-- Lua Bytecode Instructions
-- Generated by Relua

-- Chunk: lineDefined=0, lastLineDefined=0, numParams=0, isVararg=2, maxStackSize=4

-- Raw Instructions:
-- pc=00 raw=0x00004026 opcodeNum=38 A=0 B=0 C=1 Bx=1 sBx=-131070
-- pc=01 raw=0x0040801B opcodeNum=27 A=0 B=0 C=258 Bx=258 sBx=-130813
-- pc=02 raw=0x00808010 opcodeNum=16 A=0 B=1 C=2 Bx=514 sBx=-130557
-- pc=03 raw=0x00000028 opcodeNum=40 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=04 raw=0x0000C026 opcodeNum=38 A=0 B=0 C=3 Bx=3 sBx=-131068
-- pc=05 raw=0x00010046 opcodeNum=6 A=1 B=0 C=4 Bx=4 sBx=-131067
-- pc=06 raw=0x000140A6 opcodeNum=38 A=2 B=0 C=5 Bx=5 sBx=-131066
-- pc=07 raw=0x0141809B opcodeNum=27 A=2 B=2 C=262 Bx=1286 sBx=-129785
-- pc=08 raw=0x01804010 opcodeNum=16 A=0 B=3 C=1 Bx=1537 sBx=-129534
-- pc=09 raw=0x0001C026 opcodeNum=38 A=0 B=0 C=7 Bx=7 sBx=-131064
-- pc=10 raw=0x00020046 opcodeNum=6 A=1 B=0 C=8 Bx=8 sBx=-131063
-- pc=11 raw=0x01008010 opcodeNum=16 A=0 B=2 C=2 Bx=1026 sBx=-130045
-- pc=12 raw=0x0001C066 opcodeNum=38 A=1 B=0 C=7 Bx=7 sBx=-131064
-- pc=13 raw=0x00024086 opcodeNum=6 A=2 B=0 C=9 Bx=9 sBx=-131062
-- pc=14 raw=0x01004050 opcodeNum=16 A=1 B=2 C=1 Bx=1025 sBx=-130046
-- pc=15 raw=0x0001C066 opcodeNum=38 A=1 B=0 C=7 Bx=7 sBx=-131064
-- pc=16 raw=0x00028086 opcodeNum=6 A=2 B=0 C=10 Bx=10 sBx=-131061
-- pc=17 raw=0x01004050 opcodeNum=16 A=1 B=2 C=1 Bx=1025 sBx=-130046
-- pc=18 raw=0x0001C066 opcodeNum=38 A=1 B=0 C=7 Bx=7 sBx=-131064
-- pc=19 raw=0x0002C086 opcodeNum=6 A=2 B=0 C=11 Bx=11 sBx=-131060
-- pc=20 raw=0x01004050 opcodeNum=16 A=1 B=2 C=1 Bx=1025 sBx=-130046
-- pc=21 raw=0x0001C066 opcodeNum=38 A=1 B=0 C=7 Bx=7 sBx=-131064
-- pc=22 raw=0x00030086 opcodeNum=6 A=2 B=0 C=12 Bx=12 sBx=-131059
-- pc=23 raw=0x01004050 opcodeNum=16 A=1 B=2 C=1 Bx=1025 sBx=-130046
-- pc=24 raw=0x00000041 opcodeNum=1 A=1 B=0 C=0 Bx=0 sBx=-131071
-- pc=25 raw=0x00000024 opcodeNum=36 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=26 raw=0x00004081 opcodeNum=1 A=2 B=0 C=1 Bx=1 sBx=-131070
-- pc=27 raw=0x000080C1 opcodeNum=1 A=3 B=0 C=2 Bx=2 sBx=-131069
-- pc=28 raw=0x01000024 opcodeNum=36 A=0 B=2 C=0 Bx=1024 sBx=-130047
-- pc=29 raw=0x00800024 opcodeNum=36 A=0 B=1 C=0 Bx=512 sBx=-130559
-- pc=30 raw=0x00000024 opcodeNum=36 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=31 raw=0x000340E8 opcodeNum=40 A=3 B=0 C=13 Bx=13 sBx=-131058
-- pc=32 raw=0x00800008 opcodeNum=8 A=0 B=1 C=0 Bx=512 sBx=-130559

-- Register Operations:
   0: GETGLOBAL	R0 K1              ; R0 := os
   1: GETTABLE	R0 R0 K2            ; R0 := R0["clock"]
   2: CALL	R0 1 2                  ; R0 := R0()
   3: SETGLOBAL	R0 K0              ; exectime := R0
   4: GETGLOBAL	R0 K3              ; R0 := module
   5: LOADK	R1 K4                  ; R1 := "luci.sgi.cgi"
   6: GETGLOBAL	R2 K5              ; R2 := package
   7: GETTABLE	R2 R2 K6            ; R2 := R2["seeall"]
   8: CALL	R0 3 1                  ; R0(R1, R2)
   9: GETGLOBAL	R0 K7              ; R0 := require
  10: LOADK	R1 K8                  ; R1 := "luci.ltn12"
  11: CALL	R0 2 2                  ; R0 := R0(R1)
  12: GETGLOBAL	R1 K7              ; R1 := require
  13: LOADK	R2 K9                  ; R2 := "nixio.util"
  14: CALL	R1 2 1                  ; R1(R2)
  15: GETGLOBAL	R1 K7              ; R1 := require
  16: LOADK	R2 K10                 ; R2 := "luci.http"
  17: CALL	R1 2 1                  ; R1(R2)
  18: GETGLOBAL	R1 K7              ; R1 := require
  19: LOADK	R2 K11                 ; R2 := "luci.sys"
  20: CALL	R1 2 1                  ; R1(R2)
  21: GETGLOBAL	R1 K7              ; R1 := require
  22: LOADK	R2 K12                 ; R2 := "luci.dispatcher"
  23: CALL	R1 2 1                  ; R1(R2)
  24: CLOSURE	R1 0                 ; R1 := closure(0)
  25: MOVE	R0 R0                   ; R0 := R0
  26: CLOSURE	R2 1                 ; R2 := closure(1)
  27: CLOSURE	R3 2                 ; R3 := closure(2)
  28: MOVE	R0 R2                   ; R0 := R2
  29: MOVE	R0 R1                   ; R0 := R1
  30: MOVE	R0 R0                   ; R0 := R0
  31: SETGLOBAL	R3 K13             ; run := R3
  32: RETURN	R0 1                  ; return

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=35, lastLineDefined=52, numParams=2, isVararg=0, maxStackSize=4

-- Raw Instructions:
-- pc=00 raw=0x00004049 opcodeNum=9 A=1 B=0 C=1 Bx=1 sBx=-131070
-- pc=01 raw=0x8000001F opcodeNum=31 A=0 B=256 C=0 Bx=131072 sBx=1
-- pc=02 raw=0x00000046 opcodeNum=6 A=1 B=0 C=0 Bx=0 sBx=-131071
-- pc=03 raw=0x00000092 opcodeNum=18 A=2 B=0 C=0 Bx=0 sBx=-131071
-- pc=04 raw=0x0140409B opcodeNum=27 A=2 B=2 C=257 Bx=1281 sBx=-129790
-- pc=05 raw=0x000000C1 opcodeNum=1 A=3 B=0 C=0 Bx=0 sBx=-131071
-- pc=06 raw=0x00800024 opcodeNum=36 A=0 B=1 C=0 Bx=512 sBx=-130559
-- pc=07 raw=0x00000024 opcodeNum=36 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=08 raw=0x01000024 opcodeNum=36 A=0 B=2 C=0 Bx=1024 sBx=-130047
-- pc=09 raw=0x010000C8 opcodeNum=8 A=3 B=2 C=0 Bx=1024 sBx=-130047
-- pc=10 raw=0x00800008 opcodeNum=8 A=0 B=1 C=0 Bx=512 sBx=-130559

-- Register Operations:
   0: TEST	R1 1                    ; if R1 then goto 3
   1: JMP	1                        ; goto 3
   2: LOADK	R1 K0                  ; R1 := 0
   3: GETUPVAL	R2 0                ; R2 := UpValue[0]
   4: GETTABLE	R2 R2 K1            ; R2 := R2["BLOCKSIZE"]
   5: CLOSURE	R3 0                 ; R3 := closure(0)
   6: MOVE	R0 R1                   ; R0 := R1
   7: MOVE	R0 R0                   ; R0 := R0
   8: MOVE	R0 R2                   ; R0 := R2
   9: RETURN	R3 2                  ; return R3
  10: RETURN	R0 1                  ; return

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=39, lastLineDefined=51, numParams=0, isVararg=0, maxStackSize=4

-- Raw Instructions:
-- pc=00 raw=0x00000012 opcodeNum=18 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=01 raw=0x00400003 opcodeNum=3 A=0 B=0 C=256 Bx=256 sBx=-130815
-- pc=02 raw=0x8001401F opcodeNum=31 A=0 B=256 C=5 Bx=131077 sBx=6
-- pc=03 raw=0x00800012 opcodeNum=18 A=0 B=1 C=0 Bx=512 sBx=-130559
-- pc=04 raw=0x0040400F opcodeNum=15 A=0 B=0 C=257 Bx=257 sBx=-130814
-- pc=05 raw=0x01004010 opcodeNum=16 A=0 B=2 C=1 Bx=1025 sBx=-130046
-- pc=06 raw=0x00000029 opcodeNum=41 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=07 raw=0x01000008 opcodeNum=8 A=0 B=2 C=0 Bx=1024 sBx=-130047
-- pc=08 raw=0x8005001F opcodeNum=31 A=0 B=256 C=20 Bx=131092 sBx=21
-- pc=09 raw=0x00000012 opcodeNum=18 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=10 raw=0x01000052 opcodeNum=18 A=1 B=2 C=0 Bx=1024 sBx=-130047
-- pc=11 raw=0x00800005 opcodeNum=5 A=0 B=1 C=0 Bx=512 sBx=-130559
-- pc=12 raw=0x8000801F opcodeNum=31 A=0 B=256 C=2 Bx=131074 sBx=3
-- pc=13 raw=0x01000012 opcodeNum=18 A=0 B=2 C=0 Bx=1024 sBx=-130047
-- pc=14 raw=0x00004009 opcodeNum=9 A=0 B=0 C=1 Bx=1 sBx=-131070
-- pc=15 raw=0x8000001F opcodeNum=31 A=0 B=256 C=0 Bx=131072 sBx=1
-- pc=16 raw=0x00000012 opcodeNum=18 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=17 raw=0x00000052 opcodeNum=18 A=1 B=0 C=0 Bx=0 sBx=-131071
-- pc=18 raw=0x0080004C opcodeNum=12 A=1 B=1 C=0 Bx=512 sBx=-130559
-- pc=19 raw=0x00000067 opcodeNum=39 A=1 B=0 C=0 Bx=0 sBx=-131071
-- pc=20 raw=0x00800052 opcodeNum=18 A=1 B=1 C=0 Bx=512 sBx=-130559
-- pc=21 raw=0x00C0804F opcodeNum=15 A=1 B=1 C=258 Bx=770 sBx=-130301
-- pc=22 raw=0x000000E4 opcodeNum=36 A=3 B=0 C=0 Bx=0 sBx=-131071
-- pc=23 raw=0x01808050 opcodeNum=16 A=1 B=3 C=2 Bx=1538 sBx=-129533
-- pc=24 raw=0x00004049 opcodeNum=9 A=1 B=0 C=1 Bx=1 sBx=-131070
-- pc=25 raw=0x8000801F opcodeNum=31 A=0 B=256 C=2 Bx=131074 sBx=3
-- pc=26 raw=0x00800092 opcodeNum=18 A=2 B=1 C=0 Bx=512 sBx=-130559
-- pc=27 raw=0x0140408F opcodeNum=15 A=2 B=2 C=257 Bx=1281 sBx=-129790
-- pc=28 raw=0x01004090 opcodeNum=16 A=2 B=2 C=1 Bx=1025 sBx=-130046
-- pc=29 raw=0x01000048 opcodeNum=8 A=1 B=2 C=0 Bx=1024 sBx=-130047
-- pc=30 raw=0x00800008 opcodeNum=8 A=0 B=1 C=0 Bx=512 sBx=-130559

-- Register Operations:
   0: GETUPVAL	R0 0                ; R0 := UpValue[0]
   1: LT	0 R0 K0                   ; if R0 >= 1 then goto 9
   2: JMP	6                        ; goto 9
   3: GETUPVAL	R0 1                ; R0 := UpValue[1]
   4: SELF	R0 R0 K1                ; R1 := R0; R0 := R0["close"]
   5: CALL	R0 2 1                  ; R0(R1)
   6: LOADNIL	R0 R0                ; R0 := nil
   7: RETURN	R0 2                  ; return R0
   8: JMP	21                       ; goto 30
   9: GETUPVAL	R0 0                ; R0 := UpValue[0]
  10: GETUPVAL	R1 2                ; R1 := UpValue[2]
  11: LT	0 R1 R0                   ; if R1 >= R0 then goto 16
  12: JMP	3                        ; goto 16
  13: GETUPVAL	R0 2                ; R0 := UpValue[2]
  14: TEST	R0 1                    ; if R0 then goto 17
  15: JMP	1                        ; goto 17
  16: GETUPVAL	R0 0                ; R0 := UpValue[0]
  17: GETUPVAL	R1 0                ; R1 := UpValue[0]
  18: SUB	R1 R1 R0                 ; R1 := R1 - R0
  19: SETUPVAL	R1 0                ; UpValue[0] := R1
  20: GETUPVAL	R1 1                ; R1 := UpValue[1]
  21: SELF	R1 R1 K2                ; R2 := R1; R1 := R1["read"]
  22: MOVE	R3 R0                   ; R3 := R0
  23: CALL	R1 3 2                  ; R1 := R1(R2, R3)
  24: TEST	R1 1                    ; if R1 then goto 29
  25: JMP	3                        ; goto 29
  26: GETUPVAL	R2 1                ; R2 := UpValue[1]
  27: SELF	R2 R2 K1                ; R3 := R2; R2 := R2["close"]
  28: CALL	R2 2 1                  ; R2(R3)
  29: RETURN	R1 2                  ; return R1
  30: RETURN	R0 1                  ; return


-- SubChunk 2:
-- SubChunk: lineDefined=56, lastLineDefined=68, numParams=0, isVararg=0, maxStackSize=3

-- Raw Instructions:
-- pc=00 raw=0x00000026 opcodeNum=38 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=01 raw=0x00004046 opcodeNum=6 A=1 B=0 C=1 Bx=1 sBx=-131070
-- pc=02 raw=0x01008010 opcodeNum=16 A=0 B=2 C=2 Bx=1026 sBx=-130045
-- pc=03 raw=0x00008066 opcodeNum=38 A=1 B=0 C=2 Bx=2 sBx=-131069
-- pc=04 raw=0x00000081 opcodeNum=1 A=2 B=0 C=0 Bx=0 sBx=-131071
-- pc=05 raw=0x00000024 opcodeNum=36 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=06 raw=0x81808051 opcodeNum=17 A=1 B=259 C=2 Bx=132610 sBx=1539
-- pc=07 raw=0x00800008 opcodeNum=8 A=0 B=1 C=0 Bx=512 sBx=-130559

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := require
   1: LOADK	R1 K1                  ; R1 := "xiaoqiang.common.XQFunction"
   2: CALL	R0 2 2                  ; R0 := R0(R1)
   3: GETGLOBAL	R1 K2              ; R1 := os
   4: CLOSURE	R2 0                 ; R2 := closure(0)
   5: MOVE	R0 R0                   ; R0 := R0
   6: SETTABLE	R1 K3 R2            ; R1["execute"] := R2
   7: RETURN	R0 1                  ; return

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=58, lastLineDefined=67, numParams=1, isVararg=0, maxStackSize=5

-- Raw Instructions:
-- pc=00 raw=0x00000052 opcodeNum=18 A=1 B=0 C=0 Bx=0 sBx=-131071
-- pc=01 raw=0x00C0005B opcodeNum=27 A=1 B=1 C=256 Bx=768 sBx=-130303
-- pc=02 raw=0x00004086 opcodeNum=6 A=2 B=0 C=1 Bx=1 sBx=-131070
-- pc=03 raw=0x000080C6 opcodeNum=6 A=3 B=0 C=2 Bx=2 sBx=-131069
-- pc=04 raw=0x00000124 opcodeNum=36 A=4 B=0 C=0 Bx=0 sBx=-131071
-- pc=05 raw=0x02010050 opcodeNum=16 A=1 B=4 C=4 Bx=2052 sBx=-129019
-- pc=06 raw=0x00C0C013 opcodeNum=19 A=0 B=1 C=259 Bx=771 sBx=-130300
-- pc=07 raw=0x8000801F opcodeNum=31 A=0 B=256 C=2 Bx=131074 sBx=3
-- pc=08 raw=0x82008122 opcodeNum=34 A=4 B=260 C=2 Bx=133122 sBx=2051
-- pc=09 raw=0x01000108 opcodeNum=8 A=4 B=2 C=0 Bx=1024 sBx=-130047
-- pc=10 raw=0x8001801F opcodeNum=31 A=0 B=256 C=6 Bx=131078 sBx=7
-- pc=11 raw=0x00C14013 opcodeNum=19 A=0 B=1 C=261 Bx=773 sBx=-130298
-- pc=12 raw=0x8000C01F opcodeNum=31 A=0 B=256 C=3 Bx=131075 sBx=4
-- pc=13 raw=0x82008122 opcodeNum=34 A=4 B=260 C=2 Bx=133122 sBx=2051
-- pc=14 raw=0x02418125 opcodeNum=37 A=4 B=4 C=262 Bx=2310 sBx=-128761
-- pc=15 raw=0x01000108 opcodeNum=8 A=4 B=2 C=0 Bx=1024 sBx=-130047
-- pc=16 raw=0x8000001F opcodeNum=31 A=0 B=256 C=0 Bx=131072 sBx=1
-- pc=17 raw=0x01000088 opcodeNum=8 A=2 B=2 C=0 Bx=1024 sBx=-130047
-- pc=18 raw=0x00800008 opcodeNum=8 A=0 B=1 C=0 Bx=512 sBx=-130559

-- Register Operations:
   0: GETUPVAL	R1 0                ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 K0            ; R1 := R1["waitExec"]
   2: LOADK	R2 K1                  ; R2 := "/bin/sh"
   3: LOADK	R3 K2                  ; R3 := "-c"
   4: MOVE	R4 R0                   ; R4 := R0
   5: CALL	R1 4 4                  ; R1, R2, R3 := R1(R2, R3, R4)
   6: EQ	0 R1 K3                   ; if R1 ~= "exited" then goto 11
   7: JMP	3                        ; goto 11
   8: MUL	R4 K4 R2                 ; R4 := 256 * R2
   9: RETURN	R4 2                  ; return R4
  10: JMP	7                        ; goto 18
  11: EQ	0 R1 K5                   ; if R1 ~= "stopped" then goto 17
  12: JMP	4                        ; goto 17
  13: MUL	R4 K4 R2                 ; R4 := 256 * R2
  14: ADD	R4 R4 K6                 ; R4 := R4 + 127
  15: RETURN	R4 2                  ; return R4
  16: JMP	1                        ; goto 18
  17: RETURN	R2 2                  ; return R2
  18: RETURN	R0 1                  ; return


-- SubChunk 3:
-- SubChunk: lineDefined=70, lastLineDefined=112, numParams=0, isVararg=0, maxStackSize=14

-- Raw Instructions:
-- pc=00 raw=0x00000012 opcodeNum=18 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=01 raw=0x00804010 opcodeNum=16 A=0 B=1 C=1 Bx=513 sBx=-130558
-- pc=02 raw=0x00000026 opcodeNum=38 A=0 B=0 C=0 Bx=0 sBx=-131071
-- pc=03 raw=0x0040401B opcodeNum=27 A=0 B=0 C=257 Bx=257 sBx=-130814
-- pc=04 raw=0x0040801B opcodeNum=27 A=0 B=0 C=258 Bx=258 sBx=-130813
-- pc=05 raw=0x00000066 opcodeNum=38 A=1 B=0 C=0 Bx=0 sBx=-131071
-- pc=06 raw=0x00C0C05B opcodeNum=27 A=1 B=1 C=259 Bx=771 sBx=-130300
-- pc=07 raw=0x00C1005B opcodeNum=27 A=1 B=1 C=260 Bx=772 sBx=-130299
-- pc=08 raw=0x00808050 opcodeNum=16 A=1 B=1 C=2 Bx=514 sBx=-130557
-- pc=09 raw=0x00800092 opcodeNum=18 A=2 B=1 C=0 Bx=512 sBx=-130559
-- pc=10 raw=0x000140E6 opcodeNum=38 A=3 B=0 C=5 Bx=5 sBx=-131066
-- pc=11 raw=0x01C180DB opcodeNum=27 A=3 B=3 C=262 Bx=1798 sBx=-129273
-- pc=12 raw=0x0001C126 opcodeNum=38 A=4 B=0 C=7 Bx=7 sBx=-131064
-- pc=13 raw=0x00000166 opcodeNum=38 A=5 B=0 C=0 Bx=0 sBx=-131071
-- pc=14 raw=0x02C0C15B opcodeNum=27 A=5 B=5 C=259 Bx=2819 sBx=-128252
-- pc=15 raw=0x02C1015B opcodeNum=27 A=5 B=5 C=260 Bx=2820 sBx=-128251
-- pc=16 raw=0x00020186 opcodeNum=6 A=6 B=0 C=8 Bx=8 sBx=-131063
-- pc=17 raw=0x01000150 opcodeNum=16 A=5 B=2 C=0 Bx=1024 sBx=-130047
-- pc=18 raw=0x00000110 opcodeNum=16 A=4 B=0 C=0 Bx=0 sBx=-131071
-- pc=19 raw=0x00008090 opcodeNum=16 A=2 B=0 C=2 Bx=2 sBx=-131069
-- pc=20 raw=0x010000D2 opcodeNum=18 A=3 B=2 C=0 Bx=1024 sBx=-130047
-- pc=21 raw=0x01C240DB opcodeNum=27 A=3 B=3 C=265 Bx=1801 sBx=-129270
-- pc=22 raw=0x01C280DB opcodeNum=27 A=3 B=3 C=266 Bx=1802 sBx=-129269
-- pc=23 raw=0x00014126 opcodeNum=38 A=4 B=0 C=5 Bx=5 sBx=-131066
-- pc=24 raw=0x0242C11B opcodeNum=27 A=4 B=4 C=267 Bx=2315 sBx=-128756
-- pc=25 raw=0x010000D0 opcodeNum=16 A=3 B=2 C=0 Bx=1024 sBx=-130047
-- pc=26 raw=0x00008010 opcodeNum=16 A=0 B=0 C=2 Bx=2 sBx=-131069
-- pc=27 raw=0x00030066 opcodeNum=38 A=1 B=0 C=12 Bx=12 sBx=-131059
-- pc=28 raw=0x00C3405B opcodeNum=27 A=1 B=1 C=269 Bx=781 sBx=-130290
-- pc=29 raw=0x000000A6 opcodeNum=38 A=2 B=0 C=0 Bx=0 sBx=-131071
-- pc=30 raw=0x0143809B opcodeNum=27 A=2 B=2 C=270 Bx=1294 sBx=-129777
-- pc=31 raw=0x0143C09B opcodeNum=27 A=2 B=2 C=271 Bx=1295 sBx=-129776
-- pc=32 raw=0x01008050 opcodeNum=16 A=1 B=2 C=2 Bx=1026 sBx=-130045
-- pc=33 raw=0x00040086 opcodeNum=6 A=2 B=0 C=16 Bx=16 sBx=-131055
-- pc=34 raw=0x008000D8 opcodeNum=24 A=3 B=1 C=0 Bx=512 sBx=-130559
-- pc=35 raw=0x00030126 opcodeNum=38 A=4 B=0 C=12 Bx=12 sBx=-131059
-- pc=36 raw=0x0244411B opcodeNum=27 A=4 B=4 C=273 Bx=2321 sBx=-128750
-- pc=37 raw=0x00800164 opcodeNum=36 A=5 B=1 C=0 Bx=512 sBx=-130559
-- pc=38 raw=0x01008110 opcodeNum=16 A=4 B=2 C=2 Bx=1026 sBx=-130045
-- pc=39 raw=0x02448054 opcodeNum=20 A=1 B=4 C=274 Bx=2322 sBx=-128749
-- pc=40 raw=0x8014C01F opcodeNum=31 A=0 B=256 C=83 Bx=131155 sBx=84
-- pc=41 raw=0x00030126 opcodeNum=38 A=4 B=0 C=12 Bx=12 sBx=-131059
-- pc=42 raw=0x0244C11B opcodeNum=27 A=4 B=4 C=275 Bx=2323 sBx=-128748
-- pc=43 raw=0x00800164 opcodeNum=36 A=5 B=1 C=0 Bx=512 sBx=-130559
-- pc=44 raw=0x000001A4 opcodeNum=36 A=6 B=0 C=0 Bx=0 sBx=-131071
-- pc=45 raw=0x01814110 opcodeNum=16 A=4 B=3 C=5 Bx=1541 sBx=-129530
-- pc=46 raw=0x00004109 opcodeNum=9 A=4 B=0 C=1 Bx=1 sBx=-131070
-- pc=47 raw=0x8002401F opcodeNum=31 A=0 B=256 C=9 Bx=131081 sBx=10
-- pc=48 raw=0x00050226 opcodeNum=38 A=8 B=0 C=20 Bx=20 sBx=-131051
-- pc=49 raw=0x00054246 opcodeNum=6 A=9 B=0 C=21 Bx=21 sBx=-131050
-- pc=50 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=51 raw=0x00050226 opcodeNum=38 A=8 B=0 C=20 Bx=20 sBx=-131051
-- pc=52 raw=0x00058246 opcodeNum=6 A=9 B=0 C=22 Bx=22 sBx=-131049
-- pc=53 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=54 raw=0x00050226 opcodeNum=38 A=8 B=0 C=20 Bx=20 sBx=-131051
-- pc=55 raw=0x02800264 opcodeNum=36 A=9 B=5 C=0 Bx=2560 sBx=-128511
-- pc=56 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=57 raw=0x8010801F opcodeNum=31 A=0 B=256 C=66 Bx=131138 sBx=67
-- pc=58 raw=0x000000C9 opcodeNum=9 A=3 B=0 C=0 Bx=0 sBx=-131071
-- pc=59 raw=0x7FF9801F opcodeNum=31 A=0 B=255 C=486 Bx=131046 sBx=-25
-- pc=60 raw=0x02C5C013 opcodeNum=19 A=0 B=5 C=279 Bx=2839 sBx=-128232
-- pc=61 raw=0x8002C01F opcodeNum=31 A=0 B=256 C=11 Bx=131083 sBx=12
-- pc=62 raw=0x00014226 opcodeNum=38 A=8 B=0 C=5 Bx=5 sBx=-131066
-- pc=63 raw=0x0446021B opcodeNum=27 A=8 B=8 C=280 Bx=4376 sBx=-126695
-- pc=64 raw=0x00064246 opcodeNum=6 A=9 B=0 C=25 Bx=25 sBx=-131046
-- pc=65 raw=0x000682A6 opcodeNum=38 A=10 B=0 C=26 Bx=26 sBx=-131045
-- pc=66 raw=0x030002E4 opcodeNum=36 A=11 B=6 C=0 Bx=3072 sBx=-127999
-- pc=67 raw=0x01008290 opcodeNum=16 A=10 B=2 C=2 Bx=1026 sBx=-130045
-- pc=68 raw=0x0006C2C6 opcodeNum=6 A=11 B=0 C=27 Bx=27 sBx=-131044
-- pc=69 raw=0x03800324 opcodeNum=36 A=12 B=7 C=0 Bx=3584 sBx=-127487
-- pc=70 raw=0x00070346 opcodeNum=6 A=13 B=0 C=28 Bx=28 sBx=-131043
-- pc=71 raw=0x04834255 opcodeNum=21 A=9 B=9 C=13 Bx=4621 sBx=-126450
-- pc=72 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=73 raw=0x7FF6001F opcodeNum=31 A=0 B=255 C=472 Bx=131032 sBx=-39
-- pc=74 raw=0x02C74013 opcodeNum=19 A=0 B=5 C=285 Bx=2845 sBx=-128226
-- pc=75 raw=0x8001801F opcodeNum=31 A=0 B=256 C=6 Bx=131078 sBx=7
-- pc=76 raw=0x01000224 opcodeNum=36 A=8 B=2 C=0 Bx=1024 sBx=-130047
-- pc=77 raw=0x03000264 opcodeNum=36 A=9 B=6 C=0 Bx=3072 sBx=-127999
-- pc=78 raw=0x00078286 opcodeNum=6 A=10 B=0 C=30 Bx=30 sBx=-131041
-- pc=79 raw=0x038002E4 opcodeNum=36 A=11 B=7 C=0 Bx=3584 sBx=-127487
-- pc=80 raw=0x00070306 opcodeNum=6 A=12 B=0 C=28 Bx=28 sBx=-131043
-- pc=81 raw=0x04030095 opcodeNum=21 A=2 B=8 C=12 Bx=4108 sBx=-126963
-- pc=82 raw=0x7FF3C01F opcodeNum=31 A=0 B=255 C=463 Bx=131023 sBx=-48
-- pc=83 raw=0x02C7C013 opcodeNum=19 A=0 B=5 C=287 Bx=2847 sBx=-128224
-- pc=84 raw=0x8002001F opcodeNum=31 A=0 B=256 C=8 Bx=131080 sBx=9
-- pc=85 raw=0x00014226 opcodeNum=38 A=8 B=0 C=5 Bx=5 sBx=-131066
-- pc=86 raw=0x0446021B opcodeNum=27 A=8 B=8 C=280 Bx=4376 sBx=-126695
-- pc=87 raw=0x01000264 opcodeNum=36 A=9 B=2 C=0 Bx=1024 sBx=-130047
-- pc=88 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=89 raw=0x00014226 opcodeNum=38 A=8 B=0 C=5 Bx=5 sBx=-131066
-- pc=90 raw=0x0446021B opcodeNum=27 A=8 B=8 C=280 Bx=4376 sBx=-126695
-- pc=91 raw=0x00070246 opcodeNum=6 A=9 B=0 C=28 Bx=28 sBx=-131043
-- pc=92 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=93 raw=0x7FF1001F opcodeNum=31 A=0 B=255 C=452 Bx=131012 sBx=-59
-- pc=94 raw=0x02C80013 opcodeNum=19 A=0 B=5 C=288 Bx=2848 sBx=-128223
-- pc=95 raw=0x8002001F opcodeNum=31 A=0 B=256 C=8 Bx=131080 sBx=9
-- pc=96 raw=0x00014226 opcodeNum=38 A=8 B=0 C=5 Bx=5 sBx=-131066
-- pc=97 raw=0x0446021B opcodeNum=27 A=8 B=8 C=280 Bx=4376 sBx=-126695
-- pc=98 raw=0x00068266 opcodeNum=38 A=9 B=0 C=26 Bx=26 sBx=-131045
-- pc=99 raw=0x030042A3 opcodeNum=35 A=10 B=6 C=1 Bx=3073 sBx=-127998
-- pc=100 raw=0x8000001F opcodeNum=31 A=0 B=256 C=0 Bx=131072 sBx=1
-- pc=101 raw=0x00040286 opcodeNum=6 A=10 B=0 C=16 Bx=16 sBx=-131055
-- pc=102 raw=0x01000250 opcodeNum=16 A=9 B=2 C=0 Bx=1024 sBx=-130047
-- pc=103 raw=0x00004210 opcodeNum=16 A=8 B=0 C=1 Bx=1 sBx=-131070
-- pc=104 raw=0x7FEE401F opcodeNum=31 A=0 B=255 C=441 Bx=131001 sBx=-70
-- pc=105 raw=0x02C84013 opcodeNum=19 A=0 B=5 C=289 Bx=2849 sBx=-128222
-- pc=106 raw=0x8001C01F opcodeNum=31 A=0 B=256 C=7 Bx=131079 sBx=8
-- pc=107 raw=0x00014226 opcodeNum=38 A=8 B=0 C=5 Bx=5 sBx=-131066
-- pc=108 raw=0x0448821B opcodeNum=27 A=8 B=8 C=290 Bx=4386 sBx=-126685
-- pc=109 raw=0x00804210 opcodeNum=16 A=8 B=1 C=1 Bx=513 sBx=-130558
-- pc=110 raw=0x00014226 opcodeNum=38 A=8 B=0 C=5 Bx=5 sBx=-131066
-- pc=111 raw=0x0448C21B opcodeNum=27 A=8 B=8 C=291 Bx=4387 sBx=-126684
-- pc=112 raw=0x00804210 opcodeNum=16 A=8 B=1 C=1 Bx=513 sBx=-130558
-- pc=113 raw=0x000000D8 opcodeNum=24 A=3 B=0 C=0 Bx=0 sBx=-131071
-- pc=114 raw=0x7FEBC01F opcodeNum=31 A=0 B=255 C=431 Bx=130991 sBx=-80
-- pc=115 raw=0x02C90013 opcodeNum=19 A=0 B=5 C=292 Bx=2852 sBx=-128219
-- pc=116 raw=0x7FEB401F opcodeNum=31 A=0 B=255 C=429 Bx=130989 sBx=-82
-- pc=117 raw=0x0349420F opcodeNum=15 A=8 B=6 C=293 Bx=3365 sBx=-127706
-- pc=118 raw=0x000982A6 opcodeNum=38 A=10 B=0 C=38 Bx=38 sBx=-131033
-- pc=119 raw=0x0549C29B opcodeNum=27 A=10 B=10 C=295 Bx=5415 sBx=-125656
-- pc=120 raw=0x038002E4 opcodeNum=36 A=11 B=7 C=0 Bx=3584 sBx=-127487
-- pc=121 raw=0x02004210 opcodeNum=16 A=8 B=4 C=1 Bx=2049 sBx=-129022
-- pc=122 raw=0x0348C20F opcodeNum=15 A=8 B=6 C=291 Bx=3363 sBx=-127708
-- pc=123 raw=0x01004210 opcodeNum=16 A=8 B=2 C=1 Bx=1025 sBx=-130046
-- pc=124 raw=0x7FE9401F opcodeNum=31 A=0 B=255 C=421 Bx=130981 sBx=-90
-- pc=125 raw=0x00800008 opcodeNum=8 A=0 B=1 C=0 Bx=512 sBx=-130559

-- Register Operations:
   0: GETUPVAL	R0 0                ; R0 := UpValue[0]
   1: CALL	R0 1 1                  ; R0()
   2: GETGLOBAL	R0 K0              ; R0 := luci
   3: GETTABLE	R0 R0 K1            ; R0 := R0["http"]
   4: GETTABLE	R0 R0 K2            ; R0 := R0["Request"]
   5: GETGLOBAL	R1 K0              ; R1 := luci
   6: GETTABLE	R1 R1 K3            ; R1 := R1["sys"]
   7: GETTABLE	R1 R1 K4            ; R1 := R1["getenv"]
   8: CALL	R1 1 2                  ; R1 := R1()
   9: GETUPVAL	R2 1                ; R2 := UpValue[1]
  10: GETGLOBAL	R3 K5              ; R3 := io
  11: GETTABLE	R3 R3 K6            ; R3 := R3["stdin"]
  12: GETGLOBAL	R4 K7              ; R4 := tonumber
  13: GETGLOBAL	R5 K0              ; R5 := luci
  14: GETTABLE	R5 R5 K3            ; R5 := R5["sys"]
  15: GETTABLE	R5 R5 K4            ; R5 := R5["getenv"]
  16: LOADK	R6 K8                  ; R6 := "CONTENT_LENGTH"
  17: CALL	R5 2 0                  ; R5... := R5(R6)
  18: CALL	R4 0 0                  ; R4... := R4(R5...)
  19: CALL	R2 0 2                  ; R2 := R2(R3...)
  20: GETUPVAL	R3 2                ; R3 := UpValue[2]
  21: GETTABLE	R3 R3 K9            ; R3 := R3["sink"]
  22: GETTABLE	R3 R3 K10           ; R3 := R3["file"]
  23: GETGLOBAL	R4 K5              ; R4 := io
  24: GETTABLE	R4 R4 K11           ; R4 := R4["stderr"]
  25: CALL	R3 2 0                  ; R3... := R3(R4)
  26: CALL	R0 0 2                  ; R0 := R0(R1...)
  27: GETGLOBAL	R1 K12             ; R1 := coroutine
  28: GETTABLE	R1 R1 K13           ; R1 := R1["create"]
  29: GETGLOBAL	R2 K0              ; R2 := luci
  30: GETTABLE	R2 R2 K14           ; R2 := R2["dispatcher"]
  31: GETTABLE	R2 R2 K15           ; R2 := R2["httpdispatch"]
  32: CALL	R1 2 2                  ; R1 := R1(R2)
  33: LOADK	R2 K16                 ; R2 := ""
  34: LOADBOOL	R3 1 0              ; R3 := true
  35: GETGLOBAL	R4 K12             ; R4 := coroutine
  36: GETTABLE	R4 R4 K17           ; R4 := R4["status"]
  37: MOVE	R5 R1                   ; R5 := R1
  38: CALL	R4 2 2                  ; R4 := R4(R5)
  39: EQ	1 R4 K18                  ; if R4 == "dead" then goto 125
  40: JMP	84                       ; goto 125
  41: GETGLOBAL	R4 K12             ; R4 := coroutine
  42: GETTABLE	R4 R4 K19           ; R4 := R4["resume"]
  43: MOVE	R5 R1                   ; R5 := R1
  44: MOVE	R6 R0                   ; R6 := R0
  45: CALL	R4 3 5                  ; R4, R5, R6, R7 := R4(R5, R6)
  46: TEST	R4 1                    ; if R4 then goto 58
  47: JMP	10                       ; goto 58
  48: GETGLOBAL	R8 K20             ; R8 := print
  49: LOADK	R9 K21                 ; R9 := "Status: 500 Internal Server Error"
  50: CALL	R8 2 1                  ; R8(R9)
  51: GETGLOBAL	R8 K20             ; R8 := print
  52: LOADK	R9 K22                 ; R9 := "Content-Type: text/plain\n"
  53: CALL	R8 2 1                  ; R8(R9)
  54: GETGLOBAL	R8 K20             ; R8 := print
  55: MOVE	R9 R5                   ; R9 := R5
  56: CALL	R8 2 1                  ; R8(R9)
  57: JMP	67                       ; goto 125
  58: TEST	R3 0                    ; if not R3 then goto 35
  59: JMP	-25                      ; goto 35
  60: EQ	0 R5 K23                  ; if R5 ~= 1 then goto 74
  61: JMP	12                       ; goto 74
  62: GETGLOBAL	R8 K5              ; R8 := io
  63: GETTABLE	R8 R8 K24           ; R8 := R8["write"]
  64: LOADK	R9 K25                 ; R9 := "Status: "
  65: GETGLOBAL	R10 K26            ; R10 := tostring
  66: MOVE	R11 R6                  ; R11 := R6
  67: CALL	R10 2 2                 ; R10 := R10(R11)
  68: LOADK	R11 K27                ; R11 := " "
  69: MOVE	R12 R7                  ; R12 := R7
  70: LOADK	R13 K28                ; R13 := "\r\n"
  71: CONCAT	R9 R9 R13             ; R9 := R9 .. R13
  72: CALL	R8 2 1                  ; R8(R9)
  73: JMP	-39                      ; goto 35
  74: EQ	0 R5 K29                  ; if R5 ~= 2 then goto 83
  75: JMP	7                        ; goto 83
  76: MOVE	R8 R2                   ; R8 := R2
  77: MOVE	R9 R6                   ; R9 := R6
  78: LOADK	R10 K30                ; R10 := ": "
  79: MOVE	R11 R7                  ; R11 := R7
  80: LOADK	R12 K28                ; R12 := "\r\n"
  81: CONCAT	R2 R8 R12             ; R2 := R8 .. R12
  82: JMP	-48                      ; goto 35
  83: EQ	0 R5 K31                  ; if R5 ~= 3 then goto 94
  84: JMP	9                        ; goto 94
  85: GETGLOBAL	R8 K5              ; R8 := io
  86: GETTABLE	R8 R8 K24           ; R8 := R8["write"]
  87: MOVE	R9 R2                   ; R9 := R2
  88: CALL	R8 2 1                  ; R8(R9)
  89: GETGLOBAL	R8 K5              ; R8 := io
  90: GETTABLE	R8 R8 K24           ; R8 := R8["write"]
  91: LOADK	R9 K28                 ; R9 := "\r\n"
  92: CALL	R8 2 1                  ; R8(R9)
  93: JMP	-59                      ; goto 35
  94: EQ	0 R5 K32                  ; if R5 ~= 4 then goto 105
  95: JMP	9                        ; goto 105
  96: GETGLOBAL	R8 K5              ; R8 := io
  97: GETTABLE	R8 R8 K24           ; R8 := R8["write"]
  98: GETGLOBAL	R9 K26             ; R9 := tostring
  99: TESTSET	R10 R6 1             ; if R6 then R10 := R6; goto 102
 100: JMP	1                        ; goto 102
 101: LOADK	R10 K16                ; R10 := ""
 102: CALL	R9 2 0                  ; R9... := R9(R10)
 103: CALL	R8 0 1                  ; R8(R9...)
 104: JMP	-70                      ; goto 35
 105: EQ	0 R5 K33                  ; if R5 ~= 5 then goto 115
 106: JMP	8                        ; goto 115
 107: GETGLOBAL	R8 K5              ; R8 := io
 108: GETTABLE	R8 R8 K34           ; R8 := R8["flush"]
 109: CALL	R8 1 1                  ; R8()
 110: GETGLOBAL	R8 K5              ; R8 := io
 111: GETTABLE	R8 R8 K35           ; R8 := R8["close"]
 112: CALL	R8 1 1                  ; R8()
 113: LOADBOOL	R3 0 0              ; R3 := false
 114: JMP	-80                      ; goto 35
 115: EQ	0 R5 K36                  ; if R5 ~= 6 then goto 35
 116: JMP	-82                      ; goto 35
 117: SELF	R8 R6 K37               ; R9 := R6; R8 := R6["copyz"]
 118: GETGLOBAL	R10 K38            ; R10 := nixio
 119: GETTABLE	R10 R10 K39         ; R10 := R10["stdout"]
 120: MOVE	R11 R7                  ; R11 := R7
 121: CALL	R8 4 1                  ; R8(R9, R10, R11)
 122: SELF	R8 R6 K35               ; R9 := R6; R8 := R6["close"]
 123: CALL	R8 2 1                  ; R8(R9)
 124: JMP	-90                      ; goto 35
 125: RETURN	R0 1                  ; return

