-- Lua Bytecode Instructions
-- Generated by Relua

-- Chunk: lineDefined=0, lastLineDefined=0, numParams=0, isVararg=2, maxStackSize=18

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "luci.ltn12"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "luci.http.protocol"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K0         ; R2 := require
   7: LOADK	R3 K3             ; R3 := "luci.util"
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: GETGLOBAL	R3 K0         ; R3 := require
  10: LOADK	R4 K4             ; R4 := "string"
  11: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  12: GETGLOBAL	R4 K0         ; R4 := require
  13: LOADK	R5 K5             ; R5 := "coroutine"
  14: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  15: GETGLOBAL	R5 K0         ; R5 := require
  16: LOADK	R6 K6             ; R6 := "table"
  17: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  18: GETGLOBAL	R6 K0         ; R6 := require
  19: LOADK	R7 K7             ; R7 := "xiaoqiang.util.XQSecureUtil"
  20: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  21: GETGLOBAL	R7 K0         ; R7 := require
  22: LOADK	R8 K8             ; R8 := "xiaoqiang.util.XQParam"
  23: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  24: GETGLOBAL	R8 K0         ; R8 := require
  25: LOADK	R9 K9             ; R9 := "xiaoqiang.XQLog"
  26: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  27: GETGLOBAL	R9 K10        ; R9 := ipairs
  28: GETGLOBAL	R10 K11       ; R10 := pairs
  29: GETGLOBAL	R11 K12       ; R11 := next
  30: GETGLOBAL	R12 K13       ; R12 := type
  31: GETGLOBAL	R13 K14       ; R13 := tostring
  32: GETGLOBAL	R14 K15       ; R14 := error
  33: GETGLOBAL	R15 K16       ; R15 := module
  34: LOADK	R16 K17           ; R16 := "luci.http"
  35: GETGLOBAL	R17 K18       ; R17 := package
  36: GETTABLE	R17 R17 RK275  ; R17 := R17["seeall"]
  37: CALL	R15 3 1            ; R15 := R15(...) -- b=3, c=1
  38: GETTABLE	R15 R2 RK277   ; R15 := R2["threadlocal"]
  39: CALL	R15 1 2            ; R15 := R15(...) -- b=1, c=2
  40: SETGLOBAL	R15 K20       ; context := R15
  41: GETTABLE	R15 R2 RK279   ; R15 := R2["class"]
  42: CALL	R15 1 2            ; R15 := R15(...) -- b=1, c=2
  43: SETGLOBAL	R15 K22       ; Request := R15
  44: GETGLOBAL	R15 K22       ; R15 := Request
  45: CLOSURE	R16 0           ; R16 := closure(0)
  46: MOVE	R0 R1              ; R0 := R1
  47: SETTABLE	R15 RK280 R16  ; R15["__init__"] := R16
  48: GETGLOBAL	R15 K22       ; R15 := Request
  49: CLOSURE	R16 1           ; R16 := closure(1)
  50: SETTABLE	R15 RK281 R16  ; R15["formvalue"] := R16
  51: GETGLOBAL	R15 K22       ; R15 := Request
  52: CLOSURE	R16 2           ; R16 := closure(2)
  53: MOVE	R0 R10             ; R0 := R10
  54: MOVE	R0 R13             ; R0 := R13
  55: SETTABLE	R15 RK282 R16  ; R15["formvaluetable"] := R16
  56: GETGLOBAL	R15 K22       ; R15 := Request
  57: CLOSURE	R16 3           ; R16 := closure(3)
  58: SETTABLE	R15 RK283 R16  ; R15["content"] := R16
  59: GETGLOBAL	R15 K22       ; R15 := Request
  60: CLOSURE	R16 4           ; R16 := closure(4)
  61: MOVE	R0 R3              ; R0 := R3
  62: SETTABLE	R15 RK284 R16  ; R15["getcookie"] := R16
  63: GETGLOBAL	R15 K22       ; R15 := Request
  64: CLOSURE	R16 5           ; R16 := closure(5)
  65: SETTABLE	R15 RK285 R16  ; R15["getenv"] := R16
  66: GETGLOBAL	R15 K22       ; R15 := Request
  67: CLOSURE	R16 6           ; R16 := closure(6)
  68: SETTABLE	R15 RK286 R16  ; R15["setfilehandler"] := R16
  69: GETGLOBAL	R15 K22       ; R15 := Request
  70: CLOSURE	R16 7           ; R16 := closure(7)
  71: MOVE	R0 R1              ; R0 := R1
  72: SETTABLE	R15 RK287 R16  ; R15["_parse_input"] := R16
  73: CLOSURE	R15 8           ; R15 := closure(8)
  74: MOVE	R0 R4              ; R0 := R4
  75: SETGLOBAL	R15 K32       ; close := R15
  76: CLOSURE	R15 9           ; R15 := closure(9)
  77: SETGLOBAL	R15 K27       ; content := R15
  78: CLOSURE	R15 10          ; R15 := closure(10)
  79: SETGLOBAL	R15 K33       ; formvalue_unsafe := R15
  80: CLOSURE	R15 11          ; R15 := closure(11)
  81: MOVE	R0 R7              ; R0 := R7
  82: MOVE	R0 R8              ; R0 := R8
  83: MOVE	R0 R6              ; R0 := R6
  84: SETGLOBAL	R15 K25       ; formvalue := R15
  85: CLOSURE	R15 12          ; R15 := closure(12)
  86: MOVE	R0 R6              ; R0 := R6
  87: SETGLOBAL	R15 K34       ; xqformvalue := R15
  88: CLOSURE	R15 13          ; R15 := closure(13)
  89: SETGLOBAL	R15 K26       ; formvaluetable := R15
  90: CLOSURE	R15 14          ; R15 := closure(14)
  91: SETGLOBAL	R15 K28       ; getcookie := R15
  92: CLOSURE	R15 15          ; R15 := closure(15)
  93: SETGLOBAL	R15 K29       ; getenv := R15
  94: CLOSURE	R15 16          ; R15 := closure(16)
  95: SETGLOBAL	R15 K30       ; setfilehandler := R15
  96: CLOSURE	R15 17          ; R15 := closure(17)
  97: MOVE	R0 R4              ; R0 := R4
  98: SETGLOBAL	R15 K35       ; header := R15
  99: CLOSURE	R15 18          ; R15 := closure(18)
 100: SETGLOBAL	R15 K36       ; prepare_content := R15
 101: CLOSURE	R15 19          ; R15 := closure(19)
 102: SETGLOBAL	R15 K37       ; source := R15
 103: CLOSURE	R15 20          ; R15 := closure(20)
 104: MOVE	R0 R4              ; R0 := R4
 105: SETGLOBAL	R15 K38       ; status := R15
 106: CLOSURE	R15 21          ; R15 := closure(21)
 107: MOVE	R0 R14             ; R0 := R14
 108: MOVE	R0 R13             ; R0 := R13
 109: MOVE	R0 R3              ; R0 := R3
 110: MOVE	R0 R4              ; R0 := R4
 111: SETGLOBAL	R15 K39       ; write := R15
 112: CLOSURE	R15 22          ; R15 := closure(22)
 113: MOVE	R0 R13             ; R0 := R13
 114: MOVE	R0 R4              ; R0 := R4
 115: SETGLOBAL	R15 K40       ; write_file := R15
 116: CLOSURE	R15 23          ; R15 := closure(23)
 117: MOVE	R0 R4              ; R0 := R4
 118: SETGLOBAL	R15 K41       ; splice := R15
 119: CLOSURE	R15 24          ; R15 := closure(24)
 120: SETGLOBAL	R15 K42       ; redirect := R15
 121: CLOSURE	R15 25          ; R15 := closure(25)
 122: MOVE	R0 R10             ; R0 := R10
 123: MOVE	R0 R5              ; R0 := R5
 124: SETGLOBAL	R15 K43       ; build_querystring := R15
 125: GETTABLE	R15 R1 RK300   ; R15 := R1["urldecode"]
 126: SETGLOBAL	R15 K44       ; urldecode := R15
 127: GETTABLE	R15 R1 RK301   ; R15 := R1["urlencode"]
 128: SETGLOBAL	R15 K45       ; urlencode := R15
 129: CLOSURE	R15 26          ; R15 := closure(26)
 130: MOVE	R0 R12             ; R0 := R12
 131: MOVE	R0 R13             ; R0 := R13
 132: SETGLOBAL	R15 K46       ; writeJsonNoLog := R15
 133: CLOSURE	R15 27          ; R15 := closure(27)
 134: SETGLOBAL	R15 K47       ; write_json := R15
 135: CLOSURE	R15 28          ; R15 := closure(28)
 136: MOVE	R0 R12             ; R0 := R12
 137: MOVE	R0 R13             ; R0 := R13
 138: SETGLOBAL	R15 K48       ; write_jsonp := R15
 139: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=43, lastLineDefined=59, numParams=4, isVararg=0, maxStackSize=7

-- Register Operations:
   0: SETTABLE	R0 RK256 R2    ; R0["input"] := R2
   1: SETTABLE	R0 RK257 R3    ; R0["error"] := R3
   2: CLOSURE	R4 0            ; R4 := closure(0)
   3: SETTABLE	R0 RK258 R4    ; R0["filehandler"] := R4
   4: NEWTABLE	R4             ; R4 := {}
   5: SETTABLE	R4 RK260 R1    ; R4["env"] := R1
   6: NEWTABLE	R5             ; R5 := {}
   7: SETTABLE	R4 RK261 R5    ; R4["headers"] := R5
   8: GETUPVAL	R5 0           ; R5 := UpValue[0]
   9: GETTABLE	R5 R5 RK263    ; R5 := R5["urldecode_params"]
  10: GETTABLE	R6 R1 RK264    ; R6 := R1["QUERY_STRING"]
  11: TEST	R6 1 0             ; if not R6 then goto 0
  12: JMP	1                   ; goto 1
  13: LOADK	R6 K9             ; R6 := ""
  14: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  15: SETTABLE	R4 RK262 R5    ; R4["params"] := R5
  16: SETTABLE	R0 RK259 R4    ; R0["message"] := R4
  17: SETTABLE	R0 RK266 R267  ; R0["parsed_input"] := false
  18: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=49, lastLineDefined=49, numParams=0, isVararg=0, maxStackSize=2

-- Register Operations:
   0: RETURN	R0 1             ; return R0


-- SubChunk 2:
-- SubChunk: lineDefined=61, lastLineDefined=71, numParams=3, isVararg=0, maxStackSize=5

-- Register Operations:
   0: TEST	R2 1 0             ; if not R2 then goto 0
   1: JMP	5                   ; goto 5
   2: GETTABLE	R3 R0 RK256    ; R3 := R0["parsed_input"]
   3: TEST	R3 1 0             ; if not R3 then goto 0
   4: JMP	2                   ; goto 2
   5: SELF	R3 R0 R257         ; R3, R4 := R0, R257
   6: CALL	R3 2 1             ; R3 := R3(...) -- b=2, c=1
   7: TEST	R1 0 0             ; if  R1 then goto 0
   8: JMP	5                   ; goto 5
   9: GETTABLE	R3 R0 RK258    ; R3 := R0["message"]
  10: GETTABLE	R3 R3 RK259    ; R3 := R3["params"]
  11: GETTABLE	R3 R3 RK1      ; R3 := R3[R1]
  12: RETURN	R3 2             ; return R3, R4
  13: JMP	3                   ; goto 3
  14: GETTABLE	R3 R0 RK258    ; R3 := R0["message"]
  15: GETTABLE	R3 R3 RK259    ; R3 := R3["params"]
  16: RETURN	R3 2             ; return R3, R4
  17: RETURN	R0 1             ; return R0

-- SubChunk 3:
-- SubChunk: lineDefined=73, lastLineDefined=89, numParams=2, isVararg=0, maxStackSize=14

-- Register Operations:
   0: NEWTABLE	R2             ; R2 := {}
   1: TEST	R1 0 0             ; if  R1 then goto 0
   2: JMP	5                   ; goto 5
   3: MOVE	R3 R1              ; R3 := R1
   4: LOADK	R4 K0             ; R4 := "."
   5: CONCAT	R3 R3 R4         ; R3 := R3 .. R4
   6: TESTSET	R1 R1 3 0       ; if R1 == true then R1 := R1; goto 0
   7: JMP	1                   ; goto 1
   8: LOADK	R1 K0             ; R1 := "."
   9: GETTABLE	R3 R0 RK257    ; R3 := R0["parsed_input"]
  10: TEST	R3 1 0             ; if not R3 then goto 0
  11: JMP	2                   ; goto 2
  12: SELF	R3 R0 R258         ; R3, R4 := R0, R258
  13: CALL	R3 2 1             ; R3 := R3(...) -- b=2, c=1
  14: GETTABLE	R3 R0 RK259    ; R3 := R0["message"]
  15: GETTABLE	R3 R3 RK260    ; R3 := R3["params"]
  16: GETTABLE	R3 R3 RK261    ; R3 := R3[nil]
  17: GETUPVAL	R4 0           ; R4 := UpValue[0]
  18: GETTABLE	R5 R0 RK259    ; R5 := R0["message"]
  19: GETTABLE	R5 R5 RK260    ; R5 := R5["params"]
  20: CALL	R4 2 4             ; R4 := R4(...) -- b=2, c=4
  21: JMP	15                  ; goto 15
  22: SELF	R9 R7 R262         ; R9, R10 := R7, R262
  23: MOVE	R11 R1             ; R11 := R1
  24: LOADK	R12 K7            ; R12 := 1
  25: LOADBOOL	R13 1 0        ; R13 := true
  26: CALL	R9 5 2             ; R9 := R9(...) -- b=5, c=2
  27: EQ	R9 R263 0            ; if R9 == 1 then goto 0
  28: JMP	8                   ; goto 8
  29: SELF	R9 R7 R264         ; R9, R10 := R7, R264
  30: LEN	R11 R1              ; R11 := #R1
  31: ADD	R11 R11 R263        ; R11 := R11 + R263
  32: CALL	R9 3 2             ; R9 := R9(...) -- b=3, c=2
  33: GETUPVAL	R10 1          ; R10 := UpValue[1]
  34: MOVE	R11 R8             ; R11 := R8
  35: CALL	R10 2 2            ; R10 := R10(...) -- b=2, c=2
  36: SETTABLE	R2 RK9 R10     ; R2[R9] := R10
  37: TFORLOOP	R4 0 2         ; tforloop R4, R5 -- b=0, c=2
  38: JMP	-17                 ; goto -17
  39: RETURN	R2 2             ; return R2, R3
  40: RETURN	R0 1             ; return R0

-- SubChunk 4:
-- SubChunk: lineDefined=91, lastLineDefined=97, numParams=1, isVararg=0, maxStackSize=3

-- Register Operations:
   0: GETTABLE	R1 R0 RK256    ; R1 := R0["parsed_input"]
   1: TEST	R1 1 0             ; if not R1 then goto 0
   2: JMP	2                   ; goto 2
   3: SELF	R1 R0 R257         ; R1, R2 := R0, R257
   4: CALL	R1 2 1             ; R1 := R1(...) -- b=2, c=1
   5: GETTABLE	R1 R0 RK258    ; R1 := R0["message"]
   6: GETTABLE	R1 R1 RK259    ; R1 := R1["content"]
   7: GETTABLE	R2 R0 RK258    ; R2 := R0["message"]
   8: GETTABLE	R2 R2 RK260    ; R2 := R2["content_length"]
   9: RETURN	R1 3             ; return R1, R2, R3
  10: RETURN	R0 1             ; return R0

-- SubChunk 5:
-- SubChunk: lineDefined=99, lastLineDefined=104, numParams=2, isVararg=0, maxStackSize=9

-- Register Operations:
   0: GETUPVAL	R2 0           ; R2 := UpValue[0]
   1: GETTABLE	R2 R2 RK256    ; R2 := R2["gsub"]
   2: LOADK	R3 K1             ; R3 := ";"
   3: SELF	R4 R0 R258         ; R4, R5 := R0, R258
   4: LOADK	R6 K3             ; R6 := "HTTP_COOKIE"
   5: CALL	R4 3 2             ; R4 := R4(...) -- b=3, c=2
   6: TEST	R4 1 0             ; if not R4 then goto 0
   7: JMP	1                   ; goto 1
   8: LOADK	R4 K4             ; R4 := ""
   9: LOADK	R5 K1             ; R5 := ";"
  10: CONCAT	R3 R3 R5         ; R3 := R3 .. R5
  11: LOADK	R4 K5             ; R4 := "%s*;%s*"
  12: LOADK	R5 K1             ; R5 := ";"
  13: CALL	R2 4 2             ; R2 := R2(...) -- b=4, c=2
  14: LOADK	R3 K1             ; R3 := ";"
  15: MOVE	R4 R1              ; R4 := R1
  16: LOADK	R5 K6             ; R5 := "=(.-);"
  17: CONCAT	R3 R3 R5         ; R3 := R3 .. R5
  18: SELF	R4 R2 R263         ; R4, R5 := R2, R263
  19: MOVE	R6 R3              ; R6 := R3
  20: CALL	R4 3 4             ; R4 := R4(...) -- b=3, c=4
  21: TESTSET	R7 R0 6 0       ; if R0 == true then R7 := R0; goto 0
  22: JMP	3                   ; goto 3
  23: GETGLOBAL	R7 K8         ; R7 := urldecode
  24: MOVE	R8 R6              ; R8 := R6
  25: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  26: RETURN	R7 2             ; return R7, R8
  27: RETURN	R0 1             ; return R0

-- SubChunk 6:
-- SubChunk: lineDefined=106, lastLineDefined=112, numParams=2, isVararg=0, maxStackSize=3

-- Register Operations:
   0: TEST	R1 0 0             ; if  R1 then goto 0
   1: JMP	5                   ; goto 5
   2: GETTABLE	R2 R0 RK256    ; R2 := R0["message"]
   3: GETTABLE	R2 R2 RK257    ; R2 := R2["env"]
   4: GETTABLE	R2 R2 RK1      ; R2 := R2[R1]
   5: RETURN	R2 2             ; return R2, R3
   6: JMP	3                   ; goto 3
   7: GETTABLE	R2 R0 RK256    ; R2 := R0["message"]
   8: GETTABLE	R2 R2 RK257    ; R2 := R2["env"]
   9: RETURN	R2 2             ; return R2, R3
  10: RETURN	R0 1             ; return R0

-- SubChunk 7:
-- SubChunk: lineDefined=114, lastLineDefined=116, numParams=2, isVararg=0, maxStackSize=2

-- Register Operations:
   0: SETTABLE	R0 RK256 R1    ; R0["filehandler"] := R1
   1: RETURN	R0 1             ; return R0

-- SubChunk 8:
-- SubChunk: lineDefined=118, lastLineDefined=125, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETUPVAL	R1 0           ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 RK256    ; R1 := R1["parse_message_body"]
   2: GETTABLE	R2 R0 RK257    ; R2 := R0["input"]
   3: GETTABLE	R3 R0 RK258    ; R3 := R0["message"]
   4: GETTABLE	R4 R0 RK259    ; R4 := R0["filehandler"]
   5: CALL	R1 4 1             ; R1 := R1(...) -- b=4, c=1
   6: SETTABLE	R0 RK260 R261  ; R0["parsed_input"] := true
   7: RETURN	R0 1             ; return R0

-- SubChunk 9:
-- SubChunk: lineDefined=128, lastLineDefined=138, numParams=0, isVararg=0, maxStackSize=2

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := context
   1: GETTABLE	R0 R0 RK257    ; R0 := R0["eoh"]
   2: TEST	R0 1 0             ; if not R0 then goto 0
   3: JMP	6                   ; goto 6
   4: GETGLOBAL	R0 K0         ; R0 := context
   5: SETTABLE	R0 RK257 R258  ; R0["eoh"] := true
   6: GETUPVAL	R0 0           ; R0 := UpValue[0]
   7: GETTABLE	R0 R0 RK259    ; R0 := R0["yield"]
   8: LOADK	R1 K4             ; R1 := 3
   9: CALL	R0 2 1             ; R0 := R0(...) -- b=2, c=1
  10: GETGLOBAL	R0 K0         ; R0 := context
  11: GETTABLE	R0 R0 RK261    ; R0 := R0["closed"]
  12: TEST	R0 1 0             ; if not R0 then goto 0
  13: JMP	6                   ; goto 6
  14: GETGLOBAL	R0 K0         ; R0 := context
  15: SETTABLE	R0 RK261 R258  ; R0["closed"] := true
  16: GETUPVAL	R0 0           ; R0 := UpValue[0]
  17: GETTABLE	R0 R0 RK259    ; R0 := R0["yield"]
  18: LOADK	R1 K6             ; R1 := 5
  19: CALL	R0 2 1             ; R0 := R0(...) -- b=2, c=1
  20: RETURN	R0 1             ; return R0

-- SubChunk 10:
-- SubChunk: lineDefined=143, lastLineDefined=145, numParams=0, isVararg=0, maxStackSize=2

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := context
   1: GETTABLE	R0 R0 RK257    ; R0 := R0["request"]
   2: SELF	R0 R0 R258         ; R0, R1 := R0, R258
   3: TAILCALL	R0 2 0         ; tailcall R0(...) -- b=2, c=0
   4: RETURN	R0 0             ; return
   5: RETURN	R0 1             ; return R0

-- SubChunk 11:
-- SubChunk: lineDefined=151, lastLineDefined=153, numParams=2, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R2 K0         ; R2 := context
   1: GETTABLE	R2 R2 RK257    ; R2 := R2["request"]
   2: SELF	R2 R2 R258         ; R2, R3 := R2, R258
   3: MOVE	R4 R0              ; R4 := R0
   4: MOVE	R5 R1              ; R5 := R1
   5: TAILCALL	R2 4 0         ; tailcall R2(...) -- b=4, c=0
   6: RETURN	R2 0             ; return
   7: RETURN	R0 1             ; return R0

-- SubChunk 12:
-- SubChunk: lineDefined=160, lastLineDefined=172, numParams=3, isVararg=0, maxStackSize=9

-- Register Operations:
   0: GETGLOBAL	R3 K0         ; R3 := context
   1: GETTABLE	R3 R3 RK257    ; R3 := R3["request"]
   2: SELF	R3 R3 R258         ; R3, R4 := R3, R258
   3: MOVE	R5 R0              ; R5 := R0
   4: MOVE	R6 R1              ; R6 := R1
   5: CALL	R3 4 2             ; R3 := R3(...) -- b=4, c=2
   6: TEST	R2 0 0             ; if  R2 then goto 0
   7: JMP	19                  ; goto 19
   8: GETUPVAL	R4 0           ; R4 := UpValue[0]
   9: GETTABLE	R4 R4 RK259    ; R4 := R4["verify"]
  10: MOVE	R5 R3              ; R5 := R3
  11: MOVE	R6 R2              ; R6 := R2
  12: CALL	R4 3 2             ; R4 := R4(...) -- b=3, c=2
  13: EQ	R4 R260 0            ; if R4 == false then goto 0
  14: JMP	10                  ; goto 10
  15: GETUPVAL	R4 1           ; R4 := UpValue[1]
  16: GETTABLE	R4 R4 RK261    ; R4 := R4["log"]
  17: LOADK	R5 K6             ; R5 := 3
  18: LOADK	R6 K7             ; R6 := "verify false key:"
  19: MOVE	R7 R0              ; R7 := R0
  20: LOADK	R8 K8             ; R8 := " val:"
  21: CONCAT	R6 R6 R8         ; R6 := R6 .. R8
  22: MOVE	R7 R3              ; R7 := R3
  23: CALL	R4 4 1             ; R4 := R4(...) -- b=4, c=1
  24: LOADNIL	R3 R3           ; R3 := nil
  25: RETURN	R3 2             ; return R3, R4
  26: JMP	6                   ; goto 6
  27: GETUPVAL	R4 2           ; R4 := UpValue[2]
  28: GETTABLE	R4 R4 RK265    ; R4 := R4["hackCheck"]
  29: MOVE	R5 R0              ; R5 := R0
  30: MOVE	R6 R3              ; R6 := R3
  31: TAILCALL	R4 3 0         ; tailcall R4(...) -- b=3, c=0
  32: RETURN	R4 0             ; return
  33: RETURN	R0 1             ; return R0

-- SubChunk 13:
-- SubChunk: lineDefined=174, lastLineDefined=177, numParams=2, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R2 K0         ; R2 := context
   1: GETTABLE	R2 R2 RK257    ; R2 := R2["request"]
   2: SELF	R2 R2 R258         ; R2, R3 := R2, R258
   3: MOVE	R4 R0              ; R4 := R0
   4: MOVE	R5 R1              ; R5 := R1
   5: CALL	R2 4 2             ; R2 := R2(...) -- b=4, c=2
   6: GETUPVAL	R3 0           ; R3 := UpValue[0]
   7: GETTABLE	R3 R3 RK259    ; R3 := R3["xssCheck"]
   8: MOVE	R4 R2              ; R4 := R2
   9: TAILCALL	R3 2 0         ; tailcall R3(...) -- b=2, c=0
  10: RETURN	R3 0             ; return
  11: RETURN	R0 1             ; return R0

-- SubChunk 14:
-- SubChunk: lineDefined=182, lastLineDefined=184, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := context
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["request"]
   2: SELF	R1 R1 R258         ; R1, R2 := R1, R258
   3: MOVE	R3 R0              ; R3 := R0
   4: TAILCALL	R1 3 0         ; tailcall R1(...) -- b=3, c=0
   5: RETURN	R1 0             ; return
   6: RETURN	R0 1             ; return R0

-- SubChunk 15:
-- SubChunk: lineDefined=189, lastLineDefined=191, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := context
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["request"]
   2: SELF	R1 R1 R258         ; R1, R2 := R1, R258
   3: MOVE	R3 R0              ; R3 := R0
   4: TAILCALL	R1 3 0         ; tailcall R1(...) -- b=3, c=0
   5: RETURN	R1 0             ; return
   6: RETURN	R0 1             ; return R0

-- SubChunk 16:
-- SubChunk: lineDefined=197, lastLineDefined=199, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := context
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["request"]
   2: SELF	R1 R1 R258         ; R1, R2 := R1, R258
   3: MOVE	R3 R0              ; R3 := R0
   4: TAILCALL	R1 3 0         ; tailcall R1(...) -- b=3, c=0
   5: RETURN	R1 0             ; return
   6: RETURN	R0 1             ; return R0

-- SubChunk 17:
-- SubChunk: lineDefined=203, lastLineDefined=205, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := context
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["request"]
   2: SELF	R1 R1 R258         ; R1, R2 := R1, R258
   3: MOVE	R3 R0              ; R3 := R0
   4: TAILCALL	R1 3 0         ; tailcall R1(...) -- b=3, c=0
   5: RETURN	R1 0             ; return
   6: RETURN	R0 1             ; return R0

-- SubChunk 18:
-- SubChunk: lineDefined=210, lastLineDefined=216, numParams=2, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R2 K0         ; R2 := context
   1: GETTABLE	R2 R2 RK257    ; R2 := R2["headers"]
   2: TEST	R2 1 0             ; if not R2 then goto 0
   3: JMP	3                   ; goto 3
   4: GETGLOBAL	R2 K0         ; R2 := context
   5: NEWTABLE	R3             ; R3 := {}
   6: SETTABLE	R2 RK257 R3    ; R2["headers"] := R3
   7: GETGLOBAL	R2 K0         ; R2 := context
   8: GETTABLE	R2 R2 RK257    ; R2 := R2["headers"]
   9: SELF	R3 R0 R258         ; R3, R4 := R0, R258
  10: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  11: SETTABLE	R2 RK3 R1      ; R2[R3] := R1
  12: GETUPVAL	R2 0           ; R2 := UpValue[0]
  13: GETTABLE	R2 R2 RK259    ; R2 := R2["yield"]
  14: LOADK	R3 K4             ; R3 := 2
  15: MOVE	R4 R0              ; R4 := R0
  16: MOVE	R5 R1              ; R5 := R1
  17: CALL	R2 4 1             ; R2 := R2(...) -- b=4, c=1
  18: RETURN	R0 1             ; return R0

-- SubChunk 19:
-- SubChunk: lineDefined=220, lastLineDefined=231, numParams=1, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := context
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["headers"]
   2: TEST	R1 0 0             ; if  R1 then goto 0
   3: JMP	5                   ; goto 5
   4: GETGLOBAL	R1 K0         ; R1 := context
   5: GETTABLE	R1 R1 RK257    ; R1 := R1["headers"]
   6: GETTABLE	R1 R1 RK258    ; R1 := R1["content-type"]
   7: TEST	R1 1 0             ; if not R1 then goto 0
   8: JMP	26                  ; goto 26
   9: EQ	R0 R259 0            ; if R0 == "application/xhtml+xml" then goto 0
  10: JMP	20                  ; goto 20
  11: GETGLOBAL	R1 K4         ; R1 := getenv
  12: LOADK	R2 K5             ; R2 := "HTTP_ACCEPT"
  13: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  14: TEST	R1 0 0             ; if  R1 then goto 0
  15: JMP	10                  ; goto 10
  16: GETGLOBAL	R1 K4         ; R1 := getenv
  17: LOADK	R2 K5             ; R2 := "HTTP_ACCEPT"
  18: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  19: SELF	R1 R1 R262         ; R1, R2 := R1, R262
  20: LOADK	R3 K3             ; R3 := "application/xhtml+xml"
  21: LOADNIL	R4 R4           ; R4 := nil
  22: LOADBOOL	R5 1 0         ; R5 := true
  23: CALL	R1 5 2             ; R1 := R1(...) -- b=5, c=2
  24: TEST	R1 1 0             ; if not R1 then goto 0
  25: JMP	1                   ; goto 1
  26: LOADK	R0 K7             ; R0 := "text/html; charset=UTF-8"
  27: GETGLOBAL	R1 K8         ; R1 := header
  28: LOADK	R2 K9             ; R2 := "Vary"
  29: LOADK	R3 K10            ; R3 := "Accept"
  30: CALL	R1 3 1             ; R1 := R1(...) -- b=3, c=1
  31: GETGLOBAL	R1 K8         ; R1 := header
  32: LOADK	R2 K11            ; R2 := "Content-Type"
  33: MOVE	R3 R0              ; R3 := R0
  34: CALL	R1 3 1             ; R1 := R1(...) -- b=3, c=1
  35: RETURN	R0 1             ; return R0

-- SubChunk 20:
-- SubChunk: lineDefined=235, lastLineDefined=237, numParams=0, isVararg=0, maxStackSize=2

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := context
   1: GETTABLE	R0 R0 RK257    ; R0 := R0["request"]
   2: GETTABLE	R0 R0 RK258    ; R0 := R0["input"]
   3: RETURN	R0 2             ; return R0, R1
   4: RETURN	R0 1             ; return R0

-- SubChunk 21:
-- SubChunk: lineDefined=242, lastLineDefined=247, numParams=2, isVararg=0, maxStackSize=6

-- Register Operations:
   0: TEST	R0 1 0             ; if not R0 then goto 0
   1: JMP	1                   ; goto 1
   2: LOADK	R0 K0             ; R0 := 200
   3: TEST	R1 1 0             ; if not R1 then goto 0
   4: JMP	1                   ; goto 1
   5: LOADK	R1 K1             ; R1 := "OK"
   6: GETGLOBAL	R2 K2         ; R2 := context
   7: SETTABLE	R2 RK259 R0    ; R2["status"] := R0
   8: GETUPVAL	R2 0           ; R2 := UpValue[0]
   9: GETTABLE	R2 R2 RK260    ; R2 := R2["yield"]
  10: LOADK	R3 K5             ; R3 := 1
  11: MOVE	R4 R0              ; R4 := R0
  12: MOVE	R5 R1              ; R5 := R1
  13: CALL	R2 4 1             ; R2 := R2(...) -- b=4, c=1
  14: RETURN	R0 1             ; return R0

-- SubChunk 22:
-- SubChunk: lineDefined=255, lastLineDefined=291, numParams=4, isVararg=0, maxStackSize=9

-- Register Operations:
   0: TEST	R0 1 0             ; if not R0 then goto 0
   1: JMP	11                  ; goto 11
   2: TEST	R1 0 0             ; if  R1 then goto 0
   3: JMP	4                   ; goto 4
   4: GETUPVAL	R4 0           ; R4 := UpValue[0]
   5: MOVE	R5 R1              ; R5 := R1
   6: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
   7: JMP	2                   ; goto 2
   8: GETGLOBAL	R4 K0         ; R4 := close
   9: CALL	R4 1 1             ; R4 := R4(...) -- b=1, c=1
  10: LOADBOOL	R4 1 0         ; R4 := true
  11: RETURN	R4 2             ; return R4, R5
  12: JMP	78                  ; goto 78
  13: LEN	R4 R0               ; R4 := #R0
  14: EQ	R4 R257 0            ; if R4 == 0 then goto 0
  15: JMP	3                   ; goto 3
  16: LOADBOOL	R4 1 0         ; R4 := true
  17: RETURN	R4 2             ; return R4, R5
  18: JMP	72                  ; goto 72
  19: GETGLOBAL	R4 K2         ; R4 := context
  20: GETTABLE	R4 R4 RK259    ; R4 := R4["eoh"]
  21: TEST	R4 1 0             ; if not R4 then goto 0
  22: JMP	61                  ; goto 61
  23: GETGLOBAL	R4 K2         ; R4 := context
  24: GETTABLE	R4 R4 RK260    ; R4 := R4["status"]
  25: TEST	R4 1 0             ; if not R4 then goto 0
  26: JMP	2                   ; goto 2
  27: GETGLOBAL	R4 K4         ; R4 := status
  28: CALL	R4 1 1             ; R4 := R4(...) -- b=1, c=1
  29: GETGLOBAL	R4 K2         ; R4 := context
  30: GETTABLE	R4 R4 RK261    ; R4 := R4["headers"]
  31: TEST	R4 0 0             ; if  R4 then goto 0
  32: JMP	5                   ; goto 5
  33: GETGLOBAL	R4 K2         ; R4 := context
  34: GETTABLE	R4 R4 RK261    ; R4 := R4["headers"]
  35: GETTABLE	R4 R4 RK262    ; R4 := R4["content-type"]
  36: TEST	R4 1 0             ; if not R4 then goto 0
  37: JMP	11                  ; goto 11
  38: TEST	R2 0 0             ; if  R2 then goto 0
  39: JMP	5                   ; goto 5
  40: GETGLOBAL	R4 K7         ; R4 := header
  41: LOADK	R5 K8             ; R5 := "Content-Type"
  42: LOADK	R6 K9             ; R6 := "text/javascript; charset=utf-8"
  43: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  44: JMP	4                   ; goto 4
  45: GETGLOBAL	R4 K7         ; R4 := header
  46: LOADK	R5 K8             ; R5 := "Content-Type"
  47: LOADK	R6 K10            ; R6 := "text/html; charset=utf-8"
  48: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  49: GETGLOBAL	R4 K2         ; R4 := context
  50: GETTABLE	R4 R4 RK261    ; R4 := R4["headers"]
  51: GETTABLE	R4 R4 RK267    ; R4 := R4["cache-control"]
  52: TEST	R4 1 0             ; if not R4 then goto 0
  53: JMP	8                   ; goto 8
  54: GETGLOBAL	R4 K7         ; R4 := header
  55: LOADK	R5 K12            ; R5 := "Cache-Control"
  56: LOADK	R6 K13            ; R6 := "no-cache"
  57: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  58: GETGLOBAL	R4 K7         ; R4 := header
  59: LOADK	R5 K14            ; R5 := "Expires"
  60: LOADK	R6 K15            ; R6 := "0"
  61: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  62: TEST	R3 0 0             ; if  R3 then goto 0
  63: JMP	14                  ; goto 14
  64: GETGLOBAL	R4 K2         ; R4 := context
  65: GETTABLE	R4 R4 RK261    ; R4 := R4["headers"]
  66: GETTABLE	R4 R4 RK272    ; R4 := R4["Content-Length"]
  67: TEST	R4 1 0             ; if not R4 then goto 0
  68: JMP	9                   ; goto 9
  69: GETGLOBAL	R4 K7         ; R4 := header
  70: LOADK	R5 K16            ; R5 := "Content-Length"
  71: GETUPVAL	R6 1           ; R6 := UpValue[1]
  72: GETUPVAL	R7 2           ; R7 := UpValue[2]
  73: GETTABLE	R7 R7 RK273    ; R7 := R7["len"]
  74: MOVE	R8 R0              ; R8 := R0
  75: CALL	R7 2 0             ; R7 := R7(...) -- b=2, c=0
  76: CALL	R6 0 0             ; R6 := R6(...) -- b=0, c=0
  77: CALL	R4 0 1             ; R4 := R4(...) -- b=0, c=1
  78: GETGLOBAL	R4 K2         ; R4 := context
  79: SETTABLE	R4 RK259 R274  ; R4["eoh"] := true
  80: GETUPVAL	R4 3           ; R4 := UpValue[3]
  81: GETTABLE	R4 R4 RK275    ; R4 := R4["yield"]
  82: LOADK	R5 K20            ; R5 := 3
  83: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  84: GETUPVAL	R4 3           ; R4 := UpValue[3]
  85: GETTABLE	R4 R4 RK275    ; R4 := R4["yield"]
  86: LOADK	R5 K21            ; R5 := 4
  87: MOVE	R6 R0              ; R6 := R0
  88: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  89: LOADBOOL	R4 1 0         ; R4 := true
  90: RETURN	R4 2             ; return R4, R5
  91: RETURN	R0 1             ; return R0

-- SubChunk 23:
-- SubChunk: lineDefined=293, lastLineDefined=320, numParams=1, isVararg=0, maxStackSize=9

-- Register Operations:
   0: LOADK	R1 K0             ; R1 := 4194304
   1: GETGLOBAL	R2 K1         ; R2 := io
   2: GETTABLE	R2 R2 RK258    ; R2 := R2["open"]
   3: MOVE	R3 R0              ; R3 := R0
   4: LOADK	R4 K3             ; R4 := "r"
   5: CALL	R2 3 2             ; R2 := R2(...) -- b=3, c=2
   6: TEST	R2 1 0             ; if not R2 then goto 0
   7: JMP	7                   ; goto 7
   8: GETGLOBAL	R3 K4         ; R3 := status
   9: LOADK	R4 K5             ; R4 := 404
  10: LOADK	R5 K6             ; R5 := "Not Found"
  11: CALL	R3 3 1             ; R3 := R3(...) -- b=3, c=1
  12: GETGLOBAL	R3 K7         ; R3 := close
  13: CALL	R3 1 1             ; R3 := R3(...) -- b=1, c=1
  14: RETURN	R0 1             ; return R0
  15: SELF	R3 R2 R264         ; R3, R4 := R2, R264
  16: LOADK	R5 K9             ; R5 := "end"
  17: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  18: SELF	R4 R2 R264         ; R4, R5 := R2, R264
  19: LOADK	R6 K10            ; R6 := "set"
  20: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  21: GETGLOBAL	R4 K11        ; R4 := context
  22: GETTABLE	R4 R4 RK260    ; R4 := R4["status"]
  23: TEST	R4 1 0             ; if not R4 then goto 0
  24: JMP	2                   ; goto 2
  25: GETGLOBAL	R4 K4         ; R4 := status
  26: CALL	R4 1 1             ; R4 := R4(...) -- b=1, c=1
  27: GETGLOBAL	R4 K12        ; R4 := header
  28: LOADK	R5 K13            ; R5 := "Content-Type"
  29: LOADK	R6 K14            ; R6 := "text/plain; charset=utf-8"
  30: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  31: GETGLOBAL	R4 K12        ; R4 := header
  32: LOADK	R5 K15            ; R5 := "Content-Length"
  33: GETUPVAL	R6 0           ; R6 := UpValue[0]
  34: MOVE	R7 R3              ; R7 := R3
  35: CALL	R6 2 0             ; R6 := R6(...) -- b=2, c=0
  36: CALL	R4 0 1             ; R4 := R4(...) -- b=0, c=1
  37: GETGLOBAL	R4 K12        ; R4 := header
  38: LOADK	R5 K16            ; R5 := "Cache-Control"
  39: LOADK	R6 K17            ; R6 := "no-cache"
  40: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  41: GETGLOBAL	R4 K12        ; R4 := header
  42: LOADK	R5 K18            ; R5 := "Expires"
  43: LOADK	R6 K19            ; R6 := "0"
  44: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  45: GETGLOBAL	R4 K11        ; R4 := context
  46: SETTABLE	R4 RK276 R277  ; R4["eoh"] := true
  47: GETUPVAL	R4 1           ; R4 := UpValue[1]
  48: GETTABLE	R4 R4 RK278    ; R4 := R4["yield"]
  49: LOADK	R5 K23            ; R5 := 3
  50: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  51: SELF	R4 R2 R280         ; R4, R5 := R2, R280
  52: LOADK	R6 K25            ; R6 := 0
  53: CALL	R4 3 2             ; R4 := R4(...) -- b=3, c=2
  54: TEST	R4 0 0             ; if  R4 then goto 0
  55: JMP	8                   ; goto 8
  56: GETUPVAL	R4 1           ; R4 := UpValue[1]
  57: GETTABLE	R4 R4 RK278    ; R4 := R4["yield"]
  58: LOADK	R5 K26            ; R5 := 4
  59: SELF	R6 R2 R280         ; R6, R7 := R2, R280
  60: MOVE	R8 R1              ; R8 := R1
  61: CALL	R6 3 0             ; R6 := R6(...) -- b=3, c=0
  62: CALL	R4 0 1             ; R4 := R4(...) -- b=0, c=1
  63: JMP	-13                 ; goto -13
  64: SELF	R4 R2 R263         ; R4, R5 := R2, R263
  65: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  66: GETGLOBAL	R4 K7         ; R4 := close
  67: CALL	R4 1 1             ; R4 := R4(...) -- b=1, c=1
  68: RETURN	R0 1             ; return R0

-- SubChunk 24:
-- SubChunk: lineDefined=325, lastLineDefined=327, numParams=2, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETUPVAL	R2 0           ; R2 := UpValue[0]
   1: GETTABLE	R2 R2 RK256    ; R2 := R2["yield"]
   2: LOADK	R3 K1             ; R3 := 6
   3: MOVE	R4 R0              ; R4 := R0
   4: MOVE	R5 R1              ; R5 := R1
   5: CALL	R2 4 1             ; R2 := R2(...) -- b=4, c=1
   6: RETURN	R0 1             ; return R0

-- SubChunk 25:
-- SubChunk: lineDefined=331, lastLineDefined=335, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := status
   1: LOADK	R2 K1             ; R2 := 302
   2: LOADK	R3 K2             ; R3 := "Found"
   3: CALL	R1 3 1             ; R1 := R1(...) -- b=3, c=1
   4: GETGLOBAL	R1 K3         ; R1 := header
   5: LOADK	R2 K4             ; R2 := "Location"
   6: MOVE	R3 R0              ; R3 := R0
   7: CALL	R1 3 1             ; R1 := R1(...) -- b=3, c=1
   8: GETGLOBAL	R1 K5         ; R1 := close
   9: CALL	R1 1 1             ; R1 := R1(...) -- b=1, c=1
  10: RETURN	R0 1             ; return R0

-- SubChunk 26:
-- SubChunk: lineDefined=340, lastLineDefined=352, numParams=1, isVararg=0, maxStackSize=10

-- Register Operations:
   0: NEWTABLE	R1             ; R1 := {}
   1: LOADK	R2 K0             ; R2 := "?"
   2: SETLIST	R1 1 1          ; setlist R1, R1 -- b=1, c=1
   3: GETUPVAL	R2 0           ; R2 := UpValue[0]
   4: MOVE	R3 R0              ; R3 := R0
   5: CALL	R2 2 4             ; R2 := R2(...) -- b=2, c=4
   6: JMP	21                  ; goto 21
   7: LEN	R7 R1               ; R7 := #R1
   8: LT	R257 R7 0            ; if 1 < R7 then goto 0
   9: JMP	3                   ; goto 3
  10: LEN	R7 R1               ; R7 := #R1
  11: ADD	R7 R7 R257          ; R7 := R7 + R257
  12: SETTABLE	R1 RK7 R258    ; R1[R7] := "&"
  13: LEN	R7 R1               ; R7 := #R1
  14: ADD	R7 R7 R257          ; R7 := R7 + R257
  15: GETGLOBAL	R8 K3         ; R8 := urldecode
  16: MOVE	R9 R5              ; R9 := R5
  17: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  18: SETTABLE	R1 RK7 R8      ; R1[R7] := R8
  19: LEN	R7 R1               ; R7 := #R1
  20: ADD	R7 R7 R257          ; R7 := R7 + R257
  21: SETTABLE	R1 RK7 R260    ; R1[R7] := "="
  22: LEN	R7 R1               ; R7 := #R1
  23: ADD	R7 R7 R257          ; R7 := R7 + R257
  24: GETGLOBAL	R8 K3         ; R8 := urldecode
  25: MOVE	R9 R6              ; R9 := R6
  26: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  27: SETTABLE	R1 RK7 R8      ; R1[R7] := R8
  28: TFORLOOP	R2 0 2         ; tforloop R2, R3 -- b=0, c=2
  29: JMP	-23                 ; goto -23
  30: GETUPVAL	R2 1           ; R2 := UpValue[1]
  31: GETTABLE	R2 R2 RK261    ; R2 := R2["concat"]
  32: MOVE	R3 R1              ; R3 := R1
  33: LOADK	R4 K6             ; R4 := ""
  34: TAILCALL	R2 3 0         ; tailcall R2(...) -- b=3, c=0
  35: RETURN	R2 0             ; return
  36: RETURN	R0 1             ; return R0

-- SubChunk 27:
-- SubChunk: lineDefined=367, lastLineDefined=385, numParams=1, isVararg=0, maxStackSize=7

-- Register Operations:
   0: EQ	R0 R256 0            ; if R0 == nil then goto 0
   1: JMP	4                   ; goto 4
   2: GETGLOBAL	R1 K1         ; R1 := write
   3: LOADK	R2 K2             ; R2 := "null"
   4: CALL	R1 2 1             ; R1 := R1(...) -- b=2, c=1
   5: JMP	49                  ; goto 49
   6: GETUPVAL	R1 0           ; R1 := UpValue[0]
   7: MOVE	R2 R0              ; R2 := R0
   8: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   9: EQ	R1 R259 0            ; if R1 == "table" then goto 0
  10: JMP	12                  ; goto 12
  11: GETGLOBAL	R1 K4         ; R1 := require
  12: LOADK	R2 K5             ; R2 := "luci.json"
  13: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  14: GETGLOBAL	R2 K1         ; R2 := write
  15: GETTABLE	R3 R1 RK262    ; R3 := R1["encode"]
  16: MOVE	R4 R0              ; R4 := R0
  17: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  18: LOADNIL	R4 R4           ; R4 := nil
  19: LOADBOOL	R5 0 0         ; R5 := false
  20: LOADBOOL	R6 1 0         ; R6 := true
  21: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
  22: JMP	32                  ; goto 32
  23: GETUPVAL	R1 0           ; R1 := UpValue[0]
  24: MOVE	R2 R0              ; R2 := R0
  25: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  26: EQ	R1 R263 0            ; if R1 == "number" then goto 0
  27: JMP	5                   ; goto 5
  28: GETUPVAL	R1 0           ; R1 := UpValue[0]
  29: MOVE	R2 R0              ; R2 := R0
  30: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  31: EQ	R1 R264 0            ; if R1 == "boolean" then goto 0
  32: JMP	12                  ; goto 12
  33: EQ	R0 R0 0              ; if R0 == R0 then goto 0
  34: JMP	4                   ; goto 4
  35: GETGLOBAL	R1 K1         ; R1 := write
  36: LOADK	R2 K9             ; R2 := "Number.NaN"
  37: CALL	R1 2 1             ; R1 := R1(...) -- b=2, c=1
  38: JMP	16                  ; goto 16
  39: GETGLOBAL	R1 K1         ; R1 := write
  40: GETUPVAL	R2 1           ; R2 := UpValue[1]
  41: MOVE	R3 R0              ; R3 := R0
  42: CALL	R2 2 0             ; R2 := R2(...) -- b=2, c=0
  43: CALL	R1 0 1             ; R1 := R1(...) -- b=0, c=1
  44: JMP	10                  ; goto 10
  45: GETGLOBAL	R1 K1         ; R1 := write
  46: GETUPVAL	R2 1           ; R2 := UpValue[1]
  47: MOVE	R3 R0              ; R3 := R0
  48: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  49: SELF	R2 R2 R267         ; R2, R3 := R2, R267
  50: LOADK	R4 K12            ; R4 := "["%z-]"
  51: CLOSURE	R5 0            ; R5 := closure(0)
  52: CALL	R2 4 2             ; R2 := R2(...) -- b=4, c=2
  53: MOD	R2 R266 R2          ; R2 := R266 % R2
  54: CALL	R1 2 1             ; R1 := R1(...) -- b=2, c=1
  55: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=381, lastLineDefined=383, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: SELF	R1 R0 R257         ; R1, R2 := R0, R257
   1: LOADK	R3 K2             ; R3 := 1
   2: CALL	R1 3 2             ; R1 := R1(...) -- b=3, c=2
   3: MOD	R1 R256 R1          ; R1 := R256 % R1
   4: RETURN	R1 2             ; return R1, R2
   5: RETURN	R0 1             ; return R0


-- SubChunk 28:
-- SubChunk: lineDefined=389, lastLineDefined=393, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := require
   1: LOADK	R2 K1             ; R2 := "xiaoqiang.XQLog"
   2: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   3: GETTABLE	R2 R1 RK258    ; R2 := R1["log"]
   4: LOADK	R3 K3             ; R3 := 7
   5: MOVE	R4 R0              ; R4 := R0
   6: CALL	R2 3 1             ; R2 := R2(...) -- b=3, c=1
   7: GETGLOBAL	R2 K4         ; R2 := writeJsonNoLog
   8: MOVE	R3 R0              ; R3 := R0
   9: CALL	R2 2 1             ; R2 := R2(...) -- b=2, c=1
  10: RETURN	R0 1             ; return R0

-- SubChunk 29:
-- SubChunk: lineDefined=395, lastLineDefined=423, numParams=2, isVararg=0, maxStackSize=8

-- Register Operations:
   0: EQ	R0 R256 0            ; if R0 == nil then goto 0
   1: JMP	4                   ; goto 4
   2: GETGLOBAL	R2 K1         ; R2 := write
   3: LOADK	R3 K2             ; R3 := "null"
   4: CALL	R2 2 1             ; R2 := R2(...) -- b=2, c=1
   5: JMP	84                  ; goto 84
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: MOVE	R3 R0              ; R3 := R0
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: EQ	R2 R259 0            ; if R2 == "table" then goto 0
  10: JMP	28                  ; goto 28
  11: GETGLOBAL	R2 K4         ; R2 := require
  12: LOADK	R3 K5             ; R3 := "luci.json"
  13: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  14: TEST	R1 0 0             ; if  R1 then goto 0
  15: JMP	12                  ; goto 12
  16: GETGLOBAL	R3 K1         ; R3 := write
  17: MOVE	R4 R1              ; R4 := R1
  18: LOADK	R5 K6             ; R5 := "("
  19: GETTABLE	R6 R2 RK263    ; R6 := R2["encode"]
  20: MOVE	R7 R0              ; R7 := R0
  21: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  22: LOADK	R7 K8             ; R7 := ");"
  23: CONCAT	R4 R4 R7         ; R4 := R4 .. R7
  24: LOADNIL	R5 R5           ; R5 := nil
  25: LOADBOOL	R6 1 0         ; R6 := true
  26: CALL	R3 4 1             ; R3 := R3(...) -- b=4, c=1
  27: JMP	62                  ; goto 62
  28: GETGLOBAL	R3 K1         ; R3 := write
  29: LOADK	R4 K9             ; R4 := "jsonpHandler("
  30: GETTABLE	R5 R2 RK263    ; R5 := R2["encode"]
  31: MOVE	R6 R0              ; R6 := R0
  32: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  33: LOADK	R6 K8             ; R6 := ");"
  34: CONCAT	R4 R4 R6         ; R4 := R4 .. R6
  35: LOADNIL	R5 R5           ; R5 := nil
  36: LOADBOOL	R6 1 0         ; R6 := true
  37: CALL	R3 4 1             ; R3 := R3(...) -- b=4, c=1
  38: JMP	51                  ; goto 51
  39: GETUPVAL	R2 0           ; R2 := UpValue[0]
  40: MOVE	R3 R0              ; R3 := R0
  41: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  42: EQ	R2 R266 0            ; if R2 == "number" then goto 0
  43: JMP	5                   ; goto 5
  44: GETUPVAL	R2 0           ; R2 := UpValue[0]
  45: MOVE	R3 R0              ; R3 := R0
  46: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  47: EQ	R2 R267 0            ; if R2 == "boolean" then goto 0
  48: JMP	12                  ; goto 12
  49: EQ	R0 R0 0              ; if R0 == R0 then goto 0
  50: JMP	4                   ; goto 4
  51: GETGLOBAL	R2 K1         ; R2 := write
  52: LOADK	R3 K12            ; R3 := "Number.NaN"
  53: CALL	R2 2 1             ; R2 := R2(...) -- b=2, c=1
  54: JMP	35                  ; goto 35
  55: GETGLOBAL	R2 K1         ; R2 := write
  56: GETUPVAL	R3 1           ; R3 := UpValue[1]
  57: MOVE	R4 R0              ; R4 := R0
  58: CALL	R3 2 0             ; R3 := R3(...) -- b=2, c=0
  59: CALL	R2 0 1             ; R2 := R2(...) -- b=0, c=1
  60: JMP	29                  ; goto 29
  61: TEST	R1 0 0             ; if  R1 then goto 0
  62: JMP	15                  ; goto 15
  63: GETGLOBAL	R2 K1         ; R2 := write
  64: MOVE	R3 R1              ; R3 := R1
  65: GETUPVAL	R4 1           ; R4 := UpValue[1]
  66: MOVE	R5 R0              ; R5 := R0
  67: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  68: SELF	R4 R4 R270         ; R4, R5 := R4, R270
  69: LOADK	R6 K15            ; R6 := "["%z-]"
  70: CLOSURE	R7 0            ; R7 := closure(0)
  71: CALL	R4 4 2             ; R4 := R4(...) -- b=4, c=2
  72: MOD	R4 R269 R4          ; R4 := R269 % R4
  73: CONCAT	R3 R3 R4         ; R3 := R3 .. R4
  74: LOADNIL	R4 R4           ; R4 := nil
  75: LOADBOOL	R5 1 0         ; R5 := true
  76: CALL	R2 4 1             ; R2 := R2(...) -- b=4, c=1
  77: JMP	12                  ; goto 12
  78: GETGLOBAL	R2 K1         ; R2 := write
  79: GETUPVAL	R3 1           ; R3 := UpValue[1]
  80: MOVE	R4 R0              ; R4 := R0
  81: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  82: SELF	R3 R3 R270         ; R3, R4 := R3, R270
  83: LOADK	R5 K15            ; R5 := "["%z-]"
  84: CLOSURE	R6 1            ; R6 := closure(1)
  85: CALL	R3 4 2             ; R3 := R3(...) -- b=4, c=2
  86: MOD	R3 R272 R3          ; R3 := R272 % R3
  87: LOADNIL	R4 R4           ; R4 := nil
  88: LOADBOOL	R5 1 0         ; R5 := true
  89: CALL	R2 4 1             ; R2 := R2(...) -- b=4, c=1
  90: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=414, lastLineDefined=416, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: SELF	R1 R0 R257         ; R1, R2 := R0, R257
   1: LOADK	R3 K2             ; R3 := 1
   2: CALL	R1 3 2             ; R1 := R1(...) -- b=3, c=2
   3: MOD	R1 R256 R1          ; R1 := R256 % R1
   4: RETURN	R1 2             ; return R1, R2
   5: RETURN	R0 1             ; return R0

-- SubChunk 2:
-- SubChunk: lineDefined=418, lastLineDefined=420, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: SELF	R1 R0 R257         ; R1, R2 := R0, R257
   1: LOADK	R3 K2             ; R3 := 1
   2: CALL	R1 3 2             ; R1 := R1(...) -- b=3, c=2
   3: MOD	R1 R256 R1          ; R1 := R256 % R1
   4: RETURN	R1 2             ; return R1, R2
   5: RETURN	R0 1             ; return R0


