-- Lua Bytecode Instructions
-- Generated by Relua

-- Chunk: lineDefined=0, lastLineDefined=0, numParams=0, isVararg=2, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := module
   1: LOADK	R1 K1                  ; R1 := "luci.controller.api.xqdatacenter"
   2: GETGLOBAL	R2 K2              ; R2 := package
   3: GETTABLE	R2 R2 K3            ; R2 := R2["seeall"]
   4: CALL	R0 3 1                  ; R0(R1, R2)
   5: CLOSURE	R0 0                 ; R0 := closure(0)
   6: SETGLOBAL	R0 K4              ; index := R0
   7: GETGLOBAL	R0 K5              ; R0 := require
   8: LOADK	R1 K6                  ; R1 := "luci.http"
   9: CALL	R0 2 2                  ; R0 := R0(R1)
  10: GETGLOBAL	R1 K5              ; R1 := require
  11: LOADK	R2 K7                  ; R2 := "json"
  12: CALL	R1 2 2                  ; R1 := R1(R2)
  13: GETGLOBAL	R2 K5              ; R2 := require
  14: LOADK	R3 K8                  ; R3 := "xiaoqiang.common.XQConfigs"
  15: CALL	R2 2 2                  ; R2 := R2(R3)
  16: GETGLOBAL	R3 K5              ; R3 := require
  17: LOADK	R4 K9                  ; R4 := "xiaoqiang.common.XQFunction"
  18: CALL	R3 2 2                  ; R3 := R3(R4)
  19: GETGLOBAL	R4 K5              ; R4 := require
  20: LOADK	R5 K10                 ; R5 := "xiaoqiang.util.XQErrorUtil"
  21: CALL	R4 2 2                  ; R4 := R4(R5)
  22: CLOSURE	R5 1                 ; R5 := closure(1)
  23: MOVE	R0 R0                   ; R0 := R0
  24: SETGLOBAL	R5 K11             ; fsysProbe := R5
  25: CLOSURE	R5 2                 ; R5 := closure(2)
  26: MOVE	R0 R0                   ; R0 := R0
  27: SETGLOBAL	R5 K12             ; fsysResume := R5
  28: CLOSURE	R5 3                 ; R5 := closure(3)
  29: MOVE	R0 R3                   ; R0 := R3
  30: SETGLOBAL	R5 K13             ; chk_param := R5
  31: CLOSURE	R5 4                 ; R5 := closure(4)
  32: MOVE	R0 R0                   ; R0 := R0
  33: MOVE	R0 R3                   ; R0 := R3
  34: MOVE	R0 R2                   ; R0 := R2
  35: SETGLOBAL	R5 K14             ; tunnelRequest := R5
  36: CLOSURE	R5 5                 ; R5 := closure(5)
  37: MOVE	R0 R3                   ; R0 := R3
  38: MOVE	R0 R0                   ; R0 := R0
  39: SETGLOBAL	R5 K15             ; identifyDevice := R5
  40: CLOSURE	R5 6                 ; R5 := closure(6)
  41: MOVE	R0 R3                   ; R0 := R3
  42: MOVE	R0 R0                   ; R0 := R0
  43: SETGLOBAL	R5 K16             ; getDeviceId := R5
  44: CLOSURE	R5 7                 ; R5 := closure(7)
  45: SETGLOBAL	R5 K17             ; pathEncode := R5
  46: CLOSURE	R5 8                 ; R5 := closure(8)
  47: MOVE	R0 R0                   ; R0 := R0
  48: MOVE	R0 R3                   ; R0 := R3
  49: SETGLOBAL	R5 K18             ; download := R5
  50: CLOSURE	R5 9                 ; R5 := closure(9)
  51: MOVE	R0 R0                   ; R0 := R0
  52: SETGLOBAL	R5 K19             ; upload := R5
  53: CLOSURE	R5 10                ; R5 := closure(10)
  54: MOVE	R0 R0                   ; R0 := R0
  55: MOVE	R0 R3                   ; R0 := R3
  56: SETGLOBAL	R5 K20             ; getThumb := R5
  57: CLOSURE	R5 11                ; R5 := closure(11)
  58: MOVE	R0 R0                   ; R0 := R0
  59: MOVE	R0 R3                   ; R0 := R3
  60: SETGLOBAL	R5 K21             ; checkFileExist := R5
  61: CLOSURE	R5 12                ; R5 := closure(12)
  62: MOVE	R0 R0                   ; R0 := R0
  63: MOVE	R0 R3                   ; R0 := R3
  64: MOVE	R0 R1                   ; R0 := R1
  65: MOVE	R0 R4                   ; R0 := R4
  66: SETGLOBAL	R5 K22             ; pluginSSH := R5
  67: CLOSURE	R5 13                ; R5 := closure(13)
  68: MOVE	R0 R3                   ; R0 := R3
  69: MOVE	R0 R4                   ; R0 := R4
  70: MOVE	R0 R0                   ; R0 := R0
  71: SETGLOBAL	R5 K23             ; pluginSSHStatus := R5
  72: RETURN	R0 1                  ; return

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=3, lastLineDefined=26, numParams=0, isVararg=0, maxStackSize=8

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := node
   1: LOADK	R1 K1                  ; R1 := "api"
   2: LOADK	R2 K2                  ; R2 := "xqdatacenter"
   3: CALL	R0 3 2                  ; R0 := R0(R1, R2)
   4: GETGLOBAL	R1 K3              ; R1 := require
   5: LOADK	R2 K4                  ; R2 := "xiaoqiang.XQFeatures"
   6: CALL	R1 2 2                  ; R1 := R1(R2)
   7: GETTABLE	R1 R1 K5            ; R1 := R1["FEATURES"]
   8: GETGLOBAL	R2 K7              ; R2 := firstchild
   9: CALL	R2 1 2                  ; R2 := R2()
  10: SETTABLE	R0 K6 R2            ; R0["target"] := R2
  11: SETTABLE	R0 K8 K9            ; R0["title"] := ""
  12: SETTABLE	R0 K10 K11          ; R0["order"] := 300
  13: SETTABLE	R0 K12 K13          ; R0["sysauth"] := "admin"
  14: SETTABLE	R0 K14 K15          ; R0["sysauth_authenticator"] := "jsonauth"
  15: SETTABLE	R0 K16 K17          ; R0["index"] := true
  16: GETGLOBAL	R2 K18             ; R2 := entry
  17: NEWTABLE	R3 2 0              ; R3 := {} (size = 2,0)
  18: LOADK	R4 K1                  ; R4 := "api"
  19: LOADK	R5 K2                  ; R5 := "xqdatacenter"
  20: SETLIST	R3 2 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 2
  21: GETGLOBAL	R4 K7              ; R4 := firstchild
  22: CALL	R4 1 2                  ; R4 := R4()
  23: GETGLOBAL	R5 K19             ; R5 := _
  24: LOADK	R6 K9                  ; R6 := ""
  25: CALL	R5 2 2                  ; R5 := R5(R6)
  26: LOADK	R6 K11                 ; R6 := 300
  27: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
  28: GETTABLE	R2 R1 K20           ; R2 := R1["apps"]
  29: GETTABLE	R2 R2 K2            ; R2 := R2["xqdatacenter"]
  30: TEST	R2 0                    ; if R2 then goto 192
  31: JMP	160                      ; goto 192
  32: GETTABLE	R2 R1 K20           ; R2 := R1["apps"]
  33: GETTABLE	R2 R2 K2            ; R2 := R2["xqdatacenter"]
  34: EQ	0 R2 K21                  ; if R2 == "1" then goto 192
  35: JMP	156                      ; goto 192
  36: GETGLOBAL	R2 K18             ; R2 := entry
  37: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
  38: LOADK	R4 K1                  ; R4 := "api"
  39: LOADK	R5 K2                  ; R5 := "xqdatacenter"
  40: LOADK	R6 K22                 ; R6 := "request"
  41: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
  42: GETGLOBAL	R4 K23             ; R4 := call
  43: LOADK	R5 K24                 ; R5 := "tunnelRequest"
  44: CALL	R4 2 2                  ; R4 := R4(R5)
  45: GETGLOBAL	R5 K19             ; R5 := _
  46: LOADK	R6 K9                  ; R6 := ""
  47: CALL	R5 2 2                  ; R5 := R5(R6)
  48: LOADK	R6 K25                 ; R6 := 301
  49: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
  50: GETGLOBAL	R2 K18             ; R2 := entry
  51: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
  52: LOADK	R4 K1                  ; R4 := "api"
  53: LOADK	R5 K2                  ; R5 := "xqdatacenter"
  54: LOADK	R6 K26                 ; R6 := "identify_device"
  55: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
  56: GETGLOBAL	R4 K23             ; R4 := call
  57: LOADK	R5 K27                 ; R5 := "identifyDevice"
  58: CALL	R4 2 2                  ; R4 := R4(R5)
  59: GETGLOBAL	R5 K19             ; R5 := _
  60: LOADK	R6 K9                  ; R6 := ""
  61: CALL	R5 2 2                  ; R5 := R5(R6)
  62: LOADK	R6 K28                 ; R6 := 302
  63: LOADK	R7 K29                 ; R7 := 8
  64: CALL	R2 6 1                  ; R2(R3, R4, R5, R6, R7)
  65: GETGLOBAL	R2 K18             ; R2 := entry
  66: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
  67: LOADK	R4 K1                  ; R4 := "api"
  68: LOADK	R5 K2                  ; R5 := "xqdatacenter"
  69: LOADK	R6 K30                 ; R6 := "download"
  70: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
  71: GETGLOBAL	R4 K23             ; R4 := call
  72: LOADK	R5 K30                 ; R5 := "download"
  73: CALL	R4 2 2                  ; R4 := R4(R5)
  74: GETGLOBAL	R5 K19             ; R5 := _
  75: LOADK	R6 K9                  ; R6 := ""
  76: CALL	R5 2 2                  ; R5 := R5(R6)
  77: LOADK	R6 K31                 ; R6 := 303
  78: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
  79: GETGLOBAL	R2 K18             ; R2 := entry
  80: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
  81: LOADK	R4 K1                  ; R4 := "api"
  82: LOADK	R5 K2                  ; R5 := "xqdatacenter"
  83: LOADK	R6 K32                 ; R6 := "upload"
  84: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
  85: GETGLOBAL	R4 K23             ; R4 := call
  86: LOADK	R5 K32                 ; R5 := "upload"
  87: CALL	R4 2 2                  ; R4 := R4(R5)
  88: GETGLOBAL	R5 K19             ; R5 := _
  89: LOADK	R6 K9                  ; R6 := ""
  90: CALL	R5 2 2                  ; R5 := R5(R6)
  91: LOADK	R6 K33                 ; R6 := 304
  92: LOADK	R7 K34                 ; R7 := 16
  93: CALL	R2 6 1                  ; R2(R3, R4, R5, R6, R7)
  94: GETGLOBAL	R2 K18             ; R2 := entry
  95: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
  96: LOADK	R4 K1                  ; R4 := "api"
  97: LOADK	R5 K2                  ; R5 := "xqdatacenter"
  98: LOADK	R6 K35                 ; R6 := "thumb"
  99: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 100: GETGLOBAL	R4 K23             ; R4 := call
 101: LOADK	R5 K36                 ; R5 := "getThumb"
 102: CALL	R4 2 2                  ; R4 := R4(R5)
 103: GETGLOBAL	R5 K19             ; R5 := _
 104: LOADK	R6 K9                  ; R6 := ""
 105: CALL	R5 2 2                  ; R5 := R5(R6)
 106: LOADK	R6 K37                 ; R6 := 305
 107: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 108: GETGLOBAL	R2 K18             ; R2 := entry
 109: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
 110: LOADK	R4 K1                  ; R4 := "api"
 111: LOADK	R5 K2                  ; R5 := "xqdatacenter"
 112: LOADK	R6 K38                 ; R6 := "device_id"
 113: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 114: GETGLOBAL	R4 K23             ; R4 := call
 115: LOADK	R5 K39                 ; R5 := "getDeviceId"
 116: CALL	R4 2 2                  ; R4 := R4(R5)
 117: GETGLOBAL	R5 K19             ; R5 := _
 118: LOADK	R6 K9                  ; R6 := ""
 119: CALL	R5 2 2                  ; R5 := R5(R6)
 120: LOADK	R6 K40                 ; R6 := 306
 121: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 122: GETGLOBAL	R2 K18             ; R2 := entry
 123: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
 124: LOADK	R4 K1                  ; R4 := "api"
 125: LOADK	R5 K2                  ; R5 := "xqdatacenter"
 126: LOADK	R6 K41                 ; R6 := "check_file_exist"
 127: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 128: GETGLOBAL	R4 K23             ; R4 := call
 129: LOADK	R5 K42                 ; R5 := "checkFileExist"
 130: CALL	R4 2 2                  ; R4 := R4(R5)
 131: GETGLOBAL	R5 K19             ; R5 := _
 132: LOADK	R6 K9                  ; R6 := ""
 133: CALL	R5 2 2                  ; R5 := R5(R6)
 134: LOADK	R6 K43                 ; R6 := 307
 135: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 136: GETGLOBAL	R2 K18             ; R2 := entry
 137: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
 138: LOADK	R4 K1                  ; R4 := "api"
 139: LOADK	R5 K2                  ; R5 := "xqdatacenter"
 140: LOADK	R6 K44                 ; R6 := "plugin_ssh"
 141: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 142: GETGLOBAL	R4 K23             ; R4 := call
 143: LOADK	R5 K45                 ; R5 := "pluginSSH"
 144: CALL	R4 2 2                  ; R4 := R4(R5)
 145: GETGLOBAL	R5 K19             ; R5 := _
 146: LOADK	R6 K9                  ; R6 := ""
 147: CALL	R5 2 2                  ; R5 := R5(R6)
 148: LOADK	R6 K46                 ; R6 := 308
 149: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 150: GETGLOBAL	R2 K18             ; R2 := entry
 151: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
 152: LOADK	R4 K1                  ; R4 := "api"
 153: LOADK	R5 K2                  ; R5 := "xqdatacenter"
 154: LOADK	R6 K47                 ; R6 := "plugin_ssh_status"
 155: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 156: GETGLOBAL	R4 K23             ; R4 := call
 157: LOADK	R5 K48                 ; R5 := "pluginSSHStatus"
 158: CALL	R4 2 2                  ; R4 := R4(R5)
 159: GETGLOBAL	R5 K19             ; R5 := _
 160: LOADK	R6 K9                  ; R6 := ""
 161: CALL	R5 2 2                  ; R5 := R5(R6)
 162: LOADK	R6 K49                 ; R6 := 309
 163: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 164: GETGLOBAL	R2 K18             ; R2 := entry
 165: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
 166: LOADK	R4 K1                  ; R4 := "api"
 167: LOADK	R5 K2                  ; R5 := "xqdatacenter"
 168: LOADK	R6 K50                 ; R6 := "fsys_probe"
 169: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 170: GETGLOBAL	R4 K23             ; R4 := call
 171: LOADK	R5 K51                 ; R5 := "fsysProbe"
 172: CALL	R4 2 2                  ; R4 := R4(R5)
 173: GETGLOBAL	R5 K19             ; R5 := _
 174: LOADK	R6 K9                  ; R6 := ""
 175: CALL	R5 2 2                  ; R5 := R5(R6)
 176: LOADK	R6 K25                 ; R6 := 301
 177: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 178: GETGLOBAL	R2 K18             ; R2 := entry
 179: NEWTABLE	R3 3 0              ; R3 := {} (size = 3,0)
 180: LOADK	R4 K1                  ; R4 := "api"
 181: LOADK	R5 K2                  ; R5 := "xqdatacenter"
 182: LOADK	R6 K52                 ; R6 := "fsys_resume"
 183: SETLIST	R3 3 1               ; R3[(1-1)*50+i] := R3+i, 1 <= i <= 3
 184: GETGLOBAL	R4 K23             ; R4 := call
 185: LOADK	R5 K53                 ; R5 := "fsysResume"
 186: CALL	R4 2 2                  ; R4 := R4(R5)
 187: GETGLOBAL	R5 K19             ; R5 := _
 188: LOADK	R6 K9                  ; R6 := ""
 189: CALL	R5 2 2                  ; R5 := R5(R6)
 190: LOADK	R6 K25                 ; R6 := 301
 191: CALL	R2 5 1                  ; R2(R3, R4, R5, R6)
 192: RETURN	R0 1                  ; return

-- SubChunk 2:
-- SubChunk: lineDefined=34, lastLineDefined=50, numParams=0, isVararg=0, maxStackSize=5

-- Register Operations:
   0: NEWTABLE	R0 0 0              ; R0 := {} (size = 0,0)
   1: SETTABLE	R0 K0 K1            ; R0["code"] := 0
   2: SETTABLE	R0 K2 K3            ; R0["msg"] := ""
   3: GETGLOBAL	R1 K4              ; R1 := require
   4: LOADK	R2 K5                  ; R2 := "xiaoqiang.module.XQDisk"
   5: CALL	R1 2 2                  ; R1 := R1(R2)
   6: GETGLOBAL	R2 K6              ; R2 := tonumber
   7: GETUPVAL	R3 0                ; R3 := UpValue[0]
   8: GETTABLE	R3 R3 K7            ; R3 := R3["formvalue"]
   9: LOADK	R4 K8                  ; R4 := "type"
  10: CALL	R3 2 2                  ; R3 := R3(R4)
  11: TEST	R3 1                    ; if not R3 then goto 14
  12: JMP	1                        ; goto 14
  13: LOADK	R3 K9                  ; R3 := 3
  14: CALL	R2 2 2                  ; R2 := R2(R3)
  15: EQ	0 R2 K10                  ; if R2 == 1 then goto 20
  16: JMP	3                        ; goto 20
  17: GETTABLE	R3 R1 K11           ; R3 := R1["disk_check"]
  18: CALL	R3 1 1                  ; R3()
  19: JMP	8                        ; goto 28
  20: EQ	0 R2 K12                  ; if R2 == 2 then goto 26
  21: JMP	4                        ; goto 26
  22: GETTABLE	R3 R1 K14           ; R3 := R1["get_diskstatus"]
  23: CALL	R3 1 2                  ; R3 := R3()
  24: SETTABLE	R0 K13 R3           ; R0["status"] := R3
  25: JMP	2                        ; goto 28
  26: SETTABLE	R0 K0 K15           ; R0["code"] := 6
  27: SETTABLE	R0 K2 K16           ; R0["msg"] := "ParameterError"
  28: GETUPVAL	R3 0                ; R3 := UpValue[0]
  29: GETTABLE	R3 R3 K17           ; R3 := R3["write_json"]
  30: MOVE	R4 R0                   ; R4 := R0
  31: CALL	R3 2 1                  ; R3(R4)
  32: RETURN	R0 1                  ; return

-- SubChunk 3:
-- SubChunk: lineDefined=52, lastLineDefined=67, numParams=0, isVararg=0, maxStackSize=5

-- Register Operations:
   0: NEWTABLE	R0 0 0              ; R0 := {} (size = 0,0)
   1: SETTABLE	R0 K0 K1            ; R0["code"] := 0
   2: SETTABLE	R0 K2 K3            ; R0["msg"] := ""
   3: GETGLOBAL	R1 K4              ; R1 := require
   4: LOADK	R2 K5                  ; R2 := "xiaoqiang.module.XQDisk"
   5: CALL	R1 2 2                  ; R1 := R1(R2)
   6: GETGLOBAL	R2 K6              ; R2 := tonumber
   7: GETUPVAL	R3 0                ; R3 := UpValue[0]
   8: GETTABLE	R3 R3 K7            ; R3 := R3["formvalue"]
   9: LOADK	R4 K8                  ; R4 := "type"
  10: CALL	R3 2 2                  ; R3 := R3(R4)
  11: TEST	R3 1                    ; if not R3 then goto 14
  12: JMP	1                        ; goto 14
  13: LOADK	R3 K9                  ; R3 := 3
  14: CALL	R2 2 2                  ; R2 := R2(R3)
  15: EQ	0 R2 K10                  ; if R2 == 1 then goto 20
  16: JMP	3                        ; goto 20
  17: GETTABLE	R3 R1 K11           ; R3 := R1["disk_repair"]
  18: CALL	R3 1 1                  ; R3()
  19: JMP	8                        ; goto 28
  20: EQ	0 R2 K12                  ; if R2 == 2 then goto 26
  21: JMP	4                        ; goto 26
  22: GETTABLE	R3 R1 K14           ; R3 := R1["get_repairstatus"]
  23: CALL	R3 1 2                  ; R3 := R3()
  24: SETTABLE	R0 K13 R3           ; R0["status"] := R3
  25: JMP	2                        ; goto 28
  26: SETTABLE	R0 K0 K15           ; R0["code"] := 6
  27: SETTABLE	R0 K2 K16           ; R0["msg"] := "ParameterError"
  28: GETUPVAL	R3 0                ; R3 := UpValue[0]
  29: GETTABLE	R3 R3 K17           ; R3 := R3["write_json"]
  30: MOVE	R4 R0                   ; R4 := R0
  31: CALL	R3 2 1                  ; R3(R4)
  32: RETURN	R0 1                  ; return

-- SubChunk 4:
-- SubChunk: lineDefined=69, lastLineDefined=109, numParams=1, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETGLOBAL	R1 K0              ; R1 := require
   1: LOADK	R2 K1                  ; R2 := "xiaoqiang.XQLog"
   2: CALL	R1 2 2                  ; R1 := R1(R2)
   3: GETGLOBAL	R2 K0              ; R2 := require
   4: LOADK	R3 K2                  ; R3 := "json"
   5: CALL	R2 2 2                  ; R2 := R2(R3)
   6: GETTABLE	R3 R2 K3            ; R3 := R2["decode"]
   7: MOVE	R4 R0                   ; R4 := R0
   8: CALL	R3 2 2                  ; R3 := R3(R4)
   9: GETGLOBAL	R4 K0              ; R4 := require
  10: LOADK	R5 K4                  ; R5 := "xiaoqiang.util.XQSecureUtil"
  11: CALL	R4 2 2                  ; R4 := R4(R5)
  12: GETGLOBAL	R5 K5              ; R5 := type
  13: MOVE	R6 R3                   ; R6 := R3
  14: CALL	R5 2 2                  ; R5 := R5(R6)
  15: EQ	1 R5 K6                   ; if R5 == "table" then goto 23
  16: JMP	6                        ; goto 23
  17: GETTABLE	R5 R1 K7            ; R5 := R1["log"]
  18: LOADK	R6 K8                  ; R6 := 6
  19: LOADK	R7 K9                  ; R7 := "chk_param: wrong type"
  20: CALL	R5 3 1                  ; R5(R6, R7)
  21: LOADBOOL	R5 0 0              ; R5 := false
  22: RETURN	R5 2                  ; return R5
  23: GETTABLE	R5 R3 K10           ; R5 := R3["api"]
  24: EQ	0 R5 K11                  ; if R5 == 63 then goto 53
  25: JMP	27                       ; goto 53
  26: GETTABLE	R5 R3 K12           ; R5 := R3["path"]
  27: GETUPVAL	R6 0                ; R6 := UpValue[0]
  28: GETTABLE	R6 R6 K13           ; R6 := R6["isStrNil"]
  29: MOVE	R7 R5                   ; R7 := R5
  30: CALL	R6 2 2                  ; R6 := R6(R7)
  31: TEST	R6 0                    ; if R6 then goto 39
  32: JMP	6                        ; goto 39
  33: GETTABLE	R6 R1 K7            ; R6 := R1["log"]
  34: LOADK	R7 K8                  ; R7 := 6
  35: LOADK	R8 K14                 ; R8 := "chk_param:  path is null"
  36: CALL	R6 3 1                  ; R6(R7, R8)
  37: LOADBOOL	R6 0 0              ; R6 := false
  38: RETURN	R6 2                  ; return R6
  39: GETTABLE	R6 R4 K15           ; R6 := R4["hackCharsCheck"]
  40: MOVE	R7 R5                   ; R7 := R5
  41: CALL	R6 2 2                  ; R6 := R6(R7)
  42: EQ	0 R6 K16                  ; if R6 == "" then goto 50
  43: JMP	6                        ; goto 50
  44: GETTABLE	R7 R1 K7            ; R7 := R1["log"]
  45: LOADK	R8 K8                  ; R8 := 6
  46: LOADK	R9 K17                 ; R9 := "chk_param: path has invalid char"
  47: CALL	R7 3 1                  ; R7(R8, R9)
  48: LOADBOOL	R7 0 0              ; R7 := false
  49: RETURN	R7 2                  ; return R7
  50: LOADBOOL	R7 1 0              ; R7 := true
  51: RETURN	R7 2                  ; return R7
  52: JMP	53                       ; goto 106
  53: GETTABLE	R5 R3 K10           ; R5 := R3["api"]
  54: EQ	0 R5 K18                  ; if R5 == 7 then goto 106
  55: JMP	50                       ; goto 106
  56: GETTABLE	R5 R3 K19           ; R5 := R3["vendor"]
  57: GETTABLE	R6 R3 K20           ; R6 := R3["dev"]
  58: GETTABLE	R7 R3 K5            ; R7 := R3["type"]
  59: GETUPVAL	R8 0                ; R8 := UpValue[0]
  60: GETTABLE	R8 R8 K13           ; R8 := R8["isStrNil"]
  61: MOVE	R9 R5                   ; R9 := R5
  62: CALL	R8 2 2                  ; R8 := R8(R9)
  63: TEST	R8 1                    ; if not R8 then goto 77
  64: JMP	12                       ; goto 77
  65: GETUPVAL	R8 0                ; R8 := UpValue[0]
  66: GETTABLE	R8 R8 K13           ; R8 := R8["isStrNil"]
  67: MOVE	R9 R6                   ; R9 := R6
  68: CALL	R8 2 2                  ; R8 := R8(R9)
  69: TEST	R8 1                    ; if not R8 then goto 77
  70: JMP	6                        ; goto 77
  71: GETUPVAL	R8 0                ; R8 := UpValue[0]
  72: GETTABLE	R8 R8 K13           ; R8 := R8["isStrNil"]
  73: MOVE	R9 R7                   ; R9 := R7
  74: CALL	R8 2 2                  ; R8 := R8(R9)
  75: TEST	R8 0                    ; if R8 then goto 83
  76: JMP	6                        ; goto 83
  77: GETTABLE	R8 R1 K7            ; R8 := R1["log"]
  78: LOADK	R9 K8                  ; R9 := 6
  79: LOADK	R10 K21                ; R10 := "chk_param: param is null"
  80: CALL	R8 3 1                  ; R8(R9, R10)
  81: LOADBOOL	R8 0 0              ; R8 := false
  82: RETURN	R8 2                  ; return R8
  83: GETTABLE	R8 R4 K15           ; R8 := R4["hackCharsCheck"]
  84: MOVE	R9 R5                   ; R9 := R5
  85: CALL	R8 2 2                  ; R8 := R8(R9)
  86: EQ	1 R8 K16                  ; if R8 == "" then goto 98
  87: JMP	10                       ; goto 98
  88: GETTABLE	R8 R4 K15           ; R8 := R4["hackCharsCheck"]
  89: MOVE	R9 R6                   ; R9 := R6
  90: CALL	R8 2 2                  ; R8 := R8(R9)
  91: EQ	1 R8 K16                  ; if R8 == "" then goto 98
  92: JMP	5                        ; goto 98
  93: GETTABLE	R8 R4 K15           ; R8 := R4["hackCharsCheck"]
  94: MOVE	R9 R7                   ; R9 := R7
  95: CALL	R8 2 2                  ; R8 := R8(R9)
  96: EQ	0 R8 K16                  ; if R8 == "" then goto 104
  97: JMP	6                        ; goto 104
  98: GETTABLE	R8 R1 K7            ; R8 := R1["log"]
  99: LOADK	R9 K8                  ; R9 := 6
 100: LOADK	R10 K22                ; R10 := "chk_param: params has invalid char"
 101: CALL	R8 3 1                  ; R8(R9, R10)
 102: LOADBOOL	R8 0 0              ; R8 := false
 103: RETURN	R8 2                  ; return R8
 104: LOADBOOL	R8 1 0              ; R8 := true
 105: RETURN	R8 2                  ; return R8
 106: LOADBOOL	R5 1 0              ; R5 := true
 107: RETURN	R5 2                  ; return R5
 108: RETURN	R0 1                  ; return

-- SubChunk 5:
-- SubChunk: lineDefined=111, lastLineDefined=128, numParams=0, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := require
   1: LOADK	R1 K1                  ; R1 := "luci.util"
   2: CALL	R0 2 2                  ; R0 := R0(R1)
   3: GETGLOBAL	R1 K0              ; R1 := require
   4: LOADK	R2 K2                  ; R2 := "xiaoqiang.util.XQCryptoUtil"
   5: CALL	R1 2 2                  ; R1 := R1(R2)
   6: GETUPVAL	R2 0                ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 K3            ; R2 := R2["formvalue_unsafe"]
   8: LOADK	R3 K4                  ; R3 := "payload"
   9: CALL	R2 2 2                  ; R2 := R2(R3)
  10: NEWTABLE	R3 0 0              ; R3 := {} (size = 0,0)
  11: GETUPVAL	R4 1                ; R4 := UpValue[1]
  12: GETTABLE	R4 R4 K5            ; R4 := R4["isStrNil"]
  13: MOVE	R5 R2                   ; R5 := R2
  14: CALL	R4 2 2                  ; R4 := R4(R5)
  15: TEST	R4 1                    ; if not R4 then goto 22
  16: JMP	5                        ; goto 22
  17: GETGLOBAL	R4 K6              ; R4 := chk_param
  18: MOVE	R5 R2                   ; R5 := R2
  19: CALL	R4 2 2                  ; R4 := R4(R5)
  20: TEST	R4 1                    ; if not R4 then goto 29
  21: JMP	7                        ; goto 29
  22: SETTABLE	R3 K7 K8            ; R3["code"] := 6
  23: SETTABLE	R3 K9 K10           ; R3["msg"] := "ParameterError"
  24: GETUPVAL	R4 0                ; R4 := UpValue[0]
  25: GETTABLE	R4 R4 K11           ; R4 := R4["write_json"]
  26: MOVE	R5 R3                   ; R5 := R3
  27: CALL	R4 2 1                  ; R4(R5)
  28: RETURN	R0 1                  ; return
  29: GETTABLE	R4 R1 K12           ; R4 := R1["binaryBase64Enc"]
  30: MOVE	R5 R2                   ; R5 := R2
  31: CALL	R4 2 2                  ; R4 := R4(R5)
  32: GETUPVAL	R5 2                ; R5 := UpValue[2]
  33: GETTABLE	R5 R5 K13           ; R5 := R5["THRIFT_TUNNEL_TO_DATACENTER"]
  34: MOD	R5 R5 R4                 ; R5 := R5 % R4
  35: GETTABLE	R6 R0 K14           ; R6 := R0["exec"]
  36: MOVE	R7 R5                   ; R7 := R5
  37: CALL	R6 2 2                  ; R6 := R6(R7)
  38: MOVE	R3 R6                   ; R3 := R6
  39: GETUPVAL	R6 0                ; R6 := UpValue[0]
  40: GETTABLE	R6 R6 K15           ; R6 := R6["write"]
  41: MOVE	R7 R3                   ; R7 := R3
  42: LOADNIL	R8 R8                ; R8 := nil
  43: LOADBOOL	R9 0 0              ; R9 := false
  44: LOADBOOL	R10 1 0             ; R10 := true
  45: CALL	R6 5 1                  ; R6(R7, R8, R9, R10)
  46: RETURN	R0 1                  ; return

-- SubChunk 6:
-- SubChunk: lineDefined=130, lastLineDefined=135, numParams=0, isVararg=0, maxStackSize=3

-- Register Operations:
   0: NEWTABLE	R0 0 0              ; R0 := {} (size = 0,0)
   1: SETTABLE	R0 K0 K1            ; R0["code"] := 0
   2: GETUPVAL	R1 0                ; R1 := UpValue[0]
   3: GETTABLE	R1 R1 K3            ; R1 := R1["mattool_identify_device"]
   4: CALL	R1 1 2                  ; R1 := R1()
   5: SETTABLE	R0 K2 R1            ; R0["info"] := R1
   6: GETUPVAL	R1 1                ; R1 := UpValue[1]
   7: GETTABLE	R1 R1 K4            ; R1 := R1["write_json"]
   8: MOVE	R2 R0                   ; R2 := R0
   9: CALL	R1 2 1                  ; R1(R2)
  10: RETURN	R0 1                  ; return

-- SubChunk 7:
-- SubChunk: lineDefined=137, lastLineDefined=142, numParams=0, isVararg=0, maxStackSize=3

-- Register Operations:
   0: NEWTABLE	R0 0 0              ; R0 := {} (size = 0,0)
   1: SETTABLE	R0 K0 K1            ; R0["code"] := 0
   2: GETUPVAL	R1 0                ; R1 := UpValue[0]
   3: GETTABLE	R1 R1 K3            ; R1 := R1["mattool_get_deviceid"]
   4: CALL	R1 1 2                  ; R1 := R1()
   5: SETTABLE	R0 K2 R1            ; R0["deviceId"] := R1
   6: GETUPVAL	R1 1                ; R1 := UpValue[1]
   7: GETTABLE	R1 R1 K4            ; R1 := R1["write_json"]
   8: MOVE	R2 R0                   ; R2 := R0
   9: CALL	R1 2 1                  ; R1(R2)
  10: RETURN	R0 1                  ; return

-- SubChunk 8:
-- SubChunk: lineDefined=144, lastLineDefined=151, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETGLOBAL	R1 K1              ; R1 := require
   1: LOADK	R2 K0                  ; R2 := "lcurl"
   2: CALL	R1 2 2                  ; R1 := R1(R2)
   3: SETGLOBAL	R1 K0              ; lcurl := R1
   4: GETGLOBAL	R1 K2              ; R1 := string
   5: GETTABLE	R1 R1 K3            ; R1 := R1["gsub"]
   6: GETGLOBAL	R2 K0              ; R2 := lcurl
   7: GETTABLE	R2 R2 K4            ; R2 := R2["easy"]
   8: CALL	R2 1 2                  ; R2 := R2()
   9: SELF	R2 R2 K5                ; R3 := R2; R2 := R2["escape"]
  10: MOVE	R4 R0                   ; R4 := R0
  11: CALL	R2 3 2                  ; R2 := R2(R3, R4)
  12: LOADK	R3 K6                  ; R3 := "%%2F"
  13: LOADK	R4 K7                  ; R4 := "/"
  14: TAILCALL	R1 4 0              ; return R1(R2, R3, R4)
  15: RETURN	R1 0                  ; return R1...
  16: RETURN	R0 1                  ; return

-- SubChunk 9:
-- SubChunk: lineDefined=153, lastLineDefined=253, numParams=0, isVararg=0, maxStackSize=22

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := require
   1: LOADK	R1 K1                  ; R1 := "nixio.fs"
   2: CALL	R0 2 2                  ; R0 := R0(R1)
   3: GETGLOBAL	R1 K0              ; R1 := require
   4: LOADK	R2 K2                  ; R2 := "luci.http.protocol.mime"
   5: CALL	R1 2 2                  ; R1 := R1(R2)
   6: GETGLOBAL	R2 K0              ; R2 := require
   7: LOADK	R3 K3                  ; R3 := "luci.ltn12"
   8: CALL	R2 2 2                  ; R2 := R2(R3)
   9: GETGLOBAL	R3 K0              ; R3 := require
  10: LOADK	R4 K4                  ; R4 := "xiaoqiang.XQLog"
  11: CALL	R3 2 2                  ; R3 := R3(R4)
  12: GETUPVAL	R4 0                ; R4 := UpValue[0]
  13: GETTABLE	R4 R4 K5            ; R4 := R4["formvalue"]
  14: LOADK	R5 K6                  ; R5 := "path"
  15: LOADBOOL	R6 0 0              ; R6 := false
  16: LOADK	R7 K7                  ; R7 := "string"
  17: CALL	R4 4 2                  ; R4 := R4(R5, R6, R7)
  18: GETUPVAL	R5 1                ; R5 := UpValue[1]
  19: GETTABLE	R5 R5 K8            ; R5 := R5["isStrNil"]
  20: MOVE	R6 R4                   ; R6 := R4
  21: CALL	R5 2 2                  ; R5 := R5(R6)
  22: TEST	R5 0                    ; if R5 then goto 32
  23: JMP	8                        ; goto 32
  24: GETUPVAL	R5 0                ; R5 := UpValue[0]
  25: GETTABLE	R5 R5 K9            ; R5 := R5["status"]
  26: LOADK	R6 K10                 ; R6 := 404
  27: GETGLOBAL	R7 K11             ; R7 := _
  28: LOADK	R8 K12                 ; R8 := "no Such file"
  29: CALL	R7 2 0                  ; R7... := R7(R8)
  30: CALL	R5 0 1                  ; R5(R6...)
  31: RETURN	R0 1                  ; return
  32: LOADK	R5 K13                 ; R5 := "/userdisk/data/"
  33: LOADK	R6 K14                 ; R6 := "/mnt/"
  34: LOADK	R7 K15                 ; R7 := "/userdisk/privacyData/"
  35: LOADK	R8 K16                 ; R8 := "/userdisk/appdata/"
  36: LOADK	R9 K17                 ; R9 := "/userdisk/.thumbnails/"
  37: GETGLOBAL	R10 K7             ; R10 := string
  38: GETTABLE	R10 R10 K18         ; R10 := R10["sub"]
  39: MOVE	R11 R4                  ; R11 := R4
  40: LOADK	R12 K19                ; R12 := 1
  41: GETGLOBAL	R13 K7             ; R13 := string
  42: GETTABLE	R13 R13 K20         ; R13 := R13["len"]
  43: MOVE	R14 R5                  ; R14 := R5
  44: CALL	R13 2 0                 ; R13... := R13(R14)
  45: CALL	R10 0 2                 ; R10 := R10(R11...)
  46: EQ	1 R10 R5                  ; if R10 == R5 then goto 100
  47: JMP	52                       ; goto 100
  48: GETGLOBAL	R10 K7             ; R10 := string
  49: GETTABLE	R10 R10 K18         ; R10 := R10["sub"]
  50: MOVE	R11 R4                  ; R11 := R4
  51: LOADK	R12 K19                ; R12 := 1
  52: GETGLOBAL	R13 K7             ; R13 := string
  53: GETTABLE	R13 R13 K20         ; R13 := R13["len"]
  54: MOVE	R14 R6                  ; R14 := R6
  55: CALL	R13 2 0                 ; R13... := R13(R14)
  56: CALL	R10 0 2                 ; R10 := R10(R11...)
  57: EQ	1 R10 R6                  ; if R10 == R6 then goto 100
  58: JMP	41                       ; goto 100
  59: GETGLOBAL	R10 K7             ; R10 := string
  60: GETTABLE	R10 R10 K18         ; R10 := R10["sub"]
  61: MOVE	R11 R4                  ; R11 := R4
  62: LOADK	R12 K19                ; R12 := 1
  63: GETGLOBAL	R13 K7             ; R13 := string
  64: GETTABLE	R13 R13 K20         ; R13 := R13["len"]
  65: MOVE	R14 R7                  ; R14 := R7
  66: CALL	R13 2 0                 ; R13... := R13(R14)
  67: CALL	R10 0 2                 ; R10 := R10(R11...)
  68: EQ	1 R10 R7                  ; if R10 == R7 then goto 100
  69: JMP	30                       ; goto 100
  70: GETGLOBAL	R10 K7             ; R10 := string
  71: GETTABLE	R10 R10 K18         ; R10 := R10["sub"]
  72: MOVE	R11 R4                  ; R11 := R4
  73: LOADK	R12 K19                ; R12 := 1
  74: GETGLOBAL	R13 K7             ; R13 := string
  75: GETTABLE	R13 R13 K20         ; R13 := R13["len"]
  76: MOVE	R14 R8                  ; R14 := R8
  77: CALL	R13 2 0                 ; R13... := R13(R14)
  78: CALL	R10 0 2                 ; R10 := R10(R11...)
  79: EQ	1 R10 R8                  ; if R10 == R8 then goto 100
  80: JMP	19                       ; goto 100
  81: GETGLOBAL	R10 K7             ; R10 := string
  82: GETTABLE	R10 R10 K18         ; R10 := R10["sub"]
  83: MOVE	R11 R4                  ; R11 := R4
  84: LOADK	R12 K19                ; R12 := 1
  85: GETGLOBAL	R13 K7             ; R13 := string
  86: GETTABLE	R13 R13 K20         ; R13 := R13["len"]
  87: MOVE	R14 R9                  ; R14 := R9
  88: CALL	R13 2 0                 ; R13... := R13(R14)
  89: CALL	R10 0 2                 ; R10 := R10(R11...)
  90: EQ	1 R10 R9                  ; if R10 == R9 then goto 100
  91: JMP	8                        ; goto 100
  92: GETUPVAL	R10 0               ; R10 := UpValue[0]
  93: GETTABLE	R10 R10 K9          ; R10 := R10["status"]
  94: LOADK	R11 K21                ; R11 := 403
  95: GETGLOBAL	R12 K11            ; R12 := _
  96: LOADK	R13 K22                ; R13 := "no permission"
  97: CALL	R12 2 0                 ; R12... := R12(R13)
  98: CALL	R10 0 1                 ; R10(R11...)
  99: RETURN	R0 1                  ; return
 100: GETTABLE	R10 R3 K23          ; R10 := R3["log"]
 101: LOADK	R11 K24                ; R11 := 7
 102: LOADK	R12 K25                ; R12 := "=============path = "
 103: MOVE	R13 R4                  ; R13 := R4
 104: CONCAT	R12 R12 R13           ; R12 := R12 .. R13
 105: CALL	R10 3 1                 ; R10(R11, R12)
 106: GETGLOBAL	R10 K7             ; R10 := string
 107: GETTABLE	R10 R10 K26         ; R10 := R10["find"]
 108: MOVE	R11 R4                  ; R11 := R4
 109: LOADK	R12 K27                ; R12 := "/%.%./"
 110: CALL	R10 3 2                 ; R10 := R10(R11, R12)
 111: TEST	R10 0                   ; if R10 then goto 121
 112: JMP	8                        ; goto 121
 113: GETUPVAL	R10 0               ; R10 := UpValue[0]
 114: GETTABLE	R10 R10 K9          ; R10 := R10["status"]
 115: LOADK	R11 K10                ; R11 := 404
 116: GETGLOBAL	R12 K11            ; R12 := _
 117: LOADK	R13 K12                ; R13 := "no Such file"
 118: CALL	R12 2 0                 ; R12... := R12(R13)
 119: CALL	R10 0 1                 ; R10(R11...)
 120: RETURN	R0 1                  ; return
 121: GETTABLE	R10 R0 K28          ; R10 := R0["stat"]
 122: MOVE	R11 R4                  ; R11 := R4
 123: CALL	R10 2 2                 ; R10 := R10(R11)
 124: TEST	R10 1                   ; if not R10 then goto 134
 125: JMP	8                        ; goto 134
 126: GETUPVAL	R11 0               ; R11 := UpValue[0]
 127: GETTABLE	R11 R11 K9          ; R11 := R11["status"]
 128: LOADK	R12 K10                ; R12 := 404
 129: GETGLOBAL	R13 K11            ; R13 := _
 130: LOADK	R14 K12                ; R14 := "no Such file"
 131: CALL	R13 2 0                 ; R13... := R13(R14)
 132: CALL	R11 0 1                 ; R11(R12...)
 133: RETURN	R0 1                  ; return
 134: GETUPVAL	R11 0               ; R11 := UpValue[0]
 135: GETTABLE	R11 R11 K29         ; R11 := R11["header"]
 136: LOADK	R12 K30                ; R12 := "Accept-Ranges"
 137: LOADK	R13 K31                ; R13 := "bytes"
 138: CALL	R11 3 1                 ; R11(R12, R13)
 139: GETUPVAL	R11 0               ; R11 := UpValue[0]
 140: GETTABLE	R11 R11 K29         ; R11 := R11["header"]
 141: LOADK	R12 K32                ; R12 := "Content-Type"
 142: GETTABLE	R13 R1 K33          ; R13 := R1["to_mime"]
 143: MOVE	R14 R4                  ; R14 := R4
 144: CALL	R13 2 0                 ; R13... := R13(R14)
 145: CALL	R11 0 1                 ; R11(R12...)
 146: GETUPVAL	R11 0               ; R11 := UpValue[0]
 147: GETTABLE	R11 R11 K34         ; R11 := R11["getenv"]
 148: LOADK	R12 K35                ; R12 := "HTTP_RANGE"
 149: CALL	R11 2 2                 ; R11 := R11(R12)
 150: TEST	R11 0                   ; if R11 then goto 171
 151: JMP	19                       ; goto 171
 152: GETUPVAL	R12 0               ; R12 := UpValue[0]
 153: GETTABLE	R12 R12 K9          ; R12 := R12["status"]
 154: LOADK	R13 K36                ; R13 := 206
 155: CALL	R12 2 1                 ; R12(R13)
 156: GETGLOBAL	R12 K7             ; R12 := string
 157: GETTABLE	R12 R12 K37         ; R12 := R12["gsub"]
 158: MOVE	R13 R11                 ; R13 := R11
 159: LOADK	R14 K38                ; R14 := "bytes="
 160: LOADK	R15 K39                ; R15 := ""
 161: CALL	R12 4 2                 ; R12 := R12(R13, R14, R15)
 162: MOVE	R11 R12                 ; R11 := R12
 163: GETGLOBAL	R12 K7             ; R12 := string
 164: GETTABLE	R12 R12 K37         ; R12 := R12["gsub"]
 165: MOVE	R13 R11                 ; R13 := R11
 166: LOADK	R14 K40                ; R14 := "-"
 167: LOADK	R15 K39                ; R15 := ""
 168: CALL	R12 4 2                 ; R12 := R12(R13, R14, R15)
 169: MOVE	R11 R12                 ; R11 := R12
 170: JMP	1                        ; goto 172
 171: LOADK	R11 K41                ; R11 := 0
 172: GETTABLE	R12 R3 K23          ; R12 := R3["log"]
 173: LOADK	R13 K24                ; R13 := 7
 174: LOADK	R14 K42                ; R14 := "=============range = "
 175: MOVE	R15 R11                 ; R15 := R11
 176: CONCAT	R14 R14 R15           ; R14 := R14 .. R15
 177: CALL	R12 3 1                 ; R12(R13, R14)
 178: LOADK	R12 K43                ; R12 := "bytes "
 179: MOVE	R13 R11                 ; R13 := R11
 180: LOADK	R14 K40                ; R14 := "-"
 181: GETTABLE	R15 R10 K44         ; R15 := R10["size"]
 182: SUB	R15 R15 K19              ; R15 := R15 - 1
 183: LOADK	R16 K45                ; R16 := "/"
 184: GETTABLE	R17 R10 K44         ; R17 := R10["size"]
 185: CONCAT	R12 R12 R17           ; R12 := R12 .. R17
 186: GETTABLE	R13 R3 K23          ; R13 := R3["log"]
 187: LOADK	R14 K24                ; R14 := 7
 188: LOADK	R15 K46                ; R15 := "=============contentRange = "
 189: MOVE	R16 R12                 ; R16 := R12
 190: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 191: CALL	R13 3 1                 ; R13(R14, R15)
 192: GETUPVAL	R13 0               ; R13 := UpValue[0]
 193: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 194: LOADK	R14 K47                ; R14 := "Content-Length"
 195: GETTABLE	R15 R10 K44         ; R15 := R10["size"]
 196: SUB	R15 R15 R11              ; R15 := R15 - R11
 197: CALL	R13 3 1                 ; R13(R14, R15)
 198: GETUPVAL	R13 0               ; R13 := UpValue[0]
 199: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 200: LOADK	R14 K48                ; R14 := "Content-Range"
 201: MOVE	R15 R12                 ; R15 := R12
 202: CALL	R13 3 1                 ; R13(R14, R15)
 203: GETUPVAL	R13 0               ; R13 := UpValue[0]
 204: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 205: LOADK	R14 K49                ; R14 := "Content-Disposition"
 206: LOADK	R15 K50                ; R15 := "attachment; filename="
 207: GETTABLE	R16 R0 K51          ; R16 := R0["basename"]
 208: MOVE	R17 R4                  ; R17 := R4
 209: CALL	R16 2 2                 ; R16 := R16(R17)
 210: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 211: CALL	R13 3 1                 ; R13(R14, R15)
 212: GETGLOBAL	R13 K7             ; R13 := string
 213: GETTABLE	R13 R13 K18         ; R13 := R13["sub"]
 214: MOVE	R14 R4                  ; R14 := R4
 215: LOADK	R15 K19                ; R15 := 1
 216: GETGLOBAL	R16 K7             ; R16 := string
 217: GETTABLE	R16 R16 K20         ; R16 := R16["len"]
 218: MOVE	R17 R5                  ; R17 := R5
 219: CALL	R16 2 0                 ; R16... := R16(R17)
 220: CALL	R13 0 2                 ; R13 := R13(R14...)
 221: EQ	0 R13 R5                  ; if R13 == R5 then goto 245
 222: JMP	22                       ; goto 245
 223: GETUPVAL	R13 0               ; R13 := UpValue[0]
 224: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 225: LOADK	R14 K52                ; R14 := "X-Accel-Redirect"
 226: LOADK	R15 K53                ; R15 := "/download-userdisk/"
 227: GETGLOBAL	R16 K54            ; R16 := pathEncode
 228: GETGLOBAL	R17 K7             ; R17 := string
 229: GETTABLE	R17 R17 K18         ; R17 := R17["sub"]
 230: MOVE	R18 R4                  ; R18 := R4
 231: GETGLOBAL	R19 K7             ; R19 := string
 232: GETTABLE	R19 R19 K20         ; R19 := R19["len"]
 233: MOVE	R20 R5                  ; R20 := R5
 234: CALL	R19 2 2                 ; R19 := R19(R20)
 235: ADD	R19 R19 K19              ; R19 := R19 + 1
 236: GETGLOBAL	R20 K7             ; R20 := string
 237: GETTABLE	R20 R20 K20         ; R20 := R20["len"]
 238: MOVE	R21 R4                  ; R21 := R4
 239: CALL	R20 2 0                 ; R20... := R20(R21)
 240: CALL	R17 0 0                 ; R17... := R17(R18...)
 241: CALL	R16 0 2                 ; R16 := R16(R17...)
 242: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 243: CALL	R13 3 1                 ; R13(R14, R15)
 244: JMP	131                      ; goto 376
 245: GETGLOBAL	R13 K7             ; R13 := string
 246: GETTABLE	R13 R13 K18         ; R13 := R13["sub"]
 247: MOVE	R14 R4                  ; R14 := R4
 248: LOADK	R15 K19                ; R15 := 1
 249: GETGLOBAL	R16 K7             ; R16 := string
 250: GETTABLE	R16 R16 K20         ; R16 := R16["len"]
 251: MOVE	R17 R6                  ; R17 := R6
 252: CALL	R16 2 0                 ; R16... := R16(R17)
 253: CALL	R13 0 2                 ; R13 := R13(R14...)
 254: EQ	0 R13 R6                  ; if R13 == R6 then goto 278
 255: JMP	22                       ; goto 278
 256: GETUPVAL	R13 0               ; R13 := UpValue[0]
 257: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 258: LOADK	R14 K52                ; R14 := "X-Accel-Redirect"
 259: LOADK	R15 K55                ; R15 := "/download-mnt/"
 260: GETGLOBAL	R16 K54            ; R16 := pathEncode
 261: GETGLOBAL	R17 K7             ; R17 := string
 262: GETTABLE	R17 R17 K18         ; R17 := R17["sub"]
 263: MOVE	R18 R4                  ; R18 := R4
 264: GETGLOBAL	R19 K7             ; R19 := string
 265: GETTABLE	R19 R19 K20         ; R19 := R19["len"]
 266: MOVE	R20 R6                  ; R20 := R6
 267: CALL	R19 2 2                 ; R19 := R19(R20)
 268: ADD	R19 R19 K19              ; R19 := R19 + 1
 269: GETGLOBAL	R20 K7             ; R20 := string
 270: GETTABLE	R20 R20 K20         ; R20 := R20["len"]
 271: MOVE	R21 R4                  ; R21 := R4
 272: CALL	R20 2 0                 ; R20... := R20(R21)
 273: CALL	R17 0 0                 ; R17... := R17(R18...)
 274: CALL	R16 0 2                 ; R16 := R16(R17...)
 275: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 276: CALL	R13 3 1                 ; R13(R14, R15)
 277: JMP	98                       ; goto 376
 278: GETGLOBAL	R13 K7             ; R13 := string
 279: GETTABLE	R13 R13 K18         ; R13 := R13["sub"]
 280: MOVE	R14 R4                  ; R14 := R4
 281: LOADK	R15 K19                ; R15 := 1
 282: GETGLOBAL	R16 K7             ; R16 := string
 283: GETTABLE	R16 R16 K20         ; R16 := R16["len"]
 284: MOVE	R17 R7                  ; R17 := R7
 285: CALL	R16 2 0                 ; R16... := R16(R17)
 286: CALL	R13 0 2                 ; R13 := R13(R14...)
 287: EQ	0 R13 R7                  ; if R13 == R7 then goto 311
 288: JMP	22                       ; goto 311
 289: GETUPVAL	R13 0               ; R13 := UpValue[0]
 290: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 291: LOADK	R14 K52                ; R14 := "X-Accel-Redirect"
 292: LOADK	R15 K56                ; R15 := "/download-pridisk/"
 293: GETGLOBAL	R16 K54            ; R16 := pathEncode
 294: GETGLOBAL	R17 K7             ; R17 := string
 295: GETTABLE	R17 R17 K18         ; R17 := R17["sub"]
 296: MOVE	R18 R4                  ; R18 := R4
 297: GETGLOBAL	R19 K7             ; R19 := string
 298: GETTABLE	R19 R19 K20         ; R19 := R19["len"]
 299: MOVE	R20 R7                  ; R20 := R7
 300: CALL	R19 2 2                 ; R19 := R19(R20)
 301: ADD	R19 R19 K19              ; R19 := R19 + 1
 302: GETGLOBAL	R20 K7             ; R20 := string
 303: GETTABLE	R20 R20 K20         ; R20 := R20["len"]
 304: MOVE	R21 R4                  ; R21 := R4
 305: CALL	R20 2 0                 ; R20... := R20(R21)
 306: CALL	R17 0 0                 ; R17... := R17(R18...)
 307: CALL	R16 0 2                 ; R16 := R16(R17...)
 308: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 309: CALL	R13 3 1                 ; R13(R14, R15)
 310: JMP	65                       ; goto 376
 311: GETGLOBAL	R13 K7             ; R13 := string
 312: GETTABLE	R13 R13 K18         ; R13 := R13["sub"]
 313: MOVE	R14 R4                  ; R14 := R4
 314: LOADK	R15 K19                ; R15 := 1
 315: GETGLOBAL	R16 K7             ; R16 := string
 316: GETTABLE	R16 R16 K20         ; R16 := R16["len"]
 317: MOVE	R17 R8                  ; R17 := R8
 318: CALL	R16 2 0                 ; R16... := R16(R17)
 319: CALL	R13 0 2                 ; R13 := R13(R14...)
 320: EQ	0 R13 R8                  ; if R13 == R8 then goto 344
 321: JMP	22                       ; goto 344
 322: GETUPVAL	R13 0               ; R13 := UpValue[0]
 323: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 324: LOADK	R14 K52                ; R14 := "X-Accel-Redirect"
 325: LOADK	R15 K57                ; R15 := "/download-userdisk-appdata/"
 326: GETGLOBAL	R16 K54            ; R16 := pathEncode
 327: GETGLOBAL	R17 K7             ; R17 := string
 328: GETTABLE	R17 R17 K18         ; R17 := R17["sub"]
 329: MOVE	R18 R4                  ; R18 := R4
 330: GETGLOBAL	R19 K7             ; R19 := string
 331: GETTABLE	R19 R19 K20         ; R19 := R19["len"]
 332: MOVE	R20 R8                  ; R20 := R8
 333: CALL	R19 2 2                 ; R19 := R19(R20)
 334: ADD	R19 R19 K19              ; R19 := R19 + 1
 335: GETGLOBAL	R20 K7             ; R20 := string
 336: GETTABLE	R20 R20 K20         ; R20 := R20["len"]
 337: MOVE	R21 R4                  ; R21 := R4
 338: CALL	R20 2 0                 ; R20... := R20(R21)
 339: CALL	R17 0 0                 ; R17... := R17(R18...)
 340: CALL	R16 0 2                 ; R16 := R16(R17...)
 341: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 342: CALL	R13 3 1                 ; R13(R14, R15)
 343: JMP	32                       ; goto 376
 344: GETGLOBAL	R13 K7             ; R13 := string
 345: GETTABLE	R13 R13 K18         ; R13 := R13["sub"]
 346: MOVE	R14 R4                  ; R14 := R4
 347: LOADK	R15 K19                ; R15 := 1
 348: GETGLOBAL	R16 K7             ; R16 := string
 349: GETTABLE	R16 R16 K20         ; R16 := R16["len"]
 350: MOVE	R17 R9                  ; R17 := R9
 351: CALL	R16 2 0                 ; R16... := R16(R17)
 352: CALL	R13 0 2                 ; R13 := R13(R14...)
 353: EQ	0 R13 R9                  ; if R13 == R9 then goto 376
 354: JMP	21                       ; goto 376
 355: GETUPVAL	R13 0               ; R13 := UpValue[0]
 356: GETTABLE	R13 R13 K29         ; R13 := R13["header"]
 357: LOADK	R14 K52                ; R14 := "X-Accel-Redirect"
 358: LOADK	R15 K58                ; R15 := "/download-userdisk-thumbnails/"
 359: GETGLOBAL	R16 K54            ; R16 := pathEncode
 360: GETGLOBAL	R17 K7             ; R17 := string
 361: GETTABLE	R17 R17 K18         ; R17 := R17["sub"]
 362: MOVE	R18 R4                  ; R18 := R4
 363: GETGLOBAL	R19 K7             ; R19 := string
 364: GETTABLE	R19 R19 K20         ; R19 := R19["len"]
 365: MOVE	R20 R9                  ; R20 := R9
 366: CALL	R19 2 2                 ; R19 := R19(R20)
 367: ADD	R19 R19 K19              ; R19 := R19 + 1
 368: GETGLOBAL	R20 K7             ; R20 := string
 369: GETTABLE	R20 R20 K20         ; R20 := R20["len"]
 370: MOVE	R21 R4                  ; R21 := R4
 371: CALL	R20 2 0                 ; R20... := R20(R21)
 372: CALL	R17 0 0                 ; R17... := R17(R18...)
 373: CALL	R16 0 2                 ; R16 := R16(R17...)
 374: CONCAT	R15 R15 R16           ; R15 := R15 .. R16
 375: CALL	R13 3 1                 ; R13(R14, R15)
 376: RETURN	R0 1                  ; return

-- SubChunk 10:
-- SubChunk: lineDefined=255, lastLineDefined=320, numParams=0, isVararg=0, maxStackSize=18

-- Register Operations:
   0: GETGLOBAL	R1 K0              ; R1 := require
   1: LOADK	R2 K1                  ; R2 := "xiaoqiang.XQLog"
   2: CALL	R1 2 2                  ; R1 := R1(R2)
   3: GETGLOBAL	R2 K0              ; R2 := require
   4: LOADK	R3 K2                  ; R3 := "luci.fs"
   5: CALL	R2 2 2                  ; R2 := R2(R3)
   6: LOADK	R3 K3                  ; R3 := "/userdisk/upload.tmp"
   7: GETTABLE	R4 R2 K4            ; R4 := R2["isfile"]
   8: MOVE	R5 R3                   ; R5 := R3
   9: CALL	R4 2 2                  ; R4 := R4(R5)
  10: TEST	R4 0                    ; if R4 then goto 15
  11: JMP	3                        ; goto 15
  12: GETTABLE	R4 R2 K5            ; R4 := R2["unlink"]
  13: MOVE	R5 R3                   ; R5 := R3
  14: CALL	R4 2 1                  ; R4(R5)
  15: LOADNIL	R4 R4                ; R4 := nil
  16: GETUPVAL	R5 0                ; R5 := UpValue[0]
  17: GETTABLE	R5 R5 K6            ; R5 := R5["setfilehandler"]
  18: CLOSURE	R6 0                 ; R6 := closure(0)
  19: MOVE	R0 R0                   ; R0 := R0
  20: MOVE	R0 R3                   ; R0 := R3
  21: MOVE	R0 R4                   ; R0 := R4
  22: CALL	R5 2 1                  ; R5(R6)
  23: GETUPVAL	R5 0                ; R5 := UpValue[0]
  24: GETTABLE	R5 R5 K7            ; R5 := R5["formvalue"]
  25: LOADK	R6 K8                  ; R6 := "target"
  26: CALL	R5 2 2                  ; R5 := R5(R6)
  27: GETGLOBAL	R6 K9              ; R6 := string
  28: GETTABLE	R6 R6 K10           ; R6 := R6["match"]
  29: MOVE	R7 R5                   ; R7 := R5
  30: LOADK	R8 K11                 ; R8 := "/$"
  31: CALL	R6 3 2                  ; R6 := R6(R7, R8)
  32: EQ	0 R6 K12                  ; if R6 == nil then goto 37
  33: JMP	3                        ; goto 37
  34: MOVE	R6 R5                   ; R6 := R5
  35: LOADK	R7 K13                 ; R7 := "/"
  36: CONCAT	R5 R6 R7              ; R5 := R6 .. R7
  37: GETTABLE	R6 R2 K14           ; R6 := R2["mkdir"]
  38: MOVE	R7 R5                   ; R7 := R5
  39: LOADBOOL	R8 1 0              ; R8 := true
  40: CALL	R6 3 1                  ; R6(R7, R8)
  41: MOVE	R6 R4                   ; R6 := R4
  42: GETTABLE	R7 R2 K4            ; R7 := R2["isfile"]
  43: MOVE	R8 R5                   ; R8 := R5
  44: MOVE	R9 R6                   ; R9 := R6
  45: CONCAT	R8 R8 R9              ; R8 := R8 .. R9
  46: CALL	R7 2 2                  ; R7 := R7(R8)
  47: TEST	R7 0                    ; if R7 then goto 88
  48: JMP	39                       ; goto 88
  49: MOVE	R7 R6                   ; R7 := R6
  50: SELF	R8 R7 K10               ; R9 := R7; R8 := R7["match"]
  51: LOADK	R10 K15                ; R10 := ".+()%.%w+$"
  52: CALL	R8 3 2                  ; R8 := R8(R9, R10)
  53: TEST	R8 0                    ; if R8 then goto 60
  54: JMP	5                        ; goto 60
  55: SELF	R9 R7 K16               ; R10 := R7; R9 := R7["sub"]
  56: LOADK	R11 K17                ; R11 := 1
  57: SUB	R12 R8 K17               ; R12 := R8 - 1
  58: CALL	R9 4 2                  ; R9 := R9(R10, R11, R12)
  59: MOVE	R7 R9                   ; R7 := R9
  60: SELF	R9 R6 K10               ; R10 := R6; R9 := R6["match"]
  61: LOADK	R11 K18                ; R11 := ".+%.(%w+)$"
  62: CALL	R9 3 2                  ; R9 := R9(R10, R11)
  63: LOADK	R10 K17                ; R10 := 1
  64: LOADK	R11 K19                ; R11 := 100
  65: LOADK	R12 K17                ; R12 := 1
  66: FORPREP	R10 20               ; R10 -= R12; goto 87
  67: MOVE	R14 R7                  ; R14 := R7
  68: LOADK	R15 K20                ; R15 := "("
  69: MOVE	R16 R13                 ; R16 := R13
  70: LOADK	R17 K21                ; R17 := ")"
  71: CONCAT	R14 R14 R17           ; R14 := R14 .. R17
  72: TEST	R9 0                    ; if R9 then goto 78
  73: JMP	4                        ; goto 78
  74: MOVE	R15 R14                 ; R15 := R14
  75: LOADK	R16 K22                ; R16 := "."
  76: MOVE	R17 R9                  ; R17 := R9
  77: CONCAT	R14 R15 R17           ; R14 := R15 .. R17
  78: GETTABLE	R15 R2 K4           ; R15 := R2["isfile"]
  79: MOVE	R16 R5                  ; R16 := R5
  80: MOVE	R17 R14                 ; R17 := R14
  81: CONCAT	R16 R16 R17           ; R16 := R16 .. R17
  82: CALL	R15 2 2                 ; R15 := R15(R16)
  83: TEST	R15 1                   ; if not R15 then goto 87
  84: JMP	2                        ; goto 87
  85: MOVE	R6 R14                  ; R6 := R14
  86: JMP	1                        ; goto 88
  87: FORLOOP	R10 -21              ; R10 += R12; if R10 <?= R11 then { R13 := R10; goto 67 }
  88: MOVE	R7 R5                   ; R7 := R5
  89: MOVE	R8 R6                   ; R8 := R6
  90: CONCAT	R7 R7 R8              ; R7 := R7 .. R8
  91: GETTABLE	R8 R1 K23           ; R8 := R1["log"]
  92: LOADK	R9 K24                 ; R9 := 7
  93: LOADK	R10 K25                ; R10 := "dest="
  94: MOVE	R11 R7                  ; R11 := R7
  95: CONCAT	R10 R10 R11           ; R10 := R10 .. R11
  96: CALL	R8 3 1                  ; R8(R9, R10)
  97: GETTABLE	R8 R2 K26           ; R8 := R2["rename"]
  98: MOVE	R9 R3                   ; R9 := R3
  99: MOVE	R10 R7                  ; R10 := R7
 100: CALL	R8 3 1                  ; R8(R9, R10)
 101: NEWTABLE	R8 0 0              ; R8 := {} (size = 0,0)
 102: SETTABLE	R8 K27 K28          ; R8["code"] := 0
 103: GETUPVAL	R9 0                ; R9 := UpValue[0]
 104: GETTABLE	R9 R9 K29           ; R9 := R9["write_json"]
 105: MOVE	R10 R8                  ; R10 := R8
 106: CALL	R9 2 1                  ; R9(R10)
 107: RETURN	R0 1                  ; return

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=265, lastLineDefined=284, numParams=3, isVararg=0, maxStackSize=7

-- Register Operations:
   0: GETUPVAL	R3 0                ; R3 := UpValue[0]
   1: TEST	R3 1                    ; if not R3 then goto 37
   2: JMP	34                       ; goto 37
   3: TEST	R0 0                    ; if R0 then goto 37
   4: JMP	32                       ; goto 37
   5: GETTABLE	R3 R0 K0            ; R3 := R0["name"]
   6: EQ	0 R3 K1                   ; if R3 == "file" then goto 37
   7: JMP	29                       ; goto 37
   8: GETGLOBAL	R3 K2              ; R3 := io
   9: GETTABLE	R3 R3 K3            ; R3 := R3["open"]
  10: GETUPVAL	R4 1                ; R4 := UpValue[1]
  11: LOADK	R5 K4                  ; R5 := "w"
  12: CALL	R3 3 2                  ; R3 := R3(R4, R5)
  13: SETUPVAL	R3 0                ; UpValue[0] := R3
  14: GETTABLE	R3 R0 K1            ; R3 := R0["file"]
  15: SETUPVAL	R3 2                ; UpValue[2] := R3
  16: GETGLOBAL	R3 K5              ; R3 := string
  17: GETTABLE	R3 R3 K6            ; R3 := R3["gsub"]
  18: GETUPVAL	R4 2                ; R4 := UpValue[2]
  19: LOADK	R5 K7                  ; R5 := "+"
  20: LOADK	R6 K8                  ; R6 := " "
  21: CALL	R3 4 2                  ; R3 := R3(R4, R5, R6)
  22: SETUPVAL	R3 2                ; UpValue[2] := R3
  23: GETGLOBAL	R3 K5              ; R3 := string
  24: GETTABLE	R3 R3 K6            ; R3 := R3["gsub"]
  25: GETUPVAL	R4 2                ; R4 := UpValue[2]
  26: LOADK	R5 K9                  ; R5 := "%%(%x%x)"
  27: CLOSURE	R6 0                 ; R6 := closure(0)
  28: CALL	R3 4 2                  ; R3 := R3(R4, R5, R6)
  29: SETUPVAL	R3 2                ; UpValue[2] := R3
  30: GETUPVAL	R3 2                ; R3 := UpValue[2]
  31: GETTABLE	R3 R3 K6            ; R3 := R3["gsub"]
  32: GETUPVAL	R4 2                ; R4 := UpValue[2]
  33: LOADK	R5 K10                 ; R5 := "
"
  34: LOADK	R6 K11                 ; R6 := "
"
  35: CALL	R3 4 2                  ; R3 := R3(R4, R5, R6)
  36: SETUPVAL	R3 2                ; UpValue[2] := R3
  37: TEST	R1 0                    ; if R1 then goto 43
  38: JMP	4                        ; goto 43
  39: GETUPVAL	R3 0                ; R3 := UpValue[0]
  40: SELF	R3 R3 K12               ; R4 := R3; R3 := R3["write"]
  41: MOVE	R5 R1                   ; R5 := R1
  42: CALL	R3 3 1                  ; R3(R4, R5)
  43: TEST	R2 0                    ; if R2 then goto 48
  44: JMP	3                        ; goto 48
  45: GETUPVAL	R3 0                ; R3 := UpValue[0]
  46: SELF	R3 R3 K13               ; R4 := R3; R3 := R3["close"]
  47: CALL	R3 2 1                  ; R3(R4)
  48: RETURN	R0 1                  ; return

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=272, lastLineDefined=274, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETGLOBAL	R1 K0              ; R1 := string
   1: GETTABLE	R1 R1 K1            ; R1 := R1["char"]
   2: GETGLOBAL	R2 K2              ; R2 := tonumber
   3: MOVE	R3 R0                   ; R3 := R0
   4: LOADK	R4 K3                  ; R4 := 16
   5: CALL	R2 3 0                  ; R2... := R2(R3, R4)
   6: TAILCALL	R1 0 0              ; return R1(R2...)
   7: RETURN	R1 0                  ; return R1...
   8: RETURN	R0 1                  ; return



-- SubChunk 11:
-- SubChunk: lineDefined=322, lastLineDefined=347, numParams=0, isVararg=0, maxStackSize=15

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := require
   1: LOADK	R1 K1                  ; R1 := "luci.util"
   2: CALL	R0 2 2                  ; R0 := R0(R1)
   3: GETGLOBAL	R1 K0              ; R1 := require
   4: LOADK	R2 K2                  ; R2 := "nixio.fs"
   5: CALL	R1 2 2                  ; R1 := R1(R2)
   6: GETGLOBAL	R2 K0              ; R2 := require
   7: LOADK	R3 K3                  ; R3 := "luci.http.protocol.mime"
   8: CALL	R2 2 2                  ; R2 := R2(R3)
   9: GETGLOBAL	R3 K0              ; R3 := require
  10: LOADK	R4 K4                  ; R4 := "luci.ltn12"
  11: CALL	R3 2 2                  ; R3 := R3(R4)
  12: GETGLOBAL	R4 K0              ; R4 := require
  13: LOADK	R5 K5                  ; R5 := "xiaoqiang.XQLog"
  14: CALL	R4 2 2                  ; R4 := R4(R5)
  15: GETUPVAL	R5 0                ; R5 := UpValue[0]
  16: GETTABLE	R5 R5 K6            ; R5 := R5["formvalue"]
  17: LOADK	R6 K7                  ; R6 := "filePath"
  18: CALL	R5 2 2                  ; R5 := R5(R6)
  19: GETTABLE	R6 R4 K8            ; R6 := R4["log"]
  20: LOADK	R7 K9                  ; R7 := 7
  21: LOADK	R8 K10                 ; R8 := "realPath = "
  22: MOVE	R9 R5                   ; R9 := R5
  23: CALL	R6 4 1                  ; R6(R7, R8, R9)
  24: EQ	0 R5 K11                  ; if R5 == nil then goto 34
  25: JMP	8                        ; goto 34
  26: GETUPVAL	R6 0                ; R6 := UpValue[0]
  27: GETTABLE	R6 R6 K12           ; R6 := R6["status"]
  28: LOADK	R7 K13                 ; R7 := 404
  29: GETGLOBAL	R8 K14             ; R8 := _
  30: LOADK	R9 K15                 ; R9 := "no Such file"
  31: CALL	R8 2 0                  ; R8... := R8(R9)
  32: CALL	R6 0 1                  ; R6(R7...)
  33: RETURN	R0 1                  ; return
  34: LOADK	R6 K16                 ; R6 := "{"api":10, "files":[""
  35: MOVE	R7 R5                   ; R7 := R5
  36: LOADK	R8 K17                 ; R8 := ""]}"
  37: CONCAT	R6 R6 R8              ; R6 := R6 .. R8
  38: GETUPVAL	R7 1                ; R7 := UpValue[1]
  39: GETTABLE	R7 R7 K18           ; R7 := R7["thrift_tunnel_to_datacenter"]
  40: MOVE	R8 R6                   ; R8 := R6
  41: CALL	R7 2 2                  ; R7 := R7(R8)
  42: TEST	R7 0                    ; if R7 then goto 78
  43: JMP	34                       ; goto 78
  44: GETTABLE	R8 R7 K19           ; R8 := R7["code"]
  45: EQ	0 R8 K20                  ; if R8 == 0 then goto 78
  46: JMP	31                       ; goto 78
  47: GETTABLE	R8 R7 K21           ; R8 := R7["thumbnails"]
  48: GETTABLE	R8 R8 K22           ; R8 := R8[1]
  49: GETTABLE	R9 R1 K23           ; R9 := R1["stat"]
  50: MOVE	R10 R8                  ; R10 := R8
  51: CALL	R9 2 2                  ; R9 := R9(R10)
  52: GETUPVAL	R10 0               ; R10 := UpValue[0]
  53: GETTABLE	R10 R10 K24         ; R10 := R10["header"]
  54: LOADK	R11 K25                ; R11 := "Content-Type"
  55: GETTABLE	R12 R2 K26          ; R12 := R2["to_mime"]
  56: MOVE	R13 R8                  ; R13 := R8
  57: CALL	R12 2 0                 ; R12... := R12(R13)
  58: CALL	R10 0 1                 ; R10(R11...)
  59: GETUPVAL	R10 0               ; R10 := UpValue[0]
  60: GETTABLE	R10 R10 K24         ; R10 := R10["header"]
  61: LOADK	R11 K27                ; R11 := "Content-Length"
  62: GETTABLE	R12 R9 K28          ; R12 := R9["size"]
  63: CALL	R10 3 1                 ; R10(R11, R12)
  64: GETTABLE	R10 R3 K29          ; R10 := R3["pump"]
  65: GETTABLE	R10 R10 K30         ; R10 := R10["all"]
  66: GETTABLE	R11 R3 K31          ; R11 := R3["source"]
  67: GETTABLE	R11 R11 K32         ; R11 := R11["file"]
  68: GETGLOBAL	R12 K33            ; R12 := io
  69: GETTABLE	R12 R12 K34         ; R12 := R12["open"]
  70: MOVE	R13 R8                  ; R13 := R8
  71: LOADK	R14 K35                ; R14 := "r"
  72: CALL	R12 3 0                 ; R12... := R12(R13, R14)
  73: CALL	R11 0 2                 ; R11 := R11(R12...)
  74: GETUPVAL	R12 0               ; R12 := UpValue[0]
  75: GETTABLE	R12 R12 K36         ; R12 := R12["write"]
  76: CALL	R10 3 1                 ; R10(R11, R12)
  77: JMP	7                        ; goto 85
  78: GETUPVAL	R8 0                ; R8 := UpValue[0]
  79: GETTABLE	R8 R8 K12           ; R8 := R8["status"]
  80: LOADK	R9 K13                 ; R9 := 404
  81: GETGLOBAL	R10 K14            ; R10 := _
  82: LOADK	R11 K37                ; R11 := "no Such thumb file"
  83: CALL	R10 2 0                 ; R10... := R10(R11)
  84: CALL	R8 0 1                  ; R8(R9...)
  85: RETURN	R0 1                  ; return

-- SubChunk 12:
-- SubChunk: lineDefined=349, lastLineDefined=367, numParams=0, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := require
   1: LOADK	R1 K1                  ; R1 := "nixio.fs"
   2: CALL	R0 2 2                  ; R0 := R0(R1)
   3: LOADBOOL	R1 1 0              ; R1 := true
   4: GETUPVAL	R2 0                ; R2 := UpValue[0]
   5: GETTABLE	R2 R2 K2            ; R2 := R2["formvalue"]
   6: LOADK	R3 K3                  ; R3 := "filePath"
   7: CALL	R2 2 2                  ; R2 := R2(R3)
   8: GETUPVAL	R3 1                ; R3 := UpValue[1]
   9: GETTABLE	R3 R3 K4            ; R3 := R3["isStrNil"]
  10: MOVE	R4 R2                   ; R4 := R2
  11: CALL	R3 2 2                  ; R3 := R3(R4)
  12: TEST	R3 0                    ; if R3 then goto 16
  13: JMP	2                        ; goto 16
  14: LOADBOOL	R1 0 0              ; R1 := false
  15: JMP	6                        ; goto 22
  16: GETTABLE	R3 R0 K5            ; R3 := R0["stat"]
  17: MOVE	R4 R2                   ; R4 := R2
  18: CALL	R3 2 2                  ; R3 := R3(R4)
  19: TEST	R3 1                    ; if not R3 then goto 22
  20: JMP	1                        ; goto 22
  21: LOADBOOL	R1 0 0              ; R1 := false
  22: NEWTABLE	R3 0 0              ; R3 := {} (size = 0,0)
  23: SETTABLE	R3 K6 K7            ; R3["code"] := 0
  24: SETTABLE	R3 K8 R1            ; R3["exist"] := R1
  25: GETUPVAL	R4 0                ; R4 := UpValue[0]
  26: GETTABLE	R4 R4 K9            ; R4 := R4["write_json"]
  27: MOVE	R5 R3                   ; R5 := R3
  28: CALL	R4 2 1                  ; R4(R5)
  29: RETURN	R0 1                  ; return

-- SubChunk 13:
-- SubChunk: lineDefined=369, lastLineDefined=408, numParams=0, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETGLOBAL	R0 K0              ; R0 := require
   1: LOADK	R1 K1                  ; R1 := "luci.util"
   2: CALL	R0 2 2                  ; R0 := R0(R1)
   3: GETGLOBAL	R1 K0              ; R1 := require
   4: LOADK	R2 K2                  ; R2 := "xiaoqiang.XQLog"
   5: CALL	R1 2 2                  ; R1 := R1(R2)
   6: LOADK	R2 K3                  ; R2 := 0
   7: NEWTABLE	R3 0 0              ; R3 := {} (size = 0,0)
   8: GETUPVAL	R4 0                ; R4 := UpValue[0]
   9: GETTABLE	R4 R4 K4            ; R4 := R4["formvalue"]
  10: LOADK	R5 K5                  ; R5 := "pluginID"
  11: CALL	R4 2 2                  ; R4 := R4(R5)
  12: GETUPVAL	R5 0                ; R5 := UpValue[0]
  13: GETTABLE	R5 R5 K4            ; R5 := R5["formvalue"]
  14: LOADK	R6 K6                  ; R6 := "capability"
  15: CALL	R5 2 2                  ; R5 := R5(R6)
  16: GETGLOBAL	R6 K7              ; R6 := tonumber
  17: GETUPVAL	R7 0                ; R7 := UpValue[0]
  18: GETTABLE	R7 R7 K4            ; R7 := R7["formvalue"]
  19: LOADK	R8 K8                  ; R8 := "open"
  20: CALL	R7 2 2                  ; R7 := R7(R8)
  21: TEST	R7 1                    ; if not R7 then goto 24
  22: JMP	1                        ; goto 24
  23: LOADK	R7 K3                  ; R7 := 0
  24: CALL	R6 2 2                  ; R6 := R6(R7)
  25: GETTABLE	R7 R1 K9            ; R7 := R1["check"]
  26: LOADK	R8 K3                  ; R8 := 0
  27: GETTABLE	R9 R1 K10           ; R9 := R1["KEY_FUNC_PLUGIN"]
  28: LOADK	R10 K11                ; R10 := 1
  29: CALL	R7 4 1                  ; R7(R8, R9, R10)
  30: TEST	R6 0                    ; if R6 then goto 62
  31: JMP	30                       ; goto 62
  32: EQ	0 R6 K11                  ; if R6 == 1 then goto 62
  33: JMP	28                       ; goto 62
  34: TEST	R4 0                    ; if R4 then goto 60
  35: JMP	24                       ; goto 60
  36: TEST	R5 0                    ; if R5 then goto 60
  37: JMP	22                       ; goto 60
  38: NEWTABLE	R7 0 3              ; R7 := {} (size = 0,3)
  39: SETTABLE	R7 K12 K13          ; R7["api"] := 611
  40: SETTABLE	R7 K5 R4            ; R7["pluginID"] := R4
  41: GETTABLE	R8 R0 K14           ; R8 := R0["split"]
  42: MOVE	R9 R5                   ; R9 := R5
  43: LOADK	R10 K15                ; R10 := ","
  44: CALL	R8 3 2                  ; R8 := R8(R9, R10)
  45: SETTABLE	R7 K6 R8            ; R7["capability"] := R8
  46: GETUPVAL	R8 1                ; R8 := UpValue[1]
  47: GETTABLE	R8 R8 K16           ; R8 := R8["thrift_tunnel_to_datacenter"]
  48: GETUPVAL	R9 2                ; R9 := UpValue[2]
  49: GETTABLE	R9 R9 K17           ; R9 := R9["encode"]
  50: MOVE	R10 R7                  ; R10 := R7
  51: CALL	R9 2 0                  ; R9... := R9(R10)
  52: CALL	R8 0 2                  ; R8 := R8(R9...)
  53: TEST	R8 0                    ; if R8 then goto 79
  54: JMP	24                       ; goto 79
  55: GETTABLE	R9 R8 K18           ; R9 := R8["code"]
  56: EQ	1 R9 K3                   ; if R9 == 0 then goto 79
  57: JMP	21                       ; goto 79
  58: LOADK	R2 K19                 ; R2 := 1595
  59: JMP	19                       ; goto 79
  60: LOADK	R2 K20                 ; R2 := 1537
  61: JMP	17                       ; goto 79
  62: NEWTABLE	R7 0 1              ; R7 := {} (size = 0,1)
  63: SETTABLE	R7 K12 K21          ; R7["api"] := 613
  64: GETUPVAL	R8 1                ; R8 := UpValue[1]
  65: GETTABLE	R8 R8 K16           ; R8 := R8["thrift_tunnel_to_datacenter"]
  66: GETUPVAL	R9 2                ; R9 := UpValue[2]
  67: GETTABLE	R9 R9 K17           ; R9 := R9["encode"]
  68: MOVE	R10 R7                  ; R10 := R7
  69: CALL	R9 2 0                  ; R9... := R9(R10)
  70: CALL	R8 0 2                  ; R8 := R8(R9...)
  71: TEST	R8 0                    ; if R8 then goto 78
  72: JMP	5                        ; goto 78
  73: GETTABLE	R9 R8 K18           ; R9 := R8["code"]
  74: EQ	0 R9 K3                   ; if R9 == 0 then goto 78
  75: JMP	2                        ; goto 78
  76: LOADK	R2 K3                  ; R2 := 0
  77: JMP	1                        ; goto 79
  78: LOADK	R2 K22                 ; R2 := 1601
  79: EQ	1 R2 K3                   ; if R2 == 0 then goto 86
  80: JMP	5                        ; goto 86
  81: GETUPVAL	R7 3                ; R7 := UpValue[3]
  82: GETTABLE	R7 R7 K24           ; R7 := R7["getErrorMessage"]
  83: MOVE	R8 R2                   ; R8 := R2
  84: CALL	R7 2 2                  ; R7 := R7(R8)
  85: SETTABLE	R3 K23 R7           ; R3["msg"] := R7
  86: SETTABLE	R3 K18 R2           ; R3["code"] := R2
  87: GETUPVAL	R7 0                ; R7 := UpValue[0]
  88: GETTABLE	R7 R7 K25           ; R7 := R7["write_json"]
  89: MOVE	R8 R3                   ; R8 := R3
  90: CALL	R7 2 1                  ; R7(R8)
  91: RETURN	R0 1                  ; return

-- SubChunk 14:
-- SubChunk: lineDefined=410, lastLineDefined=443, numParams=0, isVararg=0, maxStackSize=17

-- Register Operations:
   0: LOADK	R0 K0                  ; R0 := 0
   1: NEWTABLE	R1 0 0              ; R1 := {} (size = 0,0)
   2: GETUPVAL	R2 0                ; R2 := UpValue[0]
   3: GETTABLE	R2 R2 K1            ; R2 := R2["thrift_tunnel_to_datacenter"]
   4: LOADK	R3 K2                  ; R3 := "{"api":612}"
   5: CALL	R2 2 2                  ; R2 := R2(R3)
   6: GETUPVAL	R3 0                ; R3 := UpValue[0]
   7: GETTABLE	R3 R3 K1            ; R3 := R3["thrift_tunnel_to_datacenter"]
   8: LOADK	R4 K3                  ; R4 := "{"api":621}"
   9: CALL	R3 2 2                  ; R3 := R3(R4)
  10: TEST	R2 0                    ; if R2 then goto 62
  11: JMP	50                       ; goto 62
  12: GETTABLE	R4 R2 K4            ; R4 := R2["code"]
  13: EQ	0 R4 K0                   ; if R4 == 0 then goto 62
  14: JMP	47                       ; goto 62
  15: TEST	R3 0                    ; if R3 then goto 62
  16: JMP	45                       ; goto 62
  17: GETTABLE	R4 R2 K4            ; R4 := R2["code"]
  18: EQ	0 R4 K0                   ; if R4 == 0 then goto 62
  19: JMP	42                       ; goto 62
  20: NEWTABLE	R4 0 0              ; R4 := {} (size = 0,0)
  21: GETTABLE	R5 R2 K6            ; R5 := R2["status"]
  22: EQ	0 R5 K7                   ; if R5 == 1 then goto 27
  23: JMP	3                        ; goto 27
  24: LOADK	R5 K7                  ; R5 := 1
  25: TEST	R5 1                    ; if not R5 then goto 28
  26: JMP	1                        ; goto 28
  27: LOADK	R5 K0                  ; R5 := 0
  28: SETTABLE	R1 K5 R5            ; R1["enable"] := R5
  29: NEWTABLE	R5 0 0              ; R5 := {} (size = 0,0)
  30: GETTABLE	R6 R1 K5            ; R6 := R1["enable"]
  31: EQ	0 R6 K7                   ; if R6 == 1 then goto 37
  32: JMP	4                        ; goto 37
  33: GETTABLE	R6 R2 K8            ; R6 := R2["plugin_ssh_status"]
  34: GETTABLE	R7 R6 K9            ; R7 := R6["pluginID"]
  35: SETTABLE	R1 K9 R7            ; R1["pluginID"] := R7
  36: GETTABLE	R5 R6 K10           ; R5 := R6["capability"]
  37: GETGLOBAL	R6 K11             ; R6 := ipairs
  38: GETTABLE	R7 R3 K12           ; R7 := R3["list"]
  39: CALL	R6 2 4                  ; R6, R7, R8 := R6(R7)
  40: JMP	17                       ; goto 58
  41: SETTABLE	R10 K5 K0           ; R10["enable"] := 0
  42: GETGLOBAL	R11 K11            ; R11 := ipairs
  43: MOVE	R12 R5                  ; R12 := R5
  44: CALL	R11 2 4                 ; R11, R12, R13 := R11(R12)
  45: JMP	5                        ; goto 51
  46: GETTABLE	R16 R10 K13         ; R16 := R10["key"]
  47: EQ	0 R16 R15                 ; if R16 == R15 then goto 51
  48: JMP	2                        ; goto 51
  49: SETTABLE	R10 K5 K7           ; R10["enable"] := 1
  50: JMP	2                        ; goto 53
  51: TFORLOOP	R11 0 2             ; R14, ..., R15 := R11(R12, R13); if R14 ~= nil then { R13 := R14; goto 46 }
  52: JMP	-7                       ; goto 46
  53: GETGLOBAL	R11 K14            ; R11 := table
  54: GETTABLE	R11 R11 K15         ; R11 := R11["insert"]
  55: MOVE	R12 R4                  ; R12 := R4
  56: MOVE	R13 R10                 ; R13 := R10
  57: CALL	R11 3 1                 ; R11(R12, R13)
  58: TFORLOOP	R6 0 2              ; R9, ..., R10 := R6(R7, R8); if R9 ~= nil then { R8 := R9; goto 41 }
  59: JMP	-19                      ; goto 41
  60: SETTABLE	R1 K10 R4           ; R1["capability"] := R4
  61: JMP	1                        ; goto 63
  62: LOADK	R0 K16                 ; R0 := 1600
  63: EQ	1 R0 K0                   ; if R0 == 0 then goto 70
  64: JMP	5                        ; goto 70
  65: GETUPVAL	R4 1                ; R4 := UpValue[1]
  66: GETTABLE	R4 R4 K18           ; R4 := R4["getErrorMessage"]
  67: MOVE	R5 R0                   ; R5 := R0
  68: CALL	R4 2 2                  ; R4 := R4(R5)
  69: SETTABLE	R1 K17 R4           ; R1["msg"] := R4
  70: SETTABLE	R1 K4 R0            ; R1["code"] := R0
  71: GETUPVAL	R4 2                ; R4 := UpValue[2]
  72: GETTABLE	R4 R4 K19           ; R4 := R4["write_json"]
  73: MOVE	R5 R1                   ; R5 := R1
  74: CALL	R4 2 1                  ; R4(R5)
  75: RETURN	R0 1                  ; return

