-- Lua Bytecode Instructions
-- Generated by Relua

-- Chunk: lineDefined=0, lastLineDefined=0, numParams=0, isVararg=2, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := module
   1: LOADK	R1 K1             ; R1 := "luci.controller.api.xqdatacenter"
   2: GETGLOBAL	R2 K2         ; R2 := package
   3: GETTABLE	R2 R2 RK259    ; R2 := R2["seeall"]
   4: CALL	R0 3 1             ; R0 := R0(...) -- b=3, c=1
   5: CLOSURE	R0 0            ; R0 := closure(0)
   6: SETGLOBAL	R0 K4         ; index := R0
   7: GETGLOBAL	R0 K5         ; R0 := require
   8: LOADK	R1 K6             ; R1 := "luci.http"
   9: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
  10: GETGLOBAL	R1 K5         ; R1 := require
  11: LOADK	R2 K7             ; R2 := "json"
  12: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  13: GETGLOBAL	R2 K5         ; R2 := require
  14: LOADK	R3 K8             ; R3 := "xiaoqiang.common.XQConfigs"
  15: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  16: GETGLOBAL	R3 K5         ; R3 := require
  17: LOADK	R4 K9             ; R4 := "xiaoqiang.common.XQFunction"
  18: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  19: GETGLOBAL	R4 K5         ; R4 := require
  20: LOADK	R5 K10            ; R5 := "xiaoqiang.util.XQErrorUtil"
  21: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  22: CLOSURE	R5 1            ; R5 := closure(1)
  23: MOVE	R0 R0              ; R0 := R0
  24: SETGLOBAL	R5 K11        ; fsysProbe := R5
  25: CLOSURE	R5 2            ; R5 := closure(2)
  26: MOVE	R0 R0              ; R0 := R0
  27: SETGLOBAL	R5 K12        ; fsysResume := R5
  28: CLOSURE	R5 3            ; R5 := closure(3)
  29: MOVE	R0 R3              ; R0 := R3
  30: SETGLOBAL	R5 K13        ; chk_param := R5
  31: CLOSURE	R5 4            ; R5 := closure(4)
  32: MOVE	R0 R0              ; R0 := R0
  33: MOVE	R0 R3              ; R0 := R3
  34: MOVE	R0 R2              ; R0 := R2
  35: SETGLOBAL	R5 K14        ; tunnelRequest := R5
  36: CLOSURE	R5 5            ; R5 := closure(5)
  37: MOVE	R0 R3              ; R0 := R3
  38: MOVE	R0 R0              ; R0 := R0
  39: SETGLOBAL	R5 K15        ; identifyDevice := R5
  40: CLOSURE	R5 6            ; R5 := closure(6)
  41: MOVE	R0 R3              ; R0 := R3
  42: MOVE	R0 R0              ; R0 := R0
  43: SETGLOBAL	R5 K16        ; getDeviceId := R5
  44: CLOSURE	R5 7            ; R5 := closure(7)
  45: SETGLOBAL	R5 K17        ; pathEncode := R5
  46: CLOSURE	R5 8            ; R5 := closure(8)
  47: MOVE	R0 R0              ; R0 := R0
  48: MOVE	R0 R3              ; R0 := R3
  49: SETGLOBAL	R5 K18        ; download := R5
  50: CLOSURE	R5 9            ; R5 := closure(9)
  51: MOVE	R0 R0              ; R0 := R0
  52: SETGLOBAL	R5 K19        ; upload := R5
  53: CLOSURE	R5 10           ; R5 := closure(10)
  54: MOVE	R0 R0              ; R0 := R0
  55: MOVE	R0 R3              ; R0 := R3
  56: SETGLOBAL	R5 K20        ; getThumb := R5
  57: CLOSURE	R5 11           ; R5 := closure(11)
  58: MOVE	R0 R0              ; R0 := R0
  59: MOVE	R0 R3              ; R0 := R3
  60: SETGLOBAL	R5 K21        ; checkFileExist := R5
  61: CLOSURE	R5 12           ; R5 := closure(12)
  62: MOVE	R0 R0              ; R0 := R0
  63: MOVE	R0 R3              ; R0 := R3
  64: MOVE	R0 R1              ; R0 := R1
  65: MOVE	R0 R4              ; R0 := R4
  66: SETGLOBAL	R5 K22        ; pluginSSH := R5
  67: CLOSURE	R5 13           ; R5 := closure(13)
  68: MOVE	R0 R3              ; R0 := R3
  69: MOVE	R0 R4              ; R0 := R4
  70: MOVE	R0 R0              ; R0 := R0
  71: SETGLOBAL	R5 K23        ; pluginSSHStatus := R5
  72: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=3, lastLineDefined=26, numParams=0, isVararg=0, maxStackSize=8

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := node
   1: LOADK	R1 K1             ; R1 := "api"
   2: LOADK	R2 K2             ; R2 := "xqdatacenter"
   3: CALL	R0 3 2             ; R0 := R0(...) -- b=3, c=2
   4: GETGLOBAL	R1 K3         ; R1 := require
   5: LOADK	R2 K4             ; R2 := "xiaoqiang.XQFeatures"
   6: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   7: GETTABLE	R1 R1 RK261    ; R1 := R1["FEATURES"]
   8: GETGLOBAL	R2 K7         ; R2 := firstchild
   9: CALL	R2 1 2             ; R2 := R2(...) -- b=1, c=2
  10: SETTABLE	R0 RK262 R2    ; R0["target"] := R2
  11: SETTABLE	R0 RK264 R265  ; R0["title"] := ""
  12: SETTABLE	R0 RK266 R267  ; R0["order"] := 300
  13: SETTABLE	R0 RK268 R269  ; R0["sysauth"] := "admin"
  14: SETTABLE	R0 RK270 R271  ; R0["sysauth_authenticator"] := "jsonauth"
  15: SETTABLE	R0 RK272 R273  ; R0["index"] := true
  16: GETGLOBAL	R2 K18        ; R2 := entry
  17: NEWTABLE	R3             ; R3 := {}
  18: LOADK	R4 K1             ; R4 := "api"
  19: LOADK	R5 K2             ; R5 := "xqdatacenter"
  20: SETLIST	R3 2 1          ; setlist R3, R2 -- b=2, c=1
  21: GETGLOBAL	R4 K7         ; R4 := firstchild
  22: CALL	R4 1 2             ; R4 := R4(...) -- b=1, c=2
  23: GETGLOBAL	R5 K19        ; R5 := _
  24: LOADK	R6 K9             ; R6 := ""
  25: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  26: LOADK	R6 K11            ; R6 := 300
  27: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
  28: GETTABLE	R2 R1 RK276    ; R2 := R1["apps"]
  29: GETTABLE	R2 R2 RK258    ; R2 := R2["xqdatacenter"]
  30: TEST	R2 0 0             ; if  R2 then goto 0
  31: JMP	160                 ; goto 160
  32: GETTABLE	R2 R1 RK276    ; R2 := R1["apps"]
  33: GETTABLE	R2 R2 RK258    ; R2 := R2["xqdatacenter"]
  34: EQ	R2 R277 0            ; if R2 == "1" then goto 0
  35: JMP	156                 ; goto 156
  36: GETGLOBAL	R2 K18        ; R2 := entry
  37: NEWTABLE	R3             ; R3 := {}
  38: LOADK	R4 K1             ; R4 := "api"
  39: LOADK	R5 K2             ; R5 := "xqdatacenter"
  40: LOADK	R6 K22            ; R6 := "request"
  41: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
  42: GETGLOBAL	R4 K23        ; R4 := call
  43: LOADK	R5 K24            ; R5 := "tunnelRequest"
  44: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  45: GETGLOBAL	R5 K19        ; R5 := _
  46: LOADK	R6 K9             ; R6 := ""
  47: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  48: LOADK	R6 K25            ; R6 := 301
  49: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
  50: GETGLOBAL	R2 K18        ; R2 := entry
  51: NEWTABLE	R3             ; R3 := {}
  52: LOADK	R4 K1             ; R4 := "api"
  53: LOADK	R5 K2             ; R5 := "xqdatacenter"
  54: LOADK	R6 K26            ; R6 := "identify_device"
  55: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
  56: GETGLOBAL	R4 K23        ; R4 := call
  57: LOADK	R5 K27            ; R5 := "identifyDevice"
  58: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  59: GETGLOBAL	R5 K19        ; R5 := _
  60: LOADK	R6 K9             ; R6 := ""
  61: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  62: LOADK	R6 K28            ; R6 := 302
  63: LOADK	R7 K29            ; R7 := 8
  64: CALL	R2 6 1             ; R2 := R2(...) -- b=6, c=1
  65: GETGLOBAL	R2 K18        ; R2 := entry
  66: NEWTABLE	R3             ; R3 := {}
  67: LOADK	R4 K1             ; R4 := "api"
  68: LOADK	R5 K2             ; R5 := "xqdatacenter"
  69: LOADK	R6 K30            ; R6 := "download"
  70: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
  71: GETGLOBAL	R4 K23        ; R4 := call
  72: LOADK	R5 K30            ; R5 := "download"
  73: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  74: GETGLOBAL	R5 K19        ; R5 := _
  75: LOADK	R6 K9             ; R6 := ""
  76: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  77: LOADK	R6 K31            ; R6 := 303
  78: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
  79: GETGLOBAL	R2 K18        ; R2 := entry
  80: NEWTABLE	R3             ; R3 := {}
  81: LOADK	R4 K1             ; R4 := "api"
  82: LOADK	R5 K2             ; R5 := "xqdatacenter"
  83: LOADK	R6 K32            ; R6 := "upload"
  84: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
  85: GETGLOBAL	R4 K23        ; R4 := call
  86: LOADK	R5 K32            ; R5 := "upload"
  87: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  88: GETGLOBAL	R5 K19        ; R5 := _
  89: LOADK	R6 K9             ; R6 := ""
  90: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  91: LOADK	R6 K33            ; R6 := 304
  92: LOADK	R7 K34            ; R7 := 16
  93: CALL	R2 6 1             ; R2 := R2(...) -- b=6, c=1
  94: GETGLOBAL	R2 K18        ; R2 := entry
  95: NEWTABLE	R3             ; R3 := {}
  96: LOADK	R4 K1             ; R4 := "api"
  97: LOADK	R5 K2             ; R5 := "xqdatacenter"
  98: LOADK	R6 K35            ; R6 := "thumb"
  99: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 100: GETGLOBAL	R4 K23        ; R4 := call
 101: LOADK	R5 K36            ; R5 := "getThumb"
 102: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 103: GETGLOBAL	R5 K19        ; R5 := _
 104: LOADK	R6 K9             ; R6 := ""
 105: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 106: LOADK	R6 K37            ; R6 := 305
 107: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 108: GETGLOBAL	R2 K18        ; R2 := entry
 109: NEWTABLE	R3             ; R3 := {}
 110: LOADK	R4 K1             ; R4 := "api"
 111: LOADK	R5 K2             ; R5 := "xqdatacenter"
 112: LOADK	R6 K38            ; R6 := "device_id"
 113: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 114: GETGLOBAL	R4 K23        ; R4 := call
 115: LOADK	R5 K39            ; R5 := "getDeviceId"
 116: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 117: GETGLOBAL	R5 K19        ; R5 := _
 118: LOADK	R6 K9             ; R6 := ""
 119: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 120: LOADK	R6 K40            ; R6 := 306
 121: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 122: GETGLOBAL	R2 K18        ; R2 := entry
 123: NEWTABLE	R3             ; R3 := {}
 124: LOADK	R4 K1             ; R4 := "api"
 125: LOADK	R5 K2             ; R5 := "xqdatacenter"
 126: LOADK	R6 K41            ; R6 := "check_file_exist"
 127: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 128: GETGLOBAL	R4 K23        ; R4 := call
 129: LOADK	R5 K42            ; R5 := "checkFileExist"
 130: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 131: GETGLOBAL	R5 K19        ; R5 := _
 132: LOADK	R6 K9             ; R6 := ""
 133: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 134: LOADK	R6 K43            ; R6 := 307
 135: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 136: GETGLOBAL	R2 K18        ; R2 := entry
 137: NEWTABLE	R3             ; R3 := {}
 138: LOADK	R4 K1             ; R4 := "api"
 139: LOADK	R5 K2             ; R5 := "xqdatacenter"
 140: LOADK	R6 K44            ; R6 := "plugin_ssh"
 141: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 142: GETGLOBAL	R4 K23        ; R4 := call
 143: LOADK	R5 K45            ; R5 := "pluginSSH"
 144: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 145: GETGLOBAL	R5 K19        ; R5 := _
 146: LOADK	R6 K9             ; R6 := ""
 147: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 148: LOADK	R6 K46            ; R6 := 308
 149: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 150: GETGLOBAL	R2 K18        ; R2 := entry
 151: NEWTABLE	R3             ; R3 := {}
 152: LOADK	R4 K1             ; R4 := "api"
 153: LOADK	R5 K2             ; R5 := "xqdatacenter"
 154: LOADK	R6 K47            ; R6 := "plugin_ssh_status"
 155: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 156: GETGLOBAL	R4 K23        ; R4 := call
 157: LOADK	R5 K48            ; R5 := "pluginSSHStatus"
 158: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 159: GETGLOBAL	R5 K19        ; R5 := _
 160: LOADK	R6 K9             ; R6 := ""
 161: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 162: LOADK	R6 K49            ; R6 := 309
 163: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 164: GETGLOBAL	R2 K18        ; R2 := entry
 165: NEWTABLE	R3             ; R3 := {}
 166: LOADK	R4 K1             ; R4 := "api"
 167: LOADK	R5 K2             ; R5 := "xqdatacenter"
 168: LOADK	R6 K50            ; R6 := "fsys_probe"
 169: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 170: GETGLOBAL	R4 K23        ; R4 := call
 171: LOADK	R5 K51            ; R5 := "fsysProbe"
 172: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 173: GETGLOBAL	R5 K19        ; R5 := _
 174: LOADK	R6 K9             ; R6 := ""
 175: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 176: LOADK	R6 K25            ; R6 := 301
 177: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 178: GETGLOBAL	R2 K18        ; R2 := entry
 179: NEWTABLE	R3             ; R3 := {}
 180: LOADK	R4 K1             ; R4 := "api"
 181: LOADK	R5 K2             ; R5 := "xqdatacenter"
 182: LOADK	R6 K52            ; R6 := "fsys_resume"
 183: SETLIST	R3 3 1          ; setlist R3, R3 -- b=3, c=1
 184: GETGLOBAL	R4 K23        ; R4 := call
 185: LOADK	R5 K53            ; R5 := "fsysResume"
 186: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
 187: GETGLOBAL	R5 K19        ; R5 := _
 188: LOADK	R6 K9             ; R6 := ""
 189: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
 190: LOADK	R6 K25            ; R6 := 301
 191: CALL	R2 5 1             ; R2 := R2(...) -- b=5, c=1
 192: RETURN	R0 1             ; return R0

-- SubChunk 2:
-- SubChunk: lineDefined=34, lastLineDefined=50, numParams=0, isVararg=0, maxStackSize=5

-- Register Operations:
   0: NEWTABLE	R0             ; R0 := {}
   1: SETTABLE	R0 RK256 R257  ; R0["code"] := 0
   2: SETTABLE	R0 RK258 R259  ; R0["msg"] := ""
   3: GETGLOBAL	R1 K4         ; R1 := require
   4: LOADK	R2 K5             ; R2 := "xiaoqiang.module.XQDisk"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K6         ; R2 := tonumber
   7: GETUPVAL	R3 0           ; R3 := UpValue[0]
   8: GETTABLE	R3 R3 RK263    ; R3 := R3["formvalue"]
   9: LOADK	R4 K8             ; R4 := "type"
  10: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  11: TEST	R3 1 0             ; if not R3 then goto 0
  12: JMP	1                   ; goto 1
  13: LOADK	R3 K9             ; R3 := 3
  14: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  15: EQ	R2 R266 0            ; if R2 == 1 then goto 0
  16: JMP	3                   ; goto 3
  17: GETTABLE	R3 R1 RK267    ; R3 := R1["disk_check"]
  18: CALL	R3 1 1             ; R3 := R3(...) -- b=1, c=1
  19: JMP	8                   ; goto 8
  20: EQ	R2 R268 0            ; if R2 == 2 then goto 0
  21: JMP	4                   ; goto 4
  22: GETTABLE	R3 R1 RK270    ; R3 := R1["get_diskstatus"]
  23: CALL	R3 1 2             ; R3 := R3(...) -- b=1, c=2
  24: SETTABLE	R0 RK269 R3    ; R0["status"] := R3
  25: JMP	2                   ; goto 2
  26: SETTABLE	R0 RK256 R271  ; R0["code"] := 6
  27: SETTABLE	R0 RK258 R272  ; R0["msg"] := "ParameterError"
  28: GETUPVAL	R3 0           ; R3 := UpValue[0]
  29: GETTABLE	R3 R3 RK273    ; R3 := R3["write_json"]
  30: MOVE	R4 R0              ; R4 := R0
  31: CALL	R3 2 1             ; R3 := R3(...) -- b=2, c=1
  32: RETURN	R0 1             ; return R0

-- SubChunk 3:
-- SubChunk: lineDefined=52, lastLineDefined=67, numParams=0, isVararg=0, maxStackSize=5

-- Register Operations:
   0: NEWTABLE	R0             ; R0 := {}
   1: SETTABLE	R0 RK256 R257  ; R0["code"] := 0
   2: SETTABLE	R0 RK258 R259  ; R0["msg"] := ""
   3: GETGLOBAL	R1 K4         ; R1 := require
   4: LOADK	R2 K5             ; R2 := "xiaoqiang.module.XQDisk"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K6         ; R2 := tonumber
   7: GETUPVAL	R3 0           ; R3 := UpValue[0]
   8: GETTABLE	R3 R3 RK263    ; R3 := R3["formvalue"]
   9: LOADK	R4 K8             ; R4 := "type"
  10: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  11: TEST	R3 1 0             ; if not R3 then goto 0
  12: JMP	1                   ; goto 1
  13: LOADK	R3 K9             ; R3 := 3
  14: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  15: EQ	R2 R266 0            ; if R2 == 1 then goto 0
  16: JMP	3                   ; goto 3
  17: GETTABLE	R3 R1 RK267    ; R3 := R1["disk_repair"]
  18: CALL	R3 1 1             ; R3 := R3(...) -- b=1, c=1
  19: JMP	8                   ; goto 8
  20: EQ	R2 R268 0            ; if R2 == 2 then goto 0
  21: JMP	4                   ; goto 4
  22: GETTABLE	R3 R1 RK270    ; R3 := R1["get_repairstatus"]
  23: CALL	R3 1 2             ; R3 := R3(...) -- b=1, c=2
  24: SETTABLE	R0 RK269 R3    ; R0["status"] := R3
  25: JMP	2                   ; goto 2
  26: SETTABLE	R0 RK256 R271  ; R0["code"] := 6
  27: SETTABLE	R0 RK258 R272  ; R0["msg"] := "ParameterError"
  28: GETUPVAL	R3 0           ; R3 := UpValue[0]
  29: GETTABLE	R3 R3 RK273    ; R3 := R3["write_json"]
  30: MOVE	R4 R0              ; R4 := R0
  31: CALL	R3 2 1             ; R3 := R3(...) -- b=2, c=1
  32: RETURN	R0 1             ; return R0

-- SubChunk 4:
-- SubChunk: lineDefined=69, lastLineDefined=109, numParams=1, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := require
   1: LOADK	R2 K1             ; R2 := "xiaoqiang.XQLog"
   2: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   3: GETGLOBAL	R2 K0         ; R2 := require
   4: LOADK	R3 K2             ; R3 := "json"
   5: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   6: GETTABLE	R3 R2 RK259    ; R3 := R2["decode"]
   7: MOVE	R4 R0              ; R4 := R0
   8: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
   9: GETGLOBAL	R4 K0         ; R4 := require
  10: LOADK	R5 K4             ; R5 := "xiaoqiang.util.XQSecureUtil"
  11: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  12: GETGLOBAL	R5 K5         ; R5 := type
  13: MOVE	R6 R3              ; R6 := R3
  14: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  15: EQ	R5 R262 0            ; if R5 == "table" then goto 0
  16: JMP	6                   ; goto 6
  17: GETTABLE	R5 R1 RK263    ; R5 := R1["log"]
  18: LOADK	R6 K8             ; R6 := 6
  19: LOADK	R7 K9             ; R7 := "chk_param: wrong type"
  20: CALL	R5 3 1             ; R5 := R5(...) -- b=3, c=1
  21: LOADBOOL	R5 0 0         ; R5 := false
  22: RETURN	R5 2             ; return R5, R6
  23: GETTABLE	R5 R3 RK266    ; R5 := R3["api"]
  24: EQ	R5 R267 0            ; if R5 == 63 then goto 0
  25: JMP	27                  ; goto 27
  26: GETTABLE	R5 R3 RK268    ; R5 := R3["path"]
  27: GETUPVAL	R6 0           ; R6 := UpValue[0]
  28: GETTABLE	R6 R6 RK269    ; R6 := R6["isStrNil"]
  29: MOVE	R7 R5              ; R7 := R5
  30: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  31: TEST	R6 0 0             ; if  R6 then goto 0
  32: JMP	6                   ; goto 6
  33: GETTABLE	R6 R1 RK263    ; R6 := R1["log"]
  34: LOADK	R7 K8             ; R7 := 6
  35: LOADK	R8 K14            ; R8 := "chk_param:  path is null"
  36: CALL	R6 3 1             ; R6 := R6(...) -- b=3, c=1
  37: LOADBOOL	R6 0 0         ; R6 := false
  38: RETURN	R6 2             ; return R6, R7
  39: GETTABLE	R6 R4 RK271    ; R6 := R4["hackCharsCheck"]
  40: MOVE	R7 R5              ; R7 := R5
  41: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  42: EQ	R6 R272 0            ; if R6 == "" then goto 0
  43: JMP	6                   ; goto 6
  44: GETTABLE	R7 R1 RK263    ; R7 := R1["log"]
  45: LOADK	R8 K8             ; R8 := 6
  46: LOADK	R9 K17            ; R9 := "chk_param: path has invalid char"
  47: CALL	R7 3 1             ; R7 := R7(...) -- b=3, c=1
  48: LOADBOOL	R7 0 0         ; R7 := false
  49: RETURN	R7 2             ; return R7, R8
  50: LOADBOOL	R7 1 0         ; R7 := true
  51: RETURN	R7 2             ; return R7, R8
  52: JMP	53                  ; goto 53
  53: GETTABLE	R5 R3 RK266    ; R5 := R3["api"]
  54: EQ	R5 R274 0            ; if R5 == 7 then goto 0
  55: JMP	50                  ; goto 50
  56: GETTABLE	R5 R3 RK275    ; R5 := R3["vendor"]
  57: GETTABLE	R6 R3 RK276    ; R6 := R3["dev"]
  58: GETTABLE	R7 R3 RK261    ; R7 := R3["type"]
  59: GETUPVAL	R8 0           ; R8 := UpValue[0]
  60: GETTABLE	R8 R8 RK269    ; R8 := R8["isStrNil"]
  61: MOVE	R9 R5              ; R9 := R5
  62: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  63: TEST	R8 1 0             ; if not R8 then goto 0
  64: JMP	12                  ; goto 12
  65: GETUPVAL	R8 0           ; R8 := UpValue[0]
  66: GETTABLE	R8 R8 RK269    ; R8 := R8["isStrNil"]
  67: MOVE	R9 R6              ; R9 := R6
  68: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  69: TEST	R8 1 0             ; if not R8 then goto 0
  70: JMP	6                   ; goto 6
  71: GETUPVAL	R8 0           ; R8 := UpValue[0]
  72: GETTABLE	R8 R8 RK269    ; R8 := R8["isStrNil"]
  73: MOVE	R9 R7              ; R9 := R7
  74: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  75: TEST	R8 0 0             ; if  R8 then goto 0
  76: JMP	6                   ; goto 6
  77: GETTABLE	R8 R1 RK263    ; R8 := R1["log"]
  78: LOADK	R9 K8             ; R9 := 6
  79: LOADK	R10 K21           ; R10 := "chk_param: param is null"
  80: CALL	R8 3 1             ; R8 := R8(...) -- b=3, c=1
  81: LOADBOOL	R8 0 0         ; R8 := false
  82: RETURN	R8 2             ; return R8, R9
  83: GETTABLE	R8 R4 RK271    ; R8 := R4["hackCharsCheck"]
  84: MOVE	R9 R5              ; R9 := R5
  85: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  86: EQ	R8 R272 0            ; if R8 == "" then goto 0
  87: JMP	10                  ; goto 10
  88: GETTABLE	R8 R4 RK271    ; R8 := R4["hackCharsCheck"]
  89: MOVE	R9 R6              ; R9 := R6
  90: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  91: EQ	R8 R272 0            ; if R8 == "" then goto 0
  92: JMP	5                   ; goto 5
  93: GETTABLE	R8 R4 RK271    ; R8 := R4["hackCharsCheck"]
  94: MOVE	R9 R7              ; R9 := R7
  95: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  96: EQ	R8 R272 0            ; if R8 == "" then goto 0
  97: JMP	6                   ; goto 6
  98: GETTABLE	R8 R1 RK263    ; R8 := R1["log"]
  99: LOADK	R9 K8             ; R9 := 6
 100: LOADK	R10 K22           ; R10 := "chk_param: params has invalid char"
 101: CALL	R8 3 1             ; R8 := R8(...) -- b=3, c=1
 102: LOADBOOL	R8 0 0         ; R8 := false
 103: RETURN	R8 2             ; return R8, R9
 104: LOADBOOL	R8 1 0         ; R8 := true
 105: RETURN	R8 2             ; return R8, R9
 106: LOADBOOL	R5 1 0         ; R5 := true
 107: RETURN	R5 2             ; return R5, R6
 108: RETURN	R0 1             ; return R0

-- SubChunk 5:
-- SubChunk: lineDefined=111, lastLineDefined=128, numParams=0, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "luci.util"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "xiaoqiang.util.XQCryptoUtil"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 RK259    ; R2 := R2["formvalue_unsafe"]
   8: LOADK	R3 K4             ; R3 := "payload"
   9: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  10: NEWTABLE	R3             ; R3 := {}
  11: GETUPVAL	R4 1           ; R4 := UpValue[1]
  12: GETTABLE	R4 R4 RK261    ; R4 := R4["isStrNil"]
  13: MOVE	R5 R2              ; R5 := R2
  14: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  15: TEST	R4 1 0             ; if not R4 then goto 0
  16: JMP	5                   ; goto 5
  17: GETGLOBAL	R4 K6         ; R4 := chk_param
  18: MOVE	R5 R2              ; R5 := R2
  19: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  20: TEST	R4 1 0             ; if not R4 then goto 0
  21: JMP	7                   ; goto 7
  22: SETTABLE	R3 RK263 R264  ; R3["code"] := 6
  23: SETTABLE	R3 RK265 R266  ; R3["msg"] := "ParameterError"
  24: GETUPVAL	R4 0           ; R4 := UpValue[0]
  25: GETTABLE	R4 R4 RK267    ; R4 := R4["write_json"]
  26: MOVE	R5 R3              ; R5 := R3
  27: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  28: RETURN	R0 1             ; return R0
  29: GETTABLE	R4 R1 RK268    ; R4 := R1["binaryBase64Enc"]
  30: MOVE	R5 R2              ; R5 := R2
  31: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  32: GETUPVAL	R5 2           ; R5 := UpValue[2]
  33: GETTABLE	R5 R5 RK269    ; R5 := R5["THRIFT_TUNNEL_TO_DATACENTER"]
  34: MOD	R5 R5 R4            ; R5 := R5 % R4
  35: GETTABLE	R6 R0 RK270    ; R6 := R0["exec"]
  36: MOVE	R7 R5              ; R7 := R5
  37: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  38: MOVE	R3 R6              ; R3 := R6
  39: GETUPVAL	R6 0           ; R6 := UpValue[0]
  40: GETTABLE	R6 R6 RK271    ; R6 := R6["write"]
  41: MOVE	R7 R3              ; R7 := R3
  42: LOADNIL	R8 R8           ; R8 := nil
  43: LOADBOOL	R9 0 0         ; R9 := false
  44: LOADBOOL	R10 1 0        ; R10 := true
  45: CALL	R6 5 1             ; R6 := R6(...) -- b=5, c=1
  46: RETURN	R0 1             ; return R0

-- SubChunk 6:
-- SubChunk: lineDefined=130, lastLineDefined=135, numParams=0, isVararg=0, maxStackSize=3

-- Register Operations:
   0: NEWTABLE	R0             ; R0 := {}
   1: SETTABLE	R0 RK256 R257  ; R0["code"] := 0
   2: GETUPVAL	R1 0           ; R1 := UpValue[0]
   3: GETTABLE	R1 R1 RK259    ; R1 := R1["mattool_identify_device"]
   4: CALL	R1 1 2             ; R1 := R1(...) -- b=1, c=2
   5: SETTABLE	R0 RK258 R1    ; R0["info"] := R1
   6: GETUPVAL	R1 1           ; R1 := UpValue[1]
   7: GETTABLE	R1 R1 RK260    ; R1 := R1["write_json"]
   8: MOVE	R2 R0              ; R2 := R0
   9: CALL	R1 2 1             ; R1 := R1(...) -- b=2, c=1
  10: RETURN	R0 1             ; return R0

-- SubChunk 7:
-- SubChunk: lineDefined=137, lastLineDefined=142, numParams=0, isVararg=0, maxStackSize=3

-- Register Operations:
   0: NEWTABLE	R0             ; R0 := {}
   1: SETTABLE	R0 RK256 R257  ; R0["code"] := 0
   2: GETUPVAL	R1 0           ; R1 := UpValue[0]
   3: GETTABLE	R1 R1 RK259    ; R1 := R1["mattool_get_deviceid"]
   4: CALL	R1 1 2             ; R1 := R1(...) -- b=1, c=2
   5: SETTABLE	R0 RK258 R1    ; R0["deviceId"] := R1
   6: GETUPVAL	R1 1           ; R1 := UpValue[1]
   7: GETTABLE	R1 R1 RK260    ; R1 := R1["write_json"]
   8: MOVE	R2 R0              ; R2 := R0
   9: CALL	R1 2 1             ; R1 := R1(...) -- b=2, c=1
  10: RETURN	R0 1             ; return R0

-- SubChunk 8:
-- SubChunk: lineDefined=144, lastLineDefined=151, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETGLOBAL	R1 K1         ; R1 := require
   1: LOADK	R2 K0             ; R2 := "lcurl"
   2: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   3: SETGLOBAL	R1 K0         ; lcurl := R1
   4: GETGLOBAL	R1 K2         ; R1 := string
   5: GETTABLE	R1 R1 RK259    ; R1 := R1["gsub"]
   6: GETGLOBAL	R2 K0         ; R2 := lcurl
   7: GETTABLE	R2 R2 RK260    ; R2 := R2["easy"]
   8: CALL	R2 1 2             ; R2 := R2(...) -- b=1, c=2
   9: SELF	R2 R2 R261         ; R2, R3 := R2, R261
  10: MOVE	R4 R0              ; R4 := R0
  11: CALL	R2 3 2             ; R2 := R2(...) -- b=3, c=2
  12: LOADK	R3 K6             ; R3 := "%%2F"
  13: LOADK	R4 K7             ; R4 := "/"
  14: TAILCALL	R1 4 0         ; tailcall R1(...) -- b=4, c=0
  15: RETURN	R1 0             ; return
  16: RETURN	R0 1             ; return R0

-- SubChunk 9:
-- SubChunk: lineDefined=153, lastLineDefined=253, numParams=0, isVararg=0, maxStackSize=22

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "nixio.fs"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "luci.http.protocol.mime"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K0         ; R2 := require
   7: LOADK	R3 K3             ; R3 := "luci.ltn12"
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: GETGLOBAL	R3 K0         ; R3 := require
  10: LOADK	R4 K4             ; R4 := "xiaoqiang.XQLog"
  11: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  12: GETUPVAL	R4 0           ; R4 := UpValue[0]
  13: GETTABLE	R4 R4 RK261    ; R4 := R4["formvalue"]
  14: LOADK	R5 K6             ; R5 := "path"
  15: LOADBOOL	R6 0 0         ; R6 := false
  16: LOADK	R7 K7             ; R7 := "string"
  17: CALL	R4 4 2             ; R4 := R4(...) -- b=4, c=2
  18: GETUPVAL	R5 1           ; R5 := UpValue[1]
  19: GETTABLE	R5 R5 RK264    ; R5 := R5["isStrNil"]
  20: MOVE	R6 R4              ; R6 := R4
  21: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  22: TEST	R5 0 0             ; if  R5 then goto 0
  23: JMP	8                   ; goto 8
  24: GETUPVAL	R5 0           ; R5 := UpValue[0]
  25: GETTABLE	R5 R5 RK265    ; R5 := R5["status"]
  26: LOADK	R6 K10            ; R6 := 404
  27: GETGLOBAL	R7 K11        ; R7 := _
  28: LOADK	R8 K12            ; R8 := "no Such file"
  29: CALL	R7 2 0             ; R7 := R7(...) -- b=2, c=0
  30: CALL	R5 0 1             ; R5 := R5(...) -- b=0, c=1
  31: RETURN	R0 1             ; return R0
  32: LOADK	R5 K13            ; R5 := "/userdisk/data/"
  33: LOADK	R6 K14            ; R6 := "/mnt/"
  34: LOADK	R7 K15            ; R7 := "/userdisk/privacyData/"
  35: LOADK	R8 K16            ; R8 := "/userdisk/appdata/"
  36: LOADK	R9 K17            ; R9 := "/userdisk/.thumbnails/"
  37: GETGLOBAL	R10 K7        ; R10 := string
  38: GETTABLE	R10 R10 RK274  ; R10 := R10["sub"]
  39: MOVE	R11 R4             ; R11 := R4
  40: LOADK	R12 K19           ; R12 := 1
  41: GETGLOBAL	R13 K7        ; R13 := string
  42: GETTABLE	R13 R13 RK276  ; R13 := R13["len"]
  43: MOVE	R14 R5             ; R14 := R5
  44: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
  45: CALL	R10 0 2            ; R10 := R10(...) -- b=0, c=2
  46: EQ	R10 R5 0             ; if R10 == R5 then goto 0
  47: JMP	52                  ; goto 52
  48: GETGLOBAL	R10 K7        ; R10 := string
  49: GETTABLE	R10 R10 RK274  ; R10 := R10["sub"]
  50: MOVE	R11 R4             ; R11 := R4
  51: LOADK	R12 K19           ; R12 := 1
  52: GETGLOBAL	R13 K7        ; R13 := string
  53: GETTABLE	R13 R13 RK276  ; R13 := R13["len"]
  54: MOVE	R14 R6             ; R14 := R6
  55: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
  56: CALL	R10 0 2            ; R10 := R10(...) -- b=0, c=2
  57: EQ	R10 R6 0             ; if R10 == R6 then goto 0
  58: JMP	41                  ; goto 41
  59: GETGLOBAL	R10 K7        ; R10 := string
  60: GETTABLE	R10 R10 RK274  ; R10 := R10["sub"]
  61: MOVE	R11 R4             ; R11 := R4
  62: LOADK	R12 K19           ; R12 := 1
  63: GETGLOBAL	R13 K7        ; R13 := string
  64: GETTABLE	R13 R13 RK276  ; R13 := R13["len"]
  65: MOVE	R14 R7             ; R14 := R7
  66: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
  67: CALL	R10 0 2            ; R10 := R10(...) -- b=0, c=2
  68: EQ	R10 R7 0             ; if R10 == R7 then goto 0
  69: JMP	30                  ; goto 30
  70: GETGLOBAL	R10 K7        ; R10 := string
  71: GETTABLE	R10 R10 RK274  ; R10 := R10["sub"]
  72: MOVE	R11 R4             ; R11 := R4
  73: LOADK	R12 K19           ; R12 := 1
  74: GETGLOBAL	R13 K7        ; R13 := string
  75: GETTABLE	R13 R13 RK276  ; R13 := R13["len"]
  76: MOVE	R14 R8             ; R14 := R8
  77: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
  78: CALL	R10 0 2            ; R10 := R10(...) -- b=0, c=2
  79: EQ	R10 R8 0             ; if R10 == R8 then goto 0
  80: JMP	19                  ; goto 19
  81: GETGLOBAL	R10 K7        ; R10 := string
  82: GETTABLE	R10 R10 RK274  ; R10 := R10["sub"]
  83: MOVE	R11 R4             ; R11 := R4
  84: LOADK	R12 K19           ; R12 := 1
  85: GETGLOBAL	R13 K7        ; R13 := string
  86: GETTABLE	R13 R13 RK276  ; R13 := R13["len"]
  87: MOVE	R14 R9             ; R14 := R9
  88: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
  89: CALL	R10 0 2            ; R10 := R10(...) -- b=0, c=2
  90: EQ	R10 R9 0             ; if R10 == R9 then goto 0
  91: JMP	8                   ; goto 8
  92: GETUPVAL	R10 0          ; R10 := UpValue[0]
  93: GETTABLE	R10 R10 RK265  ; R10 := R10["status"]
  94: LOADK	R11 K21           ; R11 := 403
  95: GETGLOBAL	R12 K11       ; R12 := _
  96: LOADK	R13 K22           ; R13 := "no permission"
  97: CALL	R12 2 0            ; R12 := R12(...) -- b=2, c=0
  98: CALL	R10 0 1            ; R10 := R10(...) -- b=0, c=1
  99: RETURN	R0 1             ; return R0
 100: GETTABLE	R10 R3 RK279   ; R10 := R3["log"]
 101: LOADK	R11 K24           ; R11 := 7
 102: LOADK	R12 K25           ; R12 := "=============path = "
 103: MOVE	R13 R4             ; R13 := R4
 104: CONCAT	R12 R12 R13      ; R12 := R12 .. R13
 105: CALL	R10 3 1            ; R10 := R10(...) -- b=3, c=1
 106: GETGLOBAL	R10 K7        ; R10 := string
 107: GETTABLE	R10 R10 RK282  ; R10 := R10["find"]
 108: MOVE	R11 R4             ; R11 := R4
 109: LOADK	R12 K27           ; R12 := "/%.%./"
 110: CALL	R10 3 2            ; R10 := R10(...) -- b=3, c=2
 111: TEST	R10 0 0            ; if  R10 then goto 0
 112: JMP	8                   ; goto 8
 113: GETUPVAL	R10 0          ; R10 := UpValue[0]
 114: GETTABLE	R10 R10 RK265  ; R10 := R10["status"]
 115: LOADK	R11 K10           ; R11 := 404
 116: GETGLOBAL	R12 K11       ; R12 := _
 117: LOADK	R13 K12           ; R13 := "no Such file"
 118: CALL	R12 2 0            ; R12 := R12(...) -- b=2, c=0
 119: CALL	R10 0 1            ; R10 := R10(...) -- b=0, c=1
 120: RETURN	R0 1             ; return R0
 121: GETTABLE	R10 R0 RK284   ; R10 := R0["stat"]
 122: MOVE	R11 R4             ; R11 := R4
 123: CALL	R10 2 2            ; R10 := R10(...) -- b=2, c=2
 124: TEST	R10 1 0            ; if not R10 then goto 0
 125: JMP	8                   ; goto 8
 126: GETUPVAL	R11 0          ; R11 := UpValue[0]
 127: GETTABLE	R11 R11 RK265  ; R11 := R11["status"]
 128: LOADK	R12 K10           ; R12 := 404
 129: GETGLOBAL	R13 K11       ; R13 := _
 130: LOADK	R14 K12           ; R14 := "no Such file"
 131: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
 132: CALL	R11 0 1            ; R11 := R11(...) -- b=0, c=1
 133: RETURN	R0 1             ; return R0
 134: GETUPVAL	R11 0          ; R11 := UpValue[0]
 135: GETTABLE	R11 R11 RK285  ; R11 := R11["header"]
 136: LOADK	R12 K30           ; R12 := "Accept-Ranges"
 137: LOADK	R13 K31           ; R13 := "bytes"
 138: CALL	R11 3 1            ; R11 := R11(...) -- b=3, c=1
 139: GETUPVAL	R11 0          ; R11 := UpValue[0]
 140: GETTABLE	R11 R11 RK285  ; R11 := R11["header"]
 141: LOADK	R12 K32           ; R12 := "Content-Type"
 142: GETTABLE	R13 R1 RK289   ; R13 := R1["to_mime"]
 143: MOVE	R14 R4             ; R14 := R4
 144: CALL	R13 2 0            ; R13 := R13(...) -- b=2, c=0
 145: CALL	R11 0 1            ; R11 := R11(...) -- b=0, c=1
 146: GETUPVAL	R11 0          ; R11 := UpValue[0]
 147: GETTABLE	R11 R11 RK290  ; R11 := R11["getenv"]
 148: LOADK	R12 K35           ; R12 := "HTTP_RANGE"
 149: CALL	R11 2 2            ; R11 := R11(...) -- b=2, c=2
 150: TEST	R11 0 0            ; if  R11 then goto 0
 151: JMP	19                  ; goto 19
 152: GETUPVAL	R12 0          ; R12 := UpValue[0]
 153: GETTABLE	R12 R12 RK265  ; R12 := R12["status"]
 154: LOADK	R13 K36           ; R13 := 206
 155: CALL	R12 2 1            ; R12 := R12(...) -- b=2, c=1
 156: GETGLOBAL	R12 K7        ; R12 := string
 157: GETTABLE	R12 R12 RK293  ; R12 := R12["gsub"]
 158: MOVE	R13 R11            ; R13 := R11
 159: LOADK	R14 K38           ; R14 := "bytes="
 160: LOADK	R15 K39           ; R15 := ""
 161: CALL	R12 4 2            ; R12 := R12(...) -- b=4, c=2
 162: MOVE	R11 R12            ; R11 := R12
 163: GETGLOBAL	R12 K7        ; R12 := string
 164: GETTABLE	R12 R12 RK293  ; R12 := R12["gsub"]
 165: MOVE	R13 R11            ; R13 := R11
 166: LOADK	R14 K40           ; R14 := "-"
 167: LOADK	R15 K39           ; R15 := ""
 168: CALL	R12 4 2            ; R12 := R12(...) -- b=4, c=2
 169: MOVE	R11 R12            ; R11 := R12
 170: JMP	1                   ; goto 1
 171: LOADK	R11 K41           ; R11 := 0
 172: GETTABLE	R12 R3 RK279   ; R12 := R3["log"]
 173: LOADK	R13 K24           ; R13 := 7
 174: LOADK	R14 K42           ; R14 := "=============range = "
 175: MOVE	R15 R11            ; R15 := R11
 176: CONCAT	R14 R14 R15      ; R14 := R14 .. R15
 177: CALL	R12 3 1            ; R12 := R12(...) -- b=3, c=1
 178: LOADK	R12 K43           ; R12 := "bytes "
 179: MOVE	R13 R11            ; R13 := R11
 180: LOADK	R14 K40           ; R14 := "-"
 181: GETTABLE	R15 R10 RK300  ; R15 := R10["size"]
 182: SUB	R15 R15 R275        ; R15 := R15 - R275
 183: LOADK	R16 K45           ; R16 := "/"
 184: GETTABLE	R17 R10 RK300  ; R17 := R10["size"]
 185: CONCAT	R12 R12 R17      ; R12 := R12 .. R17
 186: GETTABLE	R13 R3 RK279   ; R13 := R3["log"]
 187: LOADK	R14 K24           ; R14 := 7
 188: LOADK	R15 K46           ; R15 := "=============contentRange = "
 189: MOVE	R16 R12            ; R16 := R12
 190: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 191: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 192: GETUPVAL	R13 0          ; R13 := UpValue[0]
 193: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 194: LOADK	R14 K47           ; R14 := "Content-Length"
 195: GETTABLE	R15 R10 RK300  ; R15 := R10["size"]
 196: SUB	R15 R15 R11         ; R15 := R15 - R11
 197: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 198: GETUPVAL	R13 0          ; R13 := UpValue[0]
 199: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 200: LOADK	R14 K48           ; R14 := "Content-Range"
 201: MOVE	R15 R12            ; R15 := R12
 202: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 203: GETUPVAL	R13 0          ; R13 := UpValue[0]
 204: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 205: LOADK	R14 K49           ; R14 := "Content-Disposition"
 206: LOADK	R15 K50           ; R15 := "attachment; filename="
 207: GETTABLE	R16 R0 RK307   ; R16 := R0["basename"]
 208: MOVE	R17 R4             ; R17 := R4
 209: CALL	R16 2 2            ; R16 := R16(...) -- b=2, c=2
 210: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 211: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 212: GETGLOBAL	R13 K7        ; R13 := string
 213: GETTABLE	R13 R13 RK274  ; R13 := R13["sub"]
 214: MOVE	R14 R4             ; R14 := R4
 215: LOADK	R15 K19           ; R15 := 1
 216: GETGLOBAL	R16 K7        ; R16 := string
 217: GETTABLE	R16 R16 RK276  ; R16 := R16["len"]
 218: MOVE	R17 R5             ; R17 := R5
 219: CALL	R16 2 0            ; R16 := R16(...) -- b=2, c=0
 220: CALL	R13 0 2            ; R13 := R13(...) -- b=0, c=2
 221: EQ	R13 R5 0             ; if R13 == R5 then goto 0
 222: JMP	22                  ; goto 22
 223: GETUPVAL	R13 0          ; R13 := UpValue[0]
 224: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 225: LOADK	R14 K52           ; R14 := "X-Accel-Redirect"
 226: LOADK	R15 K53           ; R15 := "/download-userdisk/"
 227: GETGLOBAL	R16 K54       ; R16 := pathEncode
 228: GETGLOBAL	R17 K7        ; R17 := string
 229: GETTABLE	R17 R17 RK274  ; R17 := R17["sub"]
 230: MOVE	R18 R4             ; R18 := R4
 231: GETGLOBAL	R19 K7        ; R19 := string
 232: GETTABLE	R19 R19 RK276  ; R19 := R19["len"]
 233: MOVE	R20 R5             ; R20 := R5
 234: CALL	R19 2 2            ; R19 := R19(...) -- b=2, c=2
 235: ADD	R19 R19 R275        ; R19 := R19 + R275
 236: GETGLOBAL	R20 K7        ; R20 := string
 237: GETTABLE	R20 R20 RK276  ; R20 := R20["len"]
 238: MOVE	R21 R4             ; R21 := R4
 239: CALL	R20 2 0            ; R20 := R20(...) -- b=2, c=0
 240: CALL	R17 0 0            ; R17 := R17(...) -- b=0, c=0
 241: CALL	R16 0 2            ; R16 := R16(...) -- b=0, c=2
 242: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 243: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 244: JMP	131                 ; goto 131
 245: GETGLOBAL	R13 K7        ; R13 := string
 246: GETTABLE	R13 R13 RK274  ; R13 := R13["sub"]
 247: MOVE	R14 R4             ; R14 := R4
 248: LOADK	R15 K19           ; R15 := 1
 249: GETGLOBAL	R16 K7        ; R16 := string
 250: GETTABLE	R16 R16 RK276  ; R16 := R16["len"]
 251: MOVE	R17 R6             ; R17 := R6
 252: CALL	R16 2 0            ; R16 := R16(...) -- b=2, c=0
 253: CALL	R13 0 2            ; R13 := R13(...) -- b=0, c=2
 254: EQ	R13 R6 0             ; if R13 == R6 then goto 0
 255: JMP	22                  ; goto 22
 256: GETUPVAL	R13 0          ; R13 := UpValue[0]
 257: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 258: LOADK	R14 K52           ; R14 := "X-Accel-Redirect"
 259: LOADK	R15 K55           ; R15 := "/download-mnt/"
 260: GETGLOBAL	R16 K54       ; R16 := pathEncode
 261: GETGLOBAL	R17 K7        ; R17 := string
 262: GETTABLE	R17 R17 RK274  ; R17 := R17["sub"]
 263: MOVE	R18 R4             ; R18 := R4
 264: GETGLOBAL	R19 K7        ; R19 := string
 265: GETTABLE	R19 R19 RK276  ; R19 := R19["len"]
 266: MOVE	R20 R6             ; R20 := R6
 267: CALL	R19 2 2            ; R19 := R19(...) -- b=2, c=2
 268: ADD	R19 R19 R275        ; R19 := R19 + R275
 269: GETGLOBAL	R20 K7        ; R20 := string
 270: GETTABLE	R20 R20 RK276  ; R20 := R20["len"]
 271: MOVE	R21 R4             ; R21 := R4
 272: CALL	R20 2 0            ; R20 := R20(...) -- b=2, c=0
 273: CALL	R17 0 0            ; R17 := R17(...) -- b=0, c=0
 274: CALL	R16 0 2            ; R16 := R16(...) -- b=0, c=2
 275: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 276: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 277: JMP	98                  ; goto 98
 278: GETGLOBAL	R13 K7        ; R13 := string
 279: GETTABLE	R13 R13 RK274  ; R13 := R13["sub"]
 280: MOVE	R14 R4             ; R14 := R4
 281: LOADK	R15 K19           ; R15 := 1
 282: GETGLOBAL	R16 K7        ; R16 := string
 283: GETTABLE	R16 R16 RK276  ; R16 := R16["len"]
 284: MOVE	R17 R7             ; R17 := R7
 285: CALL	R16 2 0            ; R16 := R16(...) -- b=2, c=0
 286: CALL	R13 0 2            ; R13 := R13(...) -- b=0, c=2
 287: EQ	R13 R7 0             ; if R13 == R7 then goto 0
 288: JMP	22                  ; goto 22
 289: GETUPVAL	R13 0          ; R13 := UpValue[0]
 290: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 291: LOADK	R14 K52           ; R14 := "X-Accel-Redirect"
 292: LOADK	R15 K56           ; R15 := "/download-pridisk/"
 293: GETGLOBAL	R16 K54       ; R16 := pathEncode
 294: GETGLOBAL	R17 K7        ; R17 := string
 295: GETTABLE	R17 R17 RK274  ; R17 := R17["sub"]
 296: MOVE	R18 R4             ; R18 := R4
 297: GETGLOBAL	R19 K7        ; R19 := string
 298: GETTABLE	R19 R19 RK276  ; R19 := R19["len"]
 299: MOVE	R20 R7             ; R20 := R7
 300: CALL	R19 2 2            ; R19 := R19(...) -- b=2, c=2
 301: ADD	R19 R19 R275        ; R19 := R19 + R275
 302: GETGLOBAL	R20 K7        ; R20 := string
 303: GETTABLE	R20 R20 RK276  ; R20 := R20["len"]
 304: MOVE	R21 R4             ; R21 := R4
 305: CALL	R20 2 0            ; R20 := R20(...) -- b=2, c=0
 306: CALL	R17 0 0            ; R17 := R17(...) -- b=0, c=0
 307: CALL	R16 0 2            ; R16 := R16(...) -- b=0, c=2
 308: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 309: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 310: JMP	65                  ; goto 65
 311: GETGLOBAL	R13 K7        ; R13 := string
 312: GETTABLE	R13 R13 RK274  ; R13 := R13["sub"]
 313: MOVE	R14 R4             ; R14 := R4
 314: LOADK	R15 K19           ; R15 := 1
 315: GETGLOBAL	R16 K7        ; R16 := string
 316: GETTABLE	R16 R16 RK276  ; R16 := R16["len"]
 317: MOVE	R17 R8             ; R17 := R8
 318: CALL	R16 2 0            ; R16 := R16(...) -- b=2, c=0
 319: CALL	R13 0 2            ; R13 := R13(...) -- b=0, c=2
 320: EQ	R13 R8 0             ; if R13 == R8 then goto 0
 321: JMP	22                  ; goto 22
 322: GETUPVAL	R13 0          ; R13 := UpValue[0]
 323: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 324: LOADK	R14 K52           ; R14 := "X-Accel-Redirect"
 325: LOADK	R15 K57           ; R15 := "/download-userdisk-appdata/"
 326: GETGLOBAL	R16 K54       ; R16 := pathEncode
 327: GETGLOBAL	R17 K7        ; R17 := string
 328: GETTABLE	R17 R17 RK274  ; R17 := R17["sub"]
 329: MOVE	R18 R4             ; R18 := R4
 330: GETGLOBAL	R19 K7        ; R19 := string
 331: GETTABLE	R19 R19 RK276  ; R19 := R19["len"]
 332: MOVE	R20 R8             ; R20 := R8
 333: CALL	R19 2 2            ; R19 := R19(...) -- b=2, c=2
 334: ADD	R19 R19 R275        ; R19 := R19 + R275
 335: GETGLOBAL	R20 K7        ; R20 := string
 336: GETTABLE	R20 R20 RK276  ; R20 := R20["len"]
 337: MOVE	R21 R4             ; R21 := R4
 338: CALL	R20 2 0            ; R20 := R20(...) -- b=2, c=0
 339: CALL	R17 0 0            ; R17 := R17(...) -- b=0, c=0
 340: CALL	R16 0 2            ; R16 := R16(...) -- b=0, c=2
 341: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 342: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 343: JMP	32                  ; goto 32
 344: GETGLOBAL	R13 K7        ; R13 := string
 345: GETTABLE	R13 R13 RK274  ; R13 := R13["sub"]
 346: MOVE	R14 R4             ; R14 := R4
 347: LOADK	R15 K19           ; R15 := 1
 348: GETGLOBAL	R16 K7        ; R16 := string
 349: GETTABLE	R16 R16 RK276  ; R16 := R16["len"]
 350: MOVE	R17 R9             ; R17 := R9
 351: CALL	R16 2 0            ; R16 := R16(...) -- b=2, c=0
 352: CALL	R13 0 2            ; R13 := R13(...) -- b=0, c=2
 353: EQ	R13 R9 0             ; if R13 == R9 then goto 0
 354: JMP	21                  ; goto 21
 355: GETUPVAL	R13 0          ; R13 := UpValue[0]
 356: GETTABLE	R13 R13 RK285  ; R13 := R13["header"]
 357: LOADK	R14 K52           ; R14 := "X-Accel-Redirect"
 358: LOADK	R15 K58           ; R15 := "/download-userdisk-thumbnails/"
 359: GETGLOBAL	R16 K54       ; R16 := pathEncode
 360: GETGLOBAL	R17 K7        ; R17 := string
 361: GETTABLE	R17 R17 RK274  ; R17 := R17["sub"]
 362: MOVE	R18 R4             ; R18 := R4
 363: GETGLOBAL	R19 K7        ; R19 := string
 364: GETTABLE	R19 R19 RK276  ; R19 := R19["len"]
 365: MOVE	R20 R9             ; R20 := R9
 366: CALL	R19 2 2            ; R19 := R19(...) -- b=2, c=2
 367: ADD	R19 R19 R275        ; R19 := R19 + R275
 368: GETGLOBAL	R20 K7        ; R20 := string
 369: GETTABLE	R20 R20 RK276  ; R20 := R20["len"]
 370: MOVE	R21 R4             ; R21 := R4
 371: CALL	R20 2 0            ; R20 := R20(...) -- b=2, c=0
 372: CALL	R17 0 0            ; R17 := R17(...) -- b=0, c=0
 373: CALL	R16 0 2            ; R16 := R16(...) -- b=0, c=2
 374: CONCAT	R15 R15 R16      ; R15 := R15 .. R16
 375: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 376: RETURN	R0 1             ; return R0

-- SubChunk 10:
-- SubChunk: lineDefined=255, lastLineDefined=320, numParams=0, isVararg=0, maxStackSize=18

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := require
   1: LOADK	R2 K1             ; R2 := "xiaoqiang.XQLog"
   2: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   3: GETGLOBAL	R2 K0         ; R2 := require
   4: LOADK	R3 K2             ; R3 := "luci.fs"
   5: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   6: LOADK	R3 K3             ; R3 := "/userdisk/upload.tmp"
   7: GETTABLE	R4 R2 RK260    ; R4 := R2["isfile"]
   8: MOVE	R5 R3              ; R5 := R3
   9: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  10: TEST	R4 0 0             ; if  R4 then goto 0
  11: JMP	3                   ; goto 3
  12: GETTABLE	R4 R2 RK261    ; R4 := R2["unlink"]
  13: MOVE	R5 R3              ; R5 := R3
  14: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  15: LOADNIL	R4 R4           ; R4 := nil
  16: GETUPVAL	R5 0           ; R5 := UpValue[0]
  17: GETTABLE	R5 R5 RK262    ; R5 := R5["setfilehandler"]
  18: CLOSURE	R6 0            ; R6 := closure(0)
  19: MOVE	R0 R0              ; R0 := R0
  20: MOVE	R0 R3              ; R0 := R3
  21: MOVE	R0 R4              ; R0 := R4
  22: CALL	R5 2 1             ; R5 := R5(...) -- b=2, c=1
  23: GETUPVAL	R5 0           ; R5 := UpValue[0]
  24: GETTABLE	R5 R5 RK263    ; R5 := R5["formvalue"]
  25: LOADK	R6 K8             ; R6 := "target"
  26: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  27: GETGLOBAL	R6 K9         ; R6 := string
  28: GETTABLE	R6 R6 RK266    ; R6 := R6["match"]
  29: MOVE	R7 R5              ; R7 := R5
  30: LOADK	R8 K11            ; R8 := "/$"
  31: CALL	R6 3 2             ; R6 := R6(...) -- b=3, c=2
  32: EQ	R6 R268 0            ; if R6 == nil then goto 0
  33: JMP	3                   ; goto 3
  34: MOVE	R6 R5              ; R6 := R5
  35: LOADK	R7 K13            ; R7 := "/"
  36: CONCAT	R5 R6 R7         ; R5 := R6 .. R7
  37: GETTABLE	R6 R2 RK270    ; R6 := R2["mkdir"]
  38: MOVE	R7 R5              ; R7 := R5
  39: LOADBOOL	R8 1 0         ; R8 := true
  40: CALL	R6 3 1             ; R6 := R6(...) -- b=3, c=1
  41: MOVE	R6 R4              ; R6 := R4
  42: GETTABLE	R7 R2 RK260    ; R7 := R2["isfile"]
  43: MOVE	R8 R5              ; R8 := R5
  44: MOVE	R9 R6              ; R9 := R6
  45: CONCAT	R8 R8 R9         ; R8 := R8 .. R9
  46: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  47: TEST	R7 0 0             ; if  R7 then goto 0
  48: JMP	39                  ; goto 39
  49: MOVE	R7 R6              ; R7 := R6
  50: SELF	R8 R7 R266         ; R8, R9 := R7, R266
  51: LOADK	R10 K15           ; R10 := ".+()%.%w+$"
  52: CALL	R8 3 2             ; R8 := R8(...) -- b=3, c=2
  53: TEST	R8 0 0             ; if  R8 then goto 0
  54: JMP	5                   ; goto 5
  55: SELF	R9 R7 R272         ; R9, R10 := R7, R272
  56: LOADK	R11 K17           ; R11 := 1
  57: SUB	R12 R8 R273         ; R12 := R8 - R273
  58: CALL	R9 4 2             ; R9 := R9(...) -- b=4, c=2
  59: MOVE	R7 R9              ; R7 := R9
  60: SELF	R9 R6 R266         ; R9, R10 := R6, R266
  61: LOADK	R11 K18           ; R11 := ".+%.(%w+)$"
  62: CALL	R9 3 2             ; R9 := R9(...) -- b=3, c=2
  63: LOADK	R10 K17           ; R10 := 1
  64: LOADK	R11 K19           ; R11 := 100
  65: LOADK	R12 K17           ; R12 := 1
  66: FORPREP	R10 0           ; forprep R10, R11, R12, R13 -- sBx=0
  67: MOVE	R14 R7             ; R14 := R7
  68: LOADK	R15 K20           ; R15 := "("
  69: MOVE	R16 R13            ; R16 := R13
  70: LOADK	R17 K21           ; R17 := ")"
  71: CONCAT	R14 R14 R17      ; R14 := R14 .. R17
  72: TEST	R9 0 0             ; if  R9 then goto 0
  73: JMP	4                   ; goto 4
  74: MOVE	R15 R14            ; R15 := R14
  75: LOADK	R16 K22           ; R16 := "."
  76: MOVE	R17 R9             ; R17 := R9
  77: CONCAT	R14 R15 R17      ; R14 := R15 .. R17
  78: GETTABLE	R15 R2 RK260   ; R15 := R2["isfile"]
  79: MOVE	R16 R5             ; R16 := R5
  80: MOVE	R17 R14            ; R17 := R14
  81: CONCAT	R16 R16 R17      ; R16 := R16 .. R17
  82: CALL	R15 2 2            ; R15 := R15(...) -- b=2, c=2
  83: TEST	R15 1 0            ; if not R15 then goto 0
  84: JMP	2                   ; goto 2
  85: MOVE	R6 R14             ; R6 := R14
  86: JMP	1                   ; goto 1
  87: FORLOOP	R10 0           ; forloop R10, R11, R12, R13 -- sBx=0
  88: MOVE	R7 R5              ; R7 := R5
  89: MOVE	R8 R6              ; R8 := R6
  90: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  91: GETTABLE	R8 R1 RK279    ; R8 := R1["log"]
  92: LOADK	R9 K24            ; R9 := 7
  93: LOADK	R10 K25           ; R10 := "dest="
  94: MOVE	R11 R7             ; R11 := R7
  95: CONCAT	R10 R10 R11      ; R10 := R10 .. R11
  96: CALL	R8 3 1             ; R8 := R8(...) -- b=3, c=1
  97: GETTABLE	R8 R2 RK282    ; R8 := R2["rename"]
  98: MOVE	R9 R3              ; R9 := R3
  99: MOVE	R10 R7             ; R10 := R7
 100: CALL	R8 3 1             ; R8 := R8(...) -- b=3, c=1
 101: NEWTABLE	R8             ; R8 := {}
 102: SETTABLE	R8 RK283 R284  ; R8["code"] := 0
 103: GETUPVAL	R9 0           ; R9 := UpValue[0]
 104: GETTABLE	R9 R9 RK285    ; R9 := R9["write_json"]
 105: MOVE	R10 R8             ; R10 := R8
 106: CALL	R9 2 1             ; R9 := R9(...) -- b=2, c=1
 107: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=265, lastLineDefined=284, numParams=3, isVararg=0, maxStackSize=7

-- Register Operations:
   0: GETUPVAL	R3 0           ; R3 := UpValue[0]
   1: TEST	R3 1 0             ; if not R3 then goto 0
   2: JMP	34                  ; goto 34
   3: TEST	R0 0 0             ; if  R0 then goto 0
   4: JMP	32                  ; goto 32
   5: GETTABLE	R3 R0 RK256    ; R3 := R0["name"]
   6: EQ	R3 R257 0            ; if R3 == "file" then goto 0
   7: JMP	29                  ; goto 29
   8: GETGLOBAL	R3 K2         ; R3 := io
   9: GETTABLE	R3 R3 RK259    ; R3 := R3["open"]
  10: GETUPVAL	R4 1           ; R4 := UpValue[1]
  11: LOADK	R5 K4             ; R5 := "w"
  12: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  13: SETUPVAL	R3 0           ; UpValue[0] := R3
  14: GETTABLE	R3 R0 RK257    ; R3 := R0["file"]
  15: SETUPVAL	R3 2           ; UpValue[2] := R3
  16: GETGLOBAL	R3 K5         ; R3 := string
  17: GETTABLE	R3 R3 RK262    ; R3 := R3["gsub"]
  18: GETUPVAL	R4 2           ; R4 := UpValue[2]
  19: LOADK	R5 K7             ; R5 := "+"
  20: LOADK	R6 K8             ; R6 := " "
  21: CALL	R3 4 2             ; R3 := R3(...) -- b=4, c=2
  22: SETUPVAL	R3 2           ; UpValue[2] := R3
  23: GETGLOBAL	R3 K5         ; R3 := string
  24: GETTABLE	R3 R3 RK262    ; R3 := R3["gsub"]
  25: GETUPVAL	R4 2           ; R4 := UpValue[2]
  26: LOADK	R5 K9             ; R5 := "%%(%x%x)"
  27: CLOSURE	R6 0            ; R6 := closure(0)
  28: CALL	R3 4 2             ; R3 := R3(...) -- b=4, c=2
  29: SETUPVAL	R3 2           ; UpValue[2] := R3
  30: GETUPVAL	R3 2           ; R3 := UpValue[2]
  31: GETTABLE	R3 R3 RK262    ; R3 := R3["gsub"]
  32: GETUPVAL	R4 2           ; R4 := UpValue[2]
  33: LOADK	R5 K10            ; R5 := "
"
  34: LOADK	R6 K11            ; R6 := "
"
  35: CALL	R3 4 2             ; R3 := R3(...) -- b=4, c=2
  36: SETUPVAL	R3 2           ; UpValue[2] := R3
  37: TEST	R1 0 0             ; if  R1 then goto 0
  38: JMP	4                   ; goto 4
  39: GETUPVAL	R3 0           ; R3 := UpValue[0]
  40: SELF	R3 R3 R268         ; R3, R4 := R3, R268
  41: MOVE	R5 R1              ; R5 := R1
  42: CALL	R3 3 1             ; R3 := R3(...) -- b=3, c=1
  43: TEST	R2 0 0             ; if  R2 then goto 0
  44: JMP	3                   ; goto 3
  45: GETUPVAL	R3 0           ; R3 := UpValue[0]
  46: SELF	R3 R3 R269         ; R3, R4 := R3, R269
  47: CALL	R3 2 1             ; R3 := R3(...) -- b=2, c=1
  48: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=272, lastLineDefined=274, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := string
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["char"]
   2: GETGLOBAL	R2 K2         ; R2 := tonumber
   3: MOVE	R3 R0              ; R3 := R0
   4: LOADK	R4 K3             ; R4 := 16
   5: CALL	R2 3 0             ; R2 := R2(...) -- b=3, c=0
   6: TAILCALL	R1 0 0         ; tailcall R1(...) -- b=0, c=0
   7: RETURN	R1 0             ; return
   8: RETURN	R0 1             ; return R0



-- SubChunk 11:
-- SubChunk: lineDefined=322, lastLineDefined=347, numParams=0, isVararg=0, maxStackSize=15

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "luci.util"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "nixio.fs"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K0         ; R2 := require
   7: LOADK	R3 K3             ; R3 := "luci.http.protocol.mime"
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: GETGLOBAL	R3 K0         ; R3 := require
  10: LOADK	R4 K4             ; R4 := "luci.ltn12"
  11: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  12: GETGLOBAL	R4 K0         ; R4 := require
  13: LOADK	R5 K5             ; R5 := "xiaoqiang.XQLog"
  14: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  15: GETUPVAL	R5 0           ; R5 := UpValue[0]
  16: GETTABLE	R5 R5 RK262    ; R5 := R5["formvalue"]
  17: LOADK	R6 K7             ; R6 := "filePath"
  18: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  19: GETTABLE	R6 R4 RK264    ; R6 := R4["log"]
  20: LOADK	R7 K9             ; R7 := 7
  21: LOADK	R8 K10            ; R8 := "realPath = "
  22: MOVE	R9 R5              ; R9 := R5
  23: CALL	R6 4 1             ; R6 := R6(...) -- b=4, c=1
  24: EQ	R5 R267 0            ; if R5 == nil then goto 0
  25: JMP	8                   ; goto 8
  26: GETUPVAL	R6 0           ; R6 := UpValue[0]
  27: GETTABLE	R6 R6 RK268    ; R6 := R6["status"]
  28: LOADK	R7 K13            ; R7 := 404
  29: GETGLOBAL	R8 K14        ; R8 := _
  30: LOADK	R9 K15            ; R9 := "no Such file"
  31: CALL	R8 2 0             ; R8 := R8(...) -- b=2, c=0
  32: CALL	R6 0 1             ; R6 := R6(...) -- b=0, c=1
  33: RETURN	R0 1             ; return R0
  34: LOADK	R6 K16            ; R6 := "{"api":10, "files":[""
  35: MOVE	R7 R5              ; R7 := R5
  36: LOADK	R8 K17            ; R8 := ""]}"
  37: CONCAT	R6 R6 R8         ; R6 := R6 .. R8
  38: GETUPVAL	R7 1           ; R7 := UpValue[1]
  39: GETTABLE	R7 R7 RK274    ; R7 := R7["thrift_tunnel_to_datacenter"]
  40: MOVE	R8 R6              ; R8 := R6
  41: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  42: TEST	R7 0 0             ; if  R7 then goto 0
  43: JMP	34                  ; goto 34
  44: GETTABLE	R8 R7 RK275    ; R8 := R7["code"]
  45: EQ	R8 R276 0            ; if R8 == 0 then goto 0
  46: JMP	31                  ; goto 31
  47: GETTABLE	R8 R7 RK277    ; R8 := R7["thumbnails"]
  48: GETTABLE	R8 R8 RK278    ; R8 := R8[1]
  49: GETTABLE	R9 R1 RK279    ; R9 := R1["stat"]
  50: MOVE	R10 R8             ; R10 := R8
  51: CALL	R9 2 2             ; R9 := R9(...) -- b=2, c=2
  52: GETUPVAL	R10 0          ; R10 := UpValue[0]
  53: GETTABLE	R10 R10 RK280  ; R10 := R10["header"]
  54: LOADK	R11 K25           ; R11 := "Content-Type"
  55: GETTABLE	R12 R2 RK282   ; R12 := R2["to_mime"]
  56: MOVE	R13 R8             ; R13 := R8
  57: CALL	R12 2 0            ; R12 := R12(...) -- b=2, c=0
  58: CALL	R10 0 1            ; R10 := R10(...) -- b=0, c=1
  59: GETUPVAL	R10 0          ; R10 := UpValue[0]
  60: GETTABLE	R10 R10 RK280  ; R10 := R10["header"]
  61: LOADK	R11 K27           ; R11 := "Content-Length"
  62: GETTABLE	R12 R9 RK284   ; R12 := R9["size"]
  63: CALL	R10 3 1            ; R10 := R10(...) -- b=3, c=1
  64: GETTABLE	R10 R3 RK285   ; R10 := R3["pump"]
  65: GETTABLE	R10 R10 RK286  ; R10 := R10["all"]
  66: GETTABLE	R11 R3 RK287   ; R11 := R3["source"]
  67: GETTABLE	R11 R11 RK288  ; R11 := R11["file"]
  68: GETGLOBAL	R12 K33       ; R12 := io
  69: GETTABLE	R12 R12 RK290  ; R12 := R12["open"]
  70: MOVE	R13 R8             ; R13 := R8
  71: LOADK	R14 K35           ; R14 := "r"
  72: CALL	R12 3 0            ; R12 := R12(...) -- b=3, c=0
  73: CALL	R11 0 2            ; R11 := R11(...) -- b=0, c=2
  74: GETUPVAL	R12 0          ; R12 := UpValue[0]
  75: GETTABLE	R12 R12 RK292  ; R12 := R12["write"]
  76: CALL	R10 3 1            ; R10 := R10(...) -- b=3, c=1
  77: JMP	7                   ; goto 7
  78: GETUPVAL	R8 0           ; R8 := UpValue[0]
  79: GETTABLE	R8 R8 RK268    ; R8 := R8["status"]
  80: LOADK	R9 K13            ; R9 := 404
  81: GETGLOBAL	R10 K14       ; R10 := _
  82: LOADK	R11 K37           ; R11 := "no Such thumb file"
  83: CALL	R10 2 0            ; R10 := R10(...) -- b=2, c=0
  84: CALL	R8 0 1             ; R8 := R8(...) -- b=0, c=1
  85: RETURN	R0 1             ; return R0

-- SubChunk 12:
-- SubChunk: lineDefined=349, lastLineDefined=367, numParams=0, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "nixio.fs"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: LOADBOOL	R1 1 0         ; R1 := true
   4: GETUPVAL	R2 0           ; R2 := UpValue[0]
   5: GETTABLE	R2 R2 RK258    ; R2 := R2["formvalue"]
   6: LOADK	R3 K3             ; R3 := "filePath"
   7: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   8: GETUPVAL	R3 1           ; R3 := UpValue[1]
   9: GETTABLE	R3 R3 RK260    ; R3 := R3["isStrNil"]
  10: MOVE	R4 R2              ; R4 := R2
  11: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  12: TEST	R3 0 0             ; if  R3 then goto 0
  13: JMP	2                   ; goto 2
  14: LOADBOOL	R1 0 0         ; R1 := false
  15: JMP	6                   ; goto 6
  16: GETTABLE	R3 R0 RK261    ; R3 := R0["stat"]
  17: MOVE	R4 R2              ; R4 := R2
  18: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  19: TEST	R3 1 0             ; if not R3 then goto 0
  20: JMP	1                   ; goto 1
  21: LOADBOOL	R1 0 0         ; R1 := false
  22: NEWTABLE	R3             ; R3 := {}
  23: SETTABLE	R3 RK262 R263  ; R3["code"] := 0
  24: SETTABLE	R3 RK264 R1    ; R3["exist"] := R1
  25: GETUPVAL	R4 0           ; R4 := UpValue[0]
  26: GETTABLE	R4 R4 RK265    ; R4 := R4["write_json"]
  27: MOVE	R5 R3              ; R5 := R3
  28: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  29: RETURN	R0 1             ; return R0

-- SubChunk 13:
-- SubChunk: lineDefined=369, lastLineDefined=408, numParams=0, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "luci.util"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "xiaoqiang.XQLog"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: LOADK	R2 K3             ; R2 := 0
   7: NEWTABLE	R3             ; R3 := {}
   8: GETUPVAL	R4 0           ; R4 := UpValue[0]
   9: GETTABLE	R4 R4 RK260    ; R4 := R4["formvalue"]
  10: LOADK	R5 K5             ; R5 := "pluginID"
  11: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  12: GETUPVAL	R5 0           ; R5 := UpValue[0]
  13: GETTABLE	R5 R5 RK260    ; R5 := R5["formvalue"]
  14: LOADK	R6 K6             ; R6 := "capability"
  15: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  16: GETGLOBAL	R6 K7         ; R6 := tonumber
  17: GETUPVAL	R7 0           ; R7 := UpValue[0]
  18: GETTABLE	R7 R7 RK260    ; R7 := R7["formvalue"]
  19: LOADK	R8 K8             ; R8 := "open"
  20: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  21: TEST	R7 1 0             ; if not R7 then goto 0
  22: JMP	1                   ; goto 1
  23: LOADK	R7 K3             ; R7 := 0
  24: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  25: GETTABLE	R7 R1 RK265    ; R7 := R1["check"]
  26: LOADK	R8 K3             ; R8 := 0
  27: GETTABLE	R9 R1 RK266    ; R9 := R1["KEY_FUNC_PLUGIN"]
  28: LOADK	R10 K11           ; R10 := 1
  29: CALL	R7 4 1             ; R7 := R7(...) -- b=4, c=1
  30: TEST	R6 0 0             ; if  R6 then goto 0
  31: JMP	30                  ; goto 30
  32: EQ	R6 R267 0            ; if R6 == 1 then goto 0
  33: JMP	28                  ; goto 28
  34: TEST	R4 0 0             ; if  R4 then goto 0
  35: JMP	24                  ; goto 24
  36: TEST	R5 0 0             ; if  R5 then goto 0
  37: JMP	22                  ; goto 22
  38: NEWTABLE	R7             ; R7 := {}
  39: SETTABLE	R7 RK268 R269  ; R7["api"] := 611
  40: SETTABLE	R7 RK261 R4    ; R7["pluginID"] := R4
  41: GETTABLE	R8 R0 RK270    ; R8 := R0["split"]
  42: MOVE	R9 R5              ; R9 := R5
  43: LOADK	R10 K15           ; R10 := ","
  44: CALL	R8 3 2             ; R8 := R8(...) -- b=3, c=2
  45: SETTABLE	R7 RK262 R8    ; R7["capability"] := R8
  46: GETUPVAL	R8 1           ; R8 := UpValue[1]
  47: GETTABLE	R8 R8 RK272    ; R8 := R8["thrift_tunnel_to_datacenter"]
  48: GETUPVAL	R9 2           ; R9 := UpValue[2]
  49: GETTABLE	R9 R9 RK273    ; R9 := R9["encode"]
  50: MOVE	R10 R7             ; R10 := R7
  51: CALL	R9 2 0             ; R9 := R9(...) -- b=2, c=0
  52: CALL	R8 0 2             ; R8 := R8(...) -- b=0, c=2
  53: TEST	R8 0 0             ; if  R8 then goto 0
  54: JMP	24                  ; goto 24
  55: GETTABLE	R9 R8 RK274    ; R9 := R8["code"]
  56: EQ	R9 R259 0            ; if R9 == 0 then goto 0
  57: JMP	21                  ; goto 21
  58: LOADK	R2 K19            ; R2 := 1595
  59: JMP	19                  ; goto 19
  60: LOADK	R2 K20            ; R2 := 1537
  61: JMP	17                  ; goto 17
  62: NEWTABLE	R7             ; R7 := {}
  63: SETTABLE	R7 RK268 R277  ; R7["api"] := 613
  64: GETUPVAL	R8 1           ; R8 := UpValue[1]
  65: GETTABLE	R8 R8 RK272    ; R8 := R8["thrift_tunnel_to_datacenter"]
  66: GETUPVAL	R9 2           ; R9 := UpValue[2]
  67: GETTABLE	R9 R9 RK273    ; R9 := R9["encode"]
  68: MOVE	R10 R7             ; R10 := R7
  69: CALL	R9 2 0             ; R9 := R9(...) -- b=2, c=0
  70: CALL	R8 0 2             ; R8 := R8(...) -- b=0, c=2
  71: TEST	R8 0 0             ; if  R8 then goto 0
  72: JMP	5                   ; goto 5
  73: GETTABLE	R9 R8 RK274    ; R9 := R8["code"]
  74: EQ	R9 R259 0            ; if R9 == 0 then goto 0
  75: JMP	2                   ; goto 2
  76: LOADK	R2 K3             ; R2 := 0
  77: JMP	1                   ; goto 1
  78: LOADK	R2 K22            ; R2 := 1601
  79: EQ	R2 R259 0            ; if R2 == 0 then goto 0
  80: JMP	5                   ; goto 5
  81: GETUPVAL	R7 3           ; R7 := UpValue[3]
  82: GETTABLE	R7 R7 RK280    ; R7 := R7["getErrorMessage"]
  83: MOVE	R8 R2              ; R8 := R2
  84: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  85: SETTABLE	R3 RK279 R7    ; R3["msg"] := R7
  86: SETTABLE	R3 RK274 R2    ; R3["code"] := R2
  87: GETUPVAL	R7 0           ; R7 := UpValue[0]
  88: GETTABLE	R7 R7 RK281    ; R7 := R7["write_json"]
  89: MOVE	R8 R3              ; R8 := R3
  90: CALL	R7 2 1             ; R7 := R7(...) -- b=2, c=1
  91: RETURN	R0 1             ; return R0

-- SubChunk 14:
-- SubChunk: lineDefined=410, lastLineDefined=443, numParams=0, isVararg=0, maxStackSize=17

-- Register Operations:
   0: LOADK	R0 K0             ; R0 := 0
   1: NEWTABLE	R1             ; R1 := {}
   2: GETUPVAL	R2 0           ; R2 := UpValue[0]
   3: GETTABLE	R2 R2 RK257    ; R2 := R2["thrift_tunnel_to_datacenter"]
   4: LOADK	R3 K2             ; R3 := "{"api":612}"
   5: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   6: GETUPVAL	R3 0           ; R3 := UpValue[0]
   7: GETTABLE	R3 R3 RK257    ; R3 := R3["thrift_tunnel_to_datacenter"]
   8: LOADK	R4 K3             ; R4 := "{"api":621}"
   9: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  10: TEST	R2 0 0             ; if  R2 then goto 0
  11: JMP	50                  ; goto 50
  12: GETTABLE	R4 R2 RK260    ; R4 := R2["code"]
  13: EQ	R4 R256 0            ; if R4 == 0 then goto 0
  14: JMP	47                  ; goto 47
  15: TEST	R3 0 0             ; if  R3 then goto 0
  16: JMP	45                  ; goto 45
  17: GETTABLE	R4 R2 RK260    ; R4 := R2["code"]
  18: EQ	R4 R256 0            ; if R4 == 0 then goto 0
  19: JMP	42                  ; goto 42
  20: NEWTABLE	R4             ; R4 := {}
  21: GETTABLE	R5 R2 RK262    ; R5 := R2["status"]
  22: EQ	R5 R263 0            ; if R5 == 1 then goto 0
  23: JMP	3                   ; goto 3
  24: LOADK	R5 K7             ; R5 := 1
  25: TEST	R5 1 0             ; if not R5 then goto 0
  26: JMP	1                   ; goto 1
  27: LOADK	R5 K0             ; R5 := 0
  28: SETTABLE	R1 RK261 R5    ; R1["enable"] := R5
  29: NEWTABLE	R5             ; R5 := {}
  30: GETTABLE	R6 R1 RK261    ; R6 := R1["enable"]
  31: EQ	R6 R263 0            ; if R6 == 1 then goto 0
  32: JMP	4                   ; goto 4
  33: GETTABLE	R6 R2 RK264    ; R6 := R2["plugin_ssh_status"]
  34: GETTABLE	R7 R6 RK265    ; R7 := R6["pluginID"]
  35: SETTABLE	R1 RK265 R7    ; R1["pluginID"] := R7
  36: GETTABLE	R5 R6 RK266    ; R5 := R6["capability"]
  37: GETGLOBAL	R6 K11        ; R6 := ipairs
  38: GETTABLE	R7 R3 RK268    ; R7 := R3["list"]
  39: CALL	R6 2 4             ; R6 := R6(...) -- b=2, c=4
  40: JMP	17                  ; goto 17
  41: SETTABLE	R10 RK261 R256 ; R10["enable"] := 0
  42: GETGLOBAL	R11 K11       ; R11 := ipairs
  43: MOVE	R12 R5             ; R12 := R5
  44: CALL	R11 2 4            ; R11 := R11(...) -- b=2, c=4
  45: JMP	5                   ; goto 5
  46: GETTABLE	R16 R10 RK269  ; R16 := R10["key"]
  47: EQ	R16 R15 0            ; if R16 == R15 then goto 0
  48: JMP	2                   ; goto 2
  49: SETTABLE	R10 RK261 R263 ; R10["enable"] := 1
  50: JMP	2                   ; goto 2
  51: TFORLOOP	R11 0 2        ; tforloop R11, R12 -- b=0, c=2
  52: JMP	-7                  ; goto -7
  53: GETGLOBAL	R11 K14       ; R11 := table
  54: GETTABLE	R11 R11 RK271  ; R11 := R11["insert"]
  55: MOVE	R12 R4             ; R12 := R4
  56: MOVE	R13 R10            ; R13 := R10
  57: CALL	R11 3 1            ; R11 := R11(...) -- b=3, c=1
  58: TFORLOOP	R6 0 2         ; tforloop R6, R7 -- b=0, c=2
  59: JMP	-19                 ; goto -19
  60: SETTABLE	R1 RK266 R4    ; R1["capability"] := R4
  61: JMP	1                   ; goto 1
  62: LOADK	R0 K16            ; R0 := 1600
  63: EQ	R0 R256 0            ; if R0 == 0 then goto 0
  64: JMP	5                   ; goto 5
  65: GETUPVAL	R4 1           ; R4 := UpValue[1]
  66: GETTABLE	R4 R4 RK274    ; R4 := R4["getErrorMessage"]
  67: MOVE	R5 R0              ; R5 := R0
  68: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  69: SETTABLE	R1 RK273 R4    ; R1["msg"] := R4
  70: SETTABLE	R1 RK260 R0    ; R1["code"] := R0
  71: GETUPVAL	R4 2           ; R4 := UpValue[2]
  72: GETTABLE	R4 R4 RK275    ; R4 := R4["write_json"]
  73: MOVE	R5 R1              ; R5 := R1
  74: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  75: RETURN	R0 1             ; return R0

