-- Lua Bytecode Instructions
-- Generated by Relua

-- Chunk: lineDefined=0, lastLineDefined=0, numParams=0, isVararg=2, maxStackSize=20

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := module
   1: LOADK	R1 K1             ; R1 := "xiaoqiang.util.XQSecureUtil"
   2: GETGLOBAL	R2 K2         ; R2 := package
   3: GETTABLE	R2 R2 RK259    ; R2 := R2["seeall"]
   4: CALL	R0 3 1             ; R0 := R0(...) -- b=3, c=1
   5: GETGLOBAL	R0 K4         ; R0 := require
   6: LOADK	R1 K5             ; R1 := "luci.util"
   7: CALL	R0 2 1             ; R0 := R0(...) -- b=2, c=1
   8: GETGLOBAL	R0 K4         ; R0 := require
   9: LOADK	R1 K6             ; R1 := "luci.sys"
  10: CALL	R0 2 1             ; R0 := R0(...) -- b=2, c=1
  11: GETGLOBAL	R0 K4         ; R0 := require
  12: LOADK	R1 K7             ; R1 := "bit"
  13: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
  14: GETGLOBAL	R1 K4         ; R1 := require
  15: LOADK	R2 K8             ; R2 := "nixio"
  16: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  17: GETGLOBAL	R2 K4         ; R2 := require
  18: LOADK	R3 K9             ; R3 := "nixio.util"
  19: CALL	R2 2 1             ; R2 := R2(...) -- b=2, c=1
  20: GETGLOBAL	R2 K4         ; R2 := require
  21: LOADK	R3 K10            ; R3 := "nixio.fs"
  22: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  23: GETGLOBAL	R3 K4         ; R3 := require
  24: LOADK	R4 K11            ; R4 := "xiaoqiang.XQLog"
  25: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  26: GETGLOBAL	R4 K4         ; R4 := require
  27: LOADK	R5 K12            ; R5 := "xssFilter"
  28: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  29: GETTABLE	R4 R4 RK269    ; R4 := R4["new"]
  30: CALL	R4 1 2             ; R4 := R4(...) -- b=1, c=2
  31: GETGLOBAL	R5 K4         ; R5 := require
  32: LOADK	R6 K14            ; R6 := "xiaoqiang.common.XQFunction"
  33: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  34: GETGLOBAL	R6 K4         ; R6 := require
  35: LOADK	R7 K15            ; R7 := "xiaoqiang.XQPreference"
  36: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  37: GETGLOBAL	R7 K4         ; R7 := require
  38: LOADK	R8 K16            ; R8 := "xiaoqiang.util.XQCryptoUtil"
  39: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  40: LOADK	R8 K17            ; R8 := "a2ffa5c9be07488bbb04a3a47d3c5f6a"
  41: LOADK	R9 K18            ; R9 := "echo -e '%s' | openssl aes-128-cbc -d -K '%s' -iv '64175472480004614961023454661220' -base64"
  42: LOADK	R10 K19           ; R10 := "echo -e '%s' | /usr/bin/aes_crypt -b -d -k '%s' -i 64175472480004614961023454661220 -"
  43: LOADK	R11 K20           ; R11 := "/etc/tmp"
  44: LOADK	R12 K21           ; R12 := "/etc/tmp/luci-nonce"
  45: CLOSURE	R13 0           ; R13 := closure(0)
  46: SETGLOBAL	R13 K22       ; checkid := R13
  47: CLOSURE	R13 1           ; R13 := closure(1)
  48: MOVE	R0 R2              ; R0 := R2
  49: MOVE	R0 R11             ; R0 := R11
  50: MOVE	R0 R12             ; R0 := R12
  51: SETGLOBAL	R13 K23       ; prepare := R13
  52: CLOSURE	R13 2           ; R13 := closure(2)
  53: MOVE	R0 R2              ; R0 := R2
  54: MOVE	R0 R12             ; R0 := R12
  55: SETGLOBAL	R13 K24       ; sane := R13
  56: CLOSURE	R13 3           ; R13 := closure(3)
  57: MOVE	R0 R12             ; R0 := R12
  58: MOVE	R0 R2              ; R0 := R2
  59: SETGLOBAL	R13 K25       ; readNonce := R13
  60: CLOSURE	R13 4           ; R13 := closure(4)
  61: MOVE	R0 R1              ; R0 := R1
  62: MOVE	R0 R12             ; R0 := R12
  63: SETGLOBAL	R13 K26       ; writeNonce := R13
  64: CLOSURE	R13 5           ; R13 := closure(5)
  65: MOVE	R0 R5              ; R0 := R5
  66: MOVE	R0 R4              ; R0 := R4
  67: SETGLOBAL	R13 K27       ; xssCheck := R13
  68: CLOSURE	R13 6           ; R13 := closure(6)
  69: SETGLOBAL	R13 K28       ; generateRedirectKey := R13
  70: CLOSURE	R13 7           ; R13 := closure(7)
  71: MOVE	R0 R5              ; R0 := R5
  72: SETGLOBAL	R13 K29       ; checkRedirectKey := R13
  73: CLOSURE	R13 8           ; R13 := closure(8)
  74: MOVE	R0 R5              ; R0 := R5
  75: SETGLOBAL	R13 K30       ; ciphertextFormat := R13
  76: CLOSURE	R13 9           ; R13 := closure(9)
  77: MOVE	R0 R5              ; R0 := R5
  78: MOVE	R0 R6              ; R0 := R6
  79: MOVE	R0 R9              ; R0 := R9
  80: MOVE	R0 R10             ; R0 := R10
  81: SETGLOBAL	R13 K31       ; decCiphertext := R13
  82: CLOSURE	R13 10          ; R13 := closure(10)
  83: MOVE	R0 R5              ; R0 := R5
  84: MOVE	R0 R3              ; R0 := R3
  85: MOVE	R0 R7              ; R0 := R7
  86: MOVE	R0 R8              ; R0 := R8
  87: MOVE	R0 R6              ; R0 := R6
  88: SETGLOBAL	R13 K32       ; savePlaintextPwd := R13
  89: CLOSURE	R13 11          ; R13 := closure(11)
  90: MOVE	R0 R5              ; R0 := R5
  91: MOVE	R0 R7              ; R0 := R7
  92: MOVE	R0 R8              ; R0 := R8
  93: SETGLOBAL	R13 K33       ; savePlaintextPwdEx := R13
  94: CLOSURE	R13 12          ; R13 := closure(12)
  95: MOVE	R0 R5              ; R0 := R5
  96: MOVE	R0 R6              ; R0 := R6
  97: SETGLOBAL	R13 K34       ; saveCiphertextPwd := R13
  98: CLOSURE	R13 13          ; R13 := closure(13)
  99: MOVE	R0 R6              ; R0 := R6
 100: SETGLOBAL	R13 K35       ; saveCiphertextLegacyPwd := R13
 101: CLOSURE	R13 14          ; R13 := closure(14)
 102: MOVE	R0 R5              ; R0 := R5
 103: MOVE	R0 R6              ; R0 := R6
 104: MOVE	R0 R7              ; R0 := R7
 105: MOVE	R0 R8              ; R0 := R8
 106: SETGLOBAL	R13 K36       ; checkPlaintextPwd := R13
 107: CLOSURE	R13 15          ; R13 := closure(15)
 108: MOVE	R0 R5              ; R0 := R5
 109: MOVE	R0 R6              ; R0 := R6
 110: MOVE	R0 R7              ; R0 := R7
 111: MOVE	R0 R3              ; R0 := R3
 112: SETGLOBAL	R13 K37       ; checkUser := R13
 113: CLOSURE	R13 16          ; R13 := closure(16)
 114: MOVE	R0 R5              ; R0 := R5
 115: MOVE	R0 R3              ; R0 := R3
 116: SETGLOBAL	R13 K38       ; checkNonce := R13
 117: LOADK	R13 K39           ; R13 := "xiaoqiang-web"
 118: CLOSURE	R14 17          ; R14 := closure(17)
 119: MOVE	R0 R13             ; R0 := R13
 120: SETGLOBAL	R14 K40       ; passportLoginUrl := R14
 121: CLOSURE	R14 18          ; R14 := closure(18)
 122: MOVE	R0 R5              ; R0 := R5
 123: MOVE	R0 R13             ; R0 := R13
 124: SETGLOBAL	R14 K41       ; passportLogoutUrl := R14
 125: CLOSURE	R14 19          ; R14 := closure(19)
 126: MOVE	R0 R5              ; R0 := R5
 127: SETGLOBAL	R14 K42       ; checkStrong := R14
 128: NEWTABLE	R14            ; R14 := {}
 129: LOADK	R15 K44           ; R15 := "'"
 130: LOADK	R16 K45           ; R16 := ";"
 131: LOADK	R17 K46           ; R17 := "nvram"
 132: LOADK	R18 K47           ; R18 := "dropbear"
 133: LOADK	R19 K48           ; R19 := "bdata"
 134: SETLIST	R14 5 1         ; setlist R14, R5 -- b=5, c=1
 135: SETGLOBAL	R14 K43       ; KEY_WORDS := R14
 136: CLOSURE	R14 20          ; R14 := closure(20)
 137: MOVE	R0 R5              ; R0 := R5
 138: SETGLOBAL	R14 K49       ; _keyWordsFilter := R14
 139: CLOSURE	R14 21          ; R14 := closure(21)
 140: SETGLOBAL	R14 K50       ; cmdSafeCheck := R14
 141: LOADK	R14 K51           ; R14 := "[`;|$&
]"
 142: NEWTABLE	R15            ; R15 := {}
 143: SETTABLE	R15 RK308 R309 ; R15["name"] := 1
 144: SETTABLE	R15 RK310 R309 ; R15["password"] := 1
 145: SETTABLE	R15 RK311 R309 ; R15["password2g"] := 1
 146: SETTABLE	R15 RK312 R309 ; R15["password5g"] := 1
 147: SETTABLE	R15 RK313 R309 ; R15["password5g2"] := 1
 148: SETTABLE	R15 RK314 R309 ; R15["npassword"] := 1
 149: SETTABLE	R15 RK315 R309 ; R15["pppoeName"] := 1
 150: SETTABLE	R15 RK316 R309 ; R15["pppoePwd"] := 1
 151: SETTABLE	R15 RK317 R309 ; R15["pwd"] := 1
 152: SETTABLE	R15 RK318 R309 ; R15["pwd1"] := 1
 153: SETTABLE	R15 RK319 R309 ; R15["pwd2"] := 1
 154: SETTABLE	R15 RK320 R309 ; R15["pwd3"] := 1
 155: SETTABLE	R15 RK321 R309 ; R15["newPwd"] := 1
 156: SETTABLE	R15 RK322 R309 ; R15["service"] := 1
 157: SETTABLE	R15 RK323 R309 ; R15["ssid"] := 1
 158: SETTABLE	R15 RK324 R309 ; R15["ssid1"] := 1
 159: SETTABLE	R15 RK325 R309 ; R15["ssid2"] := 1
 160: SETTABLE	R15 RK326 R309 ; R15["ssid3"] := 1
 161: SETTABLE	R15 RK327 R309 ; R15["ssid2g"] := 1
 162: SETTABLE	R15 RK328 R309 ; R15["ssid5g"] := 1
 163: SETTABLE	R15 RK329 R309 ; R15["ssid5g2"] := 1
 164: SETTABLE	R15 RK330 R309 ; R15["nssid"] := 1
 165: SETTABLE	R15 RK331 R309 ; R15["nssid5G"] := 1
 166: SETTABLE	R15 RK332 R309 ; R15["nssid5G2"] := 1
 167: SETTABLE	R15 RK333 R309 ; R15["username"] := 1
 168: SETTABLE	R15 RK334 R309 ; R15["apn"] := 1
 169: SETTABLE	R15 RK335 R309 ; R15["pdp"] := 1
 170: SETTABLE	R15 RK336 R309 ; R15["user"] := 1
 171: SETTABLE	R15 RK337 R309 ; R15["passwd"] := 1
 172: SETTABLE	R15 RK338 R309 ; R15["contact_phone"] := 1
 173: SETTABLE	R15 RK339 R309 ; R15["phoneList"] := 1
 174: SETTABLE	R15 RK340 R309 ; R15["msgtext"] := 1
 175: SETTABLE	R15 RK341 R309 ; R15["acs_username"] := 1
 176: SETTABLE	R15 RK342 R309 ; R15["acs_password"] := 1
 177: SETTABLE	R15 RK343 R309 ; R15["conn_username"] := 1
 178: SETTABLE	R15 RK344 R309 ; R15["conn_password"] := 1
 179: CLOSURE	R16 22          ; R16 := closure(22)
 180: MOVE	R0 R15             ; R0 := R15
 181: MOVE	R0 R14             ; R0 := R14
 182: MOVE	R0 R3              ; R0 := R3
 183: SETGLOBAL	R16 K89       ; hackCheck := R16
 184: CLOSURE	R16 23          ; R16 := closure(23)
 185: MOVE	R0 R14             ; R0 := R14
 186: SETGLOBAL	R16 K90       ; hackCharsCheck := R16
 187: CLOSURE	R16 24          ; R16 := closure(24)
 188: MOVE	R0 R5              ; R0 := R5
 189: SETGLOBAL	R16 K91       ; parseCmdline := R16
 190: RETURN	R0 1             ; return R0

-- SubChunks:

-- SubChunk 1:
-- SubChunk: lineDefined=21, lastLineDefined=23, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: TEST	R0 0 0             ; if  R0 then goto 0
   1: JMP	9                   ; goto 9
   2: LEN	R1 R0               ; R1 := #R0
   3: LE	R256 R1 0            ; if 40 <= R1 then goto 0
   4: JMP	6                   ; goto 6
   5: SELF	R1 R0 R257         ; R1, R2 := R0, R257
   6: LOADK	R3 K2             ; R3 := "^[a-fA-F0-9]+$"
   7: CALL	R1 3 2             ; R1 := R1(...) -- b=3, c=2
   8: NOT	R1 R1               ; R1 := not R1
   9: NOT	R1 R1               ; R1 := not R1
  10: JMP	2                   ; goto 2
  11: LOADBOOL	R1 0 1         ; R1 := false
  12: LOADBOOL	R1 1 0         ; R1 := true
  13: RETURN	R1 2             ; return R1, R2
  14: RETURN	R0 1             ; return R0

-- SubChunk 2:
-- SubChunk: lineDefined=25, lastLineDefined=31, numParams=0, isVararg=0, maxStackSize=3

-- Register Operations:
   0: GETUPVAL	R0 0           ; R0 := UpValue[0]
   1: GETTABLE	R0 R0 RK256    ; R0 := R0["mkdir"]
   2: GETUPVAL	R1 1           ; R1 := UpValue[1]
   3: LOADK	R2 K1             ; R2 := 700
   4: CALL	R0 3 1             ; R0 := R0(...) -- b=3, c=1
   5: GETUPVAL	R0 0           ; R0 := UpValue[0]
   6: GETTABLE	R0 R0 RK256    ; R0 := R0["mkdir"]
   7: GETUPVAL	R1 2           ; R1 := UpValue[2]
   8: LOADK	R2 K1             ; R2 := 700
   9: CALL	R0 3 1             ; R0 := R0(...) -- b=3, c=1
  10: GETGLOBAL	R0 K2         ; R0 := sane
  11: CALL	R0 1 2             ; R0 := R0(...) -- b=1, c=2
  12: TEST	R0 1 0             ; if not R0 then goto 0
  13: JMP	3                   ; goto 3
  14: GETGLOBAL	R0 K3         ; R0 := error
  15: LOADK	R1 K4             ; R1 := "Security Exception: Nonce path is not sane!"
  16: CALL	R0 2 1             ; R0 := R0(...) -- b=2, c=1
  17: RETURN	R0 1             ; return R0

-- SubChunk 3:
-- SubChunk: lineDefined=33, lastLineDefined=38, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := luci
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["sys"]
   2: GETTABLE	R1 R1 RK258    ; R1 := R1["process"]
   3: GETTABLE	R1 R1 RK259    ; R1 := R1["info"]
   4: LOADK	R2 K4             ; R2 := "uid"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 RK261    ; R2 := R2["stat"]
   8: TESTSET	R3 R1 0 0       ; if R1 == false then R3 := R1; goto 0
   9: JMP	1                   ; goto 1
  10: GETUPVAL	R3 1           ; R3 := UpValue[1]
  11: LOADK	R4 K4             ; R4 := "uid"
  12: CALL	R2 3 2             ; R2 := R2(...) -- b=3, c=2
  13: EQ	R1 R2 0              ; if R1 == R2 then goto 0
  14: JMP	15                  ; goto 15
  15: GETUPVAL	R1 0           ; R1 := UpValue[0]
  16: GETTABLE	R1 R1 RK261    ; R1 := R1["stat"]
  17: TESTSET	R2 R1 0 0       ; if R1 == false then R2 := R1; goto 0
  18: JMP	1                   ; goto 1
  19: GETUPVAL	R2 1           ; R2 := UpValue[1]
  20: LOADK	R3 K6             ; R3 := "modestr"
  21: CALL	R1 3 2             ; R1 := R1(...) -- b=3, c=2
  22: TEST	R0 0 0             ; if  R0 then goto 0
  23: JMP	3                   ; goto 3
  24: LOADK	R2 K7             ; R2 := "rw-------"
  25: TEST	R2 1 0             ; if not R2 then goto 0
  26: JMP	1                   ; goto 1
  27: LOADK	R2 K8             ; R2 := "rwx------"
  28: EQ	R1 R2 0              ; if R1 == R2 then goto 0
  29: JMP	1                   ; goto 1
  30: LOADBOOL	R1 0 1         ; R1 := false
  31: LOADBOOL	R1 1 0         ; R1 := true
  32: RETURN	R1 2             ; return R1, R2
  33: RETURN	R0 1             ; return R0

-- SubChunk 4:
-- SubChunk: lineDefined=40, lastLineDefined=56, numParams=1, isVararg=0, maxStackSize=6

-- Register Operations:
   0: TEST	R0 0 0             ; if  R0 then goto 0
   1: JMP	5                   ; goto 5
   2: GETGLOBAL	R1 K0         ; R1 := checkid
   3: MOVE	R2 R0              ; R2 := R0
   4: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   5: TEST	R1 1 0             ; if not R1 then goto 0
   6: JMP	2                   ; goto 2
   7: LOADNIL	R1 R1           ; R1 := nil
   8: RETURN	R1 2             ; return R1, R2
   9: GETGLOBAL	R1 K1         ; R1 := sane
  10: GETUPVAL	R2 0           ; R2 := UpValue[0]
  11: LOADK	R3 K2             ; R3 := "/"
  12: MOVE	R4 R0              ; R4 := R0
  13: CONCAT	R2 R2 R4         ; R2 := R2 .. R4
  14: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  15: TEST	R1 1 0             ; if not R1 then goto 0
  16: JMP	2                   ; goto 2
  17: LOADNIL	R1 R1           ; R1 := nil
  18: RETURN	R1 2             ; return R1, R2
  19: GETUPVAL	R1 1           ; R1 := UpValue[1]
  20: GETTABLE	R1 R1 RK259    ; R1 := R1["readfile"]
  21: GETUPVAL	R2 0           ; R2 := UpValue[0]
  22: LOADK	R3 K2             ; R3 := "/"
  23: MOVE	R4 R0              ; R4 := R0
  24: CONCAT	R2 R2 R4         ; R2 := R2 .. R4
  25: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  26: GETGLOBAL	R2 K4         ; R2 := loadstring
  27: MOVE	R3 R1              ; R3 := R1
  28: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  29: GETGLOBAL	R3 K5         ; R3 := setfenv
  30: MOVE	R4 R2              ; R4 := R2
  31: NEWTABLE	R5             ; R5 := {}
  32: CALL	R3 3 1             ; R3 := R3(...) -- b=3, c=1
  33: MOVE	R3 R2              ; R3 := R2
  34: CALL	R3 1 2             ; R3 := R3(...) -- b=1, c=2
  35: GETGLOBAL	R4 K6         ; R4 := type
  36: MOVE	R5 R3              ; R5 := R3
  37: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  38: EQ	R4 R263 0            ; if R4 == "table" then goto 0
  39: JMP	2                   ; goto 2
  40: LOADNIL	R4 R4           ; R4 := nil
  41: RETURN	R4 2             ; return R4, R5
  42: RETURN	R3 2             ; return R3, R4
  43: RETURN	R0 1             ; return R0

-- SubChunk 5:
-- SubChunk: lineDefined=58, lastLineDefined=69, numParams=2, isVararg=0, maxStackSize=6

-- Register Operations:
   0: GETGLOBAL	R2 K0         ; R2 := sane
   1: CALL	R2 1 2             ; R2 := R2(...) -- b=1, c=2
   2: TEST	R2 1 0             ; if not R2 then goto 0
   3: JMP	2                   ; goto 2
   4: GETGLOBAL	R2 K1         ; R2 := prepare
   5: CALL	R2 1 1             ; R2 := R2(...) -- b=1, c=1
   6: GETGLOBAL	R2 K2         ; R2 := checkid
   7: MOVE	R3 R0              ; R3 := R0
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: TEST	R2 0 0             ; if  R2 then goto 0
  10: JMP	5                   ; goto 5
  11: GETGLOBAL	R2 K3         ; R2 := type
  12: MOVE	R3 R1              ; R3 := R1
  13: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  14: EQ	R2 R260 0            ; if R2 == "table" then goto 0
  15: JMP	1                   ; goto 1
  16: RETURN	R0 1             ; return R0
  17: GETGLOBAL	R2 K5         ; R2 := luci
  18: GETTABLE	R2 R2 RK262    ; R2 := R2["util"]
  19: GETTABLE	R2 R2 RK263    ; R2 := R2["get_bytecode"]
  20: MOVE	R3 R1              ; R3 := R1
  21: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  22: MOVE	R1 R2              ; R1 := R2
  23: GETUPVAL	R2 0           ; R2 := UpValue[0]
  24: GETTABLE	R2 R2 RK264    ; R2 := R2["open"]
  25: GETUPVAL	R3 1           ; R3 := UpValue[1]
  26: LOADK	R4 K9             ; R4 := "/"
  27: MOVE	R5 R0              ; R5 := R0
  28: CONCAT	R3 R3 R5         ; R3 := R3 .. R5
  29: LOADK	R4 K10            ; R4 := "w"
  30: LOADK	R5 K11            ; R5 := 600
  31: CALL	R2 4 2             ; R2 := R2(...) -- b=4, c=2
  32: SELF	R3 R2 R268         ; R3, R4 := R2, R268
  33: MOVE	R5 R1              ; R5 := R1
  34: CALL	R3 3 1             ; R3 := R3(...) -- b=3, c=1
  35: SELF	R3 R2 R269         ; R3, R4 := R2, R269
  36: CALL	R3 2 1             ; R3 := R3(...) -- b=2, c=1
  37: RETURN	R0 1             ; return R0

-- SubChunk 6:
-- SubChunk: lineDefined=71, lastLineDefined=87, numParams=1, isVararg=0, maxStackSize=8

-- Register Operations:
   0: GETUPVAL	R1 0           ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 RK256    ; R1 := R1["isStrNil"]
   2: MOVE	R2 R0              ; R2 := R0
   3: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   4: TEST	R1 0 0             ; if  R1 then goto 0
   5: JMP	1                   ; goto 1
   6: RETURN	R0 2             ; return R0, R1
   7: GETGLOBAL	R1 K1         ; R1 := type
   8: MOVE	R2 R0              ; R2 := R0
   9: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  10: EQ	R1 R258 0            ; if R1 == "string" then goto 0
  11: JMP	20                  ; goto 20
  12: GETUPVAL	R1 1           ; R1 := UpValue[1]
  13: SELF	R1 R1 R259         ; R1, R2 := R1, R259
  14: MOVE	R3 R0              ; R3 := R0
  15: CALL	R1 3 3             ; R1 := R1(...) -- b=3, c=3
  16: TEST	R1 0 0             ; if  R1 then goto 0
  17: JMP	2                   ; goto 2
  18: RETURN	R1 2             ; return R1, R2
  19: JMP	13                  ; goto 13
  20: GETGLOBAL	R3 K4         ; R3 := require
  21: LOADK	R4 K5             ; R4 := "xiaoqiang.XQLog"
  22: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  23: GETTABLE	R4 R3 RK262    ; R4 := R3["log"]
  24: LOADK	R5 K7             ; R5 := 4
  25: LOADK	R6 K8             ; R6 := "XSS Warning:"
  26: MOVE	R7 R0              ; R7 := R0
  27: CONCAT	R6 R6 R7         ; R6 := R6 .. R7
  28: CALL	R4 3 1             ; R4 := R4(...) -- b=3, c=1
  29: LOADNIL	R4 R4           ; R4 := nil
  30: RETURN	R4 2             ; return R4, R5
  31: JMP	1                   ; goto 1
  32: RETURN	R0 2             ; return R0, R1
  33: RETURN	R0 1             ; return R0

-- SubChunk 7:
-- SubChunk: lineDefined=89, lastLineDefined=97, numParams=1, isVararg=0, maxStackSize=8

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := require
   1: LOADK	R2 K1             ; R2 := "luci.sys"
   2: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   3: GETGLOBAL	R2 K0         ; R2 := require
   4: LOADK	R3 K2             ; R3 := "luci.sauth"
   5: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   6: NEWTABLE	R3             ; R3 := {}
   7: GETTABLE	R4 R1 RK259    ; R4 := R1["uniqueid"]
   8: LOADK	R5 K4             ; R5 := 16
   9: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  10: GETGLOBAL	R5 K6         ; R5 := tostring
  11: MOVE	R6 R0              ; R6 := R0
  12: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  13: SETTABLE	R3 RK261 R5    ; R3["type"] := R5
  14: GETTABLE	R5 R2 RK263    ; R5 := R2["write"]
  15: MOVE	R6 R4              ; R6 := R4
  16: MOVE	R7 R3              ; R7 := R3
  17: CALL	R5 3 1             ; R5 := R5(...) -- b=3, c=1
  18: RETURN	R4 2             ; return R4, R5
  19: RETURN	R0 1             ; return R0

-- SubChunk 8:
-- SubChunk: lineDefined=99, lastLineDefined=116, numParams=1, isVararg=0, maxStackSize=7

-- Register Operations:
   0: GETUPVAL	R1 0           ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 RK256    ; R1 := R1["isStrNil"]
   2: MOVE	R2 R0              ; R2 := R0
   3: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   4: TEST	R1 0 0             ; if  R1 then goto 0
   5: JMP	2                   ; goto 2
   6: LOADBOOL	R1 0 0         ; R1 := false
   7: RETURN	R1 2             ; return R1, R2
   8: GETGLOBAL	R1 K1         ; R1 := require
   9: LOADK	R2 K2             ; R2 := "luci.sys"
  10: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  11: GETGLOBAL	R2 K1         ; R2 := require
  12: LOADK	R3 K3             ; R3 := "luci.sauth"
  13: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  14: GETTABLE	R3 R2 RK260    ; R3 := R2["read"]
  15: MOVE	R4 R0              ; R4 := R0
  16: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  17: TEST	R3 0 0             ; if  R3 then goto 0
  18: JMP	21                  ; goto 21
  19: GETGLOBAL	R4 K5         ; R4 := type
  20: MOVE	R5 R3              ; R5 := R3
  21: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  22: EQ	R4 R262 0            ; if R4 == "table" then goto 0
  23: JMP	16                  ; goto 16
  24: GETTABLE	R4 R2 RK263    ; R4 := R2["kill"]
  25: MOVE	R5 R0              ; R5 := R0
  26: CALL	R4 2 1             ; R4 := R4(...) -- b=2, c=1
  27: GETTABLE	R4 R1 RK264    ; R4 := R1["uptime"]
  28: CALL	R4 1 2             ; R4 := R4(...) -- b=1, c=2
  29: GETTABLE	R5 R3 RK265    ; R5 := R3["atime"]
  30: SUB	R5 R4 R5            ; R5 := R4 - R5
  31: LT	R266 R5 0            ; if 10 < R5 then goto 0
  32: JMP	3                   ; goto 3
  33: LOADBOOL	R5 0 0         ; R5 := false
  34: RETURN	R5 2             ; return R5, R6
  35: JMP	4                   ; goto 4
  36: GETGLOBAL	R5 K11        ; R5 := tostring
  37: GETTABLE	R6 R3 RK261    ; R6 := R3["type"]
  38: TAILCALL	R5 2 0         ; tailcall R5(...) -- b=2, c=0
  39: RETURN	R5 0             ; return
  40: LOADBOOL	R4 0 0         ; R4 := false
  41: RETURN	R4 2             ; return R4, R5
  42: RETURN	R0 1             ; return R0

-- SubChunk 9:
-- SubChunk: lineDefined=118, lastLineDefined=132, numParams=1, isVararg=0, maxStackSize=13

-- Register Operations:
   0: GETUPVAL	R1 0           ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 RK256    ; R1 := R1["isStrNil"]
   2: MOVE	R2 R0              ; R2 := R0
   3: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   4: TEST	R1 0 0             ; if  R1 then goto 0
   5: JMP	2                   ; goto 2
   6: LOADK	R1 K1             ; R1 := ""
   7: RETURN	R1 2             ; return R1, R2
   8: GETGLOBAL	R1 K2         ; R1 := math
   9: GETTABLE	R1 R1 RK259    ; R1 := R1["ceil"]
  10: LEN	R2 R0               ; R2 := #R0
  11: DIV	R2 R2 R260          ; R2 := R2 / R260
  12: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  13: NEWTABLE	R2             ; R2 := {}
  14: LOADK	R3 K5             ; R3 := 1
  15: MOVE	R4 R1              ; R4 := R1
  16: LOADK	R5 K5             ; R5 := 1
  17: FORPREP	R3 0            ; forprep R3, R4, R5, R6 -- sBx=0
  18: EQ	R6 R1 0              ; if R6 == R1 then goto 0
  19: JMP	13                  ; goto 13
  20: GETGLOBAL	R7 K6         ; R7 := table
  21: GETTABLE	R7 R7 RK263    ; R7 := R7["insert"]
  22: MOVE	R8 R2              ; R8 := R2
  23: GETGLOBAL	R9 K8         ; R9 := string
  24: GETTABLE	R9 R9 RK265    ; R9 := R9["sub"]
  25: MOVE	R10 R0             ; R10 := R0
  26: SUB	R11 R6 R261         ; R11 := R6 - R261
  27: MUL	R11 R11 R260        ; R11 := R11 * R260
  28: ADD	R11 R261 R11        ; R11 := R261 + R11
  29: MUL	R12 R260 R6         ; R12 := R260 * R6
  30: CALL	R9 4 0             ; R9 := R9(...) -- b=4, c=0
  31: CALL	R7 0 1             ; R7 := R7(...) -- b=0, c=1
  32: JMP	12                  ; goto 12
  33: GETGLOBAL	R7 K6         ; R7 := table
  34: GETTABLE	R7 R7 RK263    ; R7 := R7["insert"]
  35: MOVE	R8 R2              ; R8 := R2
  36: GETGLOBAL	R9 K8         ; R9 := string
  37: GETTABLE	R9 R9 RK265    ; R9 := R9["sub"]
  38: MOVE	R10 R0             ; R10 := R0
  39: SUB	R11 R6 R261         ; R11 := R6 - R261
  40: MUL	R11 R11 R260        ; R11 := R11 * R260
  41: ADD	R11 R261 R11        ; R11 := R261 + R11
  42: LOADK	R12 K10           ; R12 := -1
  43: CALL	R9 4 0             ; R9 := R9(...) -- b=4, c=0
  44: CALL	R7 0 1             ; R7 := R7(...) -- b=0, c=1
  45: FORLOOP	R3 0            ; forloop R3, R4, R5, R6 -- sBx=0
  46: GETGLOBAL	R3 K6         ; R3 := table
  47: GETTABLE	R3 R3 RK267    ; R3 := R3["concat"]
  48: MOVE	R4 R2              ; R4 := R2
  49: LOADK	R5 K12            ; R5 := "\n"
  50: TAILCALL	R3 3 0         ; tailcall R3(...) -- b=3, c=0
  51: RETURN	R3 0             ; return
  52: RETURN	R0 1             ; return R0

-- SubChunk 10:
-- SubChunk: lineDefined=134, lastLineDefined=151, numParams=3, isVararg=0, maxStackSize=9

-- Register Operations:
   0: GETUPVAL	R3 0           ; R3 := UpValue[0]
   1: GETTABLE	R3 R3 RK256    ; R3 := R3["isStrNil"]
   2: MOVE	R4 R1              ; R4 := R1
   3: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
   4: TEST	R3 1 0             ; if not R3 then goto 0
   5: JMP	15                  ; goto 15
   6: SELF	R3 R1 R257         ; R3, R4 := R1, R257
   7: LOADK	R5 K2             ; R5 := """
   8: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
   9: TEST	R3 1 0             ; if not R3 then goto 0
  10: JMP	10                  ; goto 10
  11: SELF	R3 R1 R257         ; R3, R4 := R1, R257
  12: LOADK	R5 K3             ; R5 := " "
  13: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  14: TEST	R3 1 0             ; if not R3 then goto 0
  15: JMP	5                   ; goto 5
  16: SELF	R3 R1 R257         ; R3, R4 := R1, R257
  17: LOADK	R5 K4             ; R5 := "'"
  18: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  19: TEST	R3 0 0             ; if  R3 then goto 0
  20: JMP	2                   ; goto 2
  21: LOADNIL	R3 R3           ; R3 := nil
  22: RETURN	R3 2             ; return R3, R4
  23: GETUPVAL	R3 1           ; R3 := UpValue[1]
  24: GETTABLE	R3 R3 RK261    ; R3 := R3["get_ext"]
  25: MOVE	R4 R0              ; R4 := R0
  26: LOADK	R5 K6             ; R5 := ""
  27: LOADK	R6 K7             ; R6 := "account"
  28: MOVE	R7 R2              ; R7 := R2
  29: CALL	R3 5 2             ; R3 := R3(...) -- b=5, c=2
  30: GETGLOBAL	R4 K8         ; R4 := string
  31: GETTABLE	R4 R4 RK265    ; R4 := R4["format"]
  32: GETUPVAL	R5 2           ; R5 := UpValue[2]
  33: GETGLOBAL	R6 K10        ; R6 := ciphertextFormat
  34: MOVE	R7 R1              ; R7 := R1
  35: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  36: MOVE	R7 R3              ; R7 := R3
  37: CALL	R4 4 2             ; R4 := R4(...) -- b=4, c=2
  38: GETGLOBAL	R5 K8         ; R5 := string
  39: GETTABLE	R5 R5 RK265    ; R5 := R5["format"]
  40: GETUPVAL	R6 3           ; R6 := UpValue[3]
  41: MOVE	R7 R1              ; R7 := R1
  42: MOVE	R8 R3              ; R8 := R3
  43: CALL	R5 4 2             ; R5 := R5(...) -- b=4, c=2
  44: GETGLOBAL	R6 K11        ; R6 := os
  45: GETTABLE	R6 R6 RK268    ; R6 := R6["execute"]
  46: MOVE	R7 R4              ; R7 := R4
  47: LOADK	R8 K13            ; R8 := "> /dev/null"
  48: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  49: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  50: EQ	R6 R270 0            ; if R6 == 0 then goto 0
  51: JMP	11                  ; goto 11
  52: GETGLOBAL	R6 K15        ; R6 := luci
  53: GETTABLE	R6 R6 RK272    ; R6 := R6["util"]
  54: GETTABLE	R6 R6 RK273    ; R6 := R6["trim"]
  55: GETGLOBAL	R7 K15        ; R7 := luci
  56: GETTABLE	R7 R7 RK272    ; R7 := R7["util"]
  57: GETTABLE	R7 R7 RK274    ; R7 := R7["exec"]
  58: MOVE	R8 R4              ; R8 := R4
  59: CALL	R7 2 0             ; R7 := R7(...) -- b=2, c=0
  60: TAILCALL	R6 0 0         ; tailcall R6(...) -- b=0, c=0
  61: RETURN	R6 0             ; return
  62: JMP	18                  ; goto 18
  63: GETGLOBAL	R6 K11        ; R6 := os
  64: GETTABLE	R6 R6 RK268    ; R6 := R6["execute"]
  65: MOVE	R7 R5              ; R7 := R5
  66: LOADK	R8 K13            ; R8 := "> /dev/null"
  67: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  68: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  69: EQ	R6 R270 0            ; if R6 == 0 then goto 0
  70: JMP	10                  ; goto 10
  71: GETGLOBAL	R6 K15        ; R6 := luci
  72: GETTABLE	R6 R6 RK272    ; R6 := R6["util"]
  73: GETTABLE	R6 R6 RK273    ; R6 := R6["trim"]
  74: GETGLOBAL	R7 K15        ; R7 := luci
  75: GETTABLE	R7 R7 RK272    ; R7 := R7["util"]
  76: GETTABLE	R7 R7 RK274    ; R7 := R7["exec"]
  77: MOVE	R8 R5              ; R8 := R5
  78: CALL	R7 2 0             ; R7 := R7(...) -- b=2, c=0
  79: TAILCALL	R6 0 0         ; tailcall R6(...) -- b=0, c=0
  80: RETURN	R6 0             ; return
  81: LOADNIL	R6 R6           ; R6 := nil
  82: RETURN	R6 2             ; return R6, R7
  83: RETURN	R0 1             ; return R0

-- SubChunk 11:
-- SubChunk: lineDefined=153, lastLineDefined=173, numParams=2, isVararg=0, maxStackSize=10

-- Register Operations:
   0: GETUPVAL	R2 0           ; R2 := UpValue[0]
   1: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   2: MOVE	R3 R0              ; R3 := R0
   3: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   4: TEST	R2 1 0             ; if not R2 then goto 0
   5: JMP	6                   ; goto 6
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   8: MOVE	R3 R1              ; R3 := R1
   9: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  10: TEST	R2 0 0             ; if  R2 then goto 0
  11: JMP	2                   ; goto 2
  12: LOADBOOL	R2 0 0         ; R2 := false
  13: RETURN	R2 2             ; return R2, R3
  14: GETGLOBAL	R2 K1         ; R2 := require
  15: LOADK	R3 K2             ; R3 := "xiaoqiang.util.XQSysUtil"
  16: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  17: GETTABLE	R3 R2 RK259    ; R3 := R2["getEncryptMode"]
  18: CALL	R3 1 2             ; R3 := R3(...) -- b=1, c=2
  19: LOADNIL	R4 R4           ; R4 := nil
  20: GETUPVAL	R5 1           ; R5 := UpValue[1]
  21: GETTABLE	R5 R5 RK260    ; R5 := R5["log"]
  22: LOADK	R6 K5             ; R6 := 4
  23: LOADK	R7 K6             ; R7 := "change pwd to "
  24: GETGLOBAL	R8 K7         ; R8 := tostring
  25: MOVE	R9 R1              ; R9 := R1
  26: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  27: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  28: CALL	R5 3 1             ; R5 := R5(...) -- b=3, c=1
  29: EQ	R3 R264 0            ; if R3 == 1 then goto 0
  30: JMP	22                  ; goto 22
  31: GETUPVAL	R5 2           ; R5 := UpValue[2]
  32: GETTABLE	R5 R5 RK265    ; R5 := R5["sha1"]
  33: MOVE	R6 R1              ; R6 := R1
  34: GETUPVAL	R7 3           ; R7 := UpValue[3]
  35: CONCAT	R6 R6 R7         ; R6 := R6 .. R7
  36: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  37: MOVE	R4 R5              ; R4 := R5
  38: GETUPVAL	R5 4           ; R5 := UpValue[4]
  39: GETTABLE	R5 R5 RK266    ; R5 := R5["set_ext"]
  40: MOVE	R6 R0              ; R6 := R0
  41: MOVE	R7 R4              ; R7 := R4
  42: LOADK	R8 K11            ; R8 := "account"
  43: LOADK	R9 K12            ; R9 := "legacy"
  44: CALL	R5 5 1             ; R5 := R5(...) -- b=5, c=1
  45: GETUPVAL	R5 2           ; R5 := UpValue[2]
  46: GETTABLE	R5 R5 RK269    ; R5 := R5["sha256"]
  47: MOVE	R6 R1              ; R6 := R1
  48: GETUPVAL	R7 3           ; R7 := UpValue[3]
  49: CONCAT	R6 R6 R7         ; R6 := R6 .. R7
  50: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  51: MOVE	R4 R5              ; R4 := R5
  52: JMP	7                   ; goto 7
  53: GETUPVAL	R5 2           ; R5 := UpValue[2]
  54: GETTABLE	R5 R5 RK265    ; R5 := R5["sha1"]
  55: MOVE	R6 R1              ; R6 := R1
  56: GETUPVAL	R7 3           ; R7 := UpValue[3]
  57: CONCAT	R6 R6 R7         ; R6 := R6 .. R7
  58: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  59: MOVE	R4 R5              ; R4 := R5
  60: GETUPVAL	R5 4           ; R5 := UpValue[4]
  61: GETTABLE	R5 R5 RK270    ; R5 := R5["set"]
  62: MOVE	R6 R0              ; R6 := R0
  63: MOVE	R7 R4              ; R7 := R4
  64: LOADK	R8 K11            ; R8 := "account"
  65: CALL	R5 4 1             ; R5 := R5(...) -- b=4, c=1
  66: GETUPVAL	R5 0           ; R5 := UpValue[0]
  67: GETTABLE	R5 R5 RK271    ; R5 := R5["forkExec"]
  68: LOADK	R6 K16            ; R6 := "/sbin/whc_to_re_common_api.sh webpasswd_update"
  69: CALL	R5 2 1             ; R5 := R5(...) -- b=2, c=1
  70: LOADBOOL	R5 1 0         ; R5 := true
  71: RETURN	R5 2             ; return R5, R6
  72: RETURN	R0 1             ; return R0

-- SubChunk 12:
-- SubChunk: lineDefined=175, lastLineDefined=195, numParams=2, isVararg=0, maxStackSize=13

-- Register Operations:
   0: GETUPVAL	R2 0           ; R2 := UpValue[0]
   1: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   2: MOVE	R3 R0              ; R3 := R0
   3: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   4: TEST	R2 1 0             ; if not R2 then goto 0
   5: JMP	6                   ; goto 6
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   8: MOVE	R3 R1              ; R3 := R1
   9: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  10: TEST	R2 0 0             ; if  R2 then goto 0
  11: JMP	2                   ; goto 2
  12: LOADBOOL	R2 0 0         ; R2 := false
  13: RETURN	R2 2             ; return R2, R3
  14: GETGLOBAL	R2 K1         ; R2 := require
  15: LOADK	R3 K2             ; R3 := "luci.model.uci"
  16: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  17: GETTABLE	R2 R2 RK259    ; R2 := R2["cursor"]
  18: CALL	R2 1 2             ; R2 := R2(...) -- b=1, c=2
  19: GETGLOBAL	R3 K1         ; R3 := require
  20: LOADK	R4 K4             ; R4 := "xiaoqiang.util.XQSysUtil"
  21: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
  22: GETTABLE	R4 R3 RK261    ; R4 := R3["getEncryptMode"]
  23: CALL	R4 1 2             ; R4 := R4(...) -- b=1, c=2
  24: GETUPVAL	R5 1           ; R5 := UpValue[1]
  25: GETTABLE	R5 R5 RK262    ; R5 := R5["sha1"]
  26: MOVE	R6 R1              ; R6 := R1
  27: GETUPVAL	R7 2           ; R7 := UpValue[2]
  28: CONCAT	R6 R6 R7         ; R6 := R6 .. R7
  29: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  30: EQ	R4 R263 0            ; if R4 == 1 then goto 0
  31: JMP	19                  ; goto 19
  32: GETUPVAL	R6 1           ; R6 := UpValue[1]
  33: GETTABLE	R6 R6 RK264    ; R6 := R6["sha256"]
  34: MOVE	R7 R1              ; R7 := R1
  35: GETUPVAL	R8 2           ; R8 := UpValue[2]
  36: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  37: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  38: SELF	R7 R2 R265         ; R7, R8 := R2, R265
  39: LOADK	R9 K10            ; R9 := "account"
  40: LOADK	R10 K11           ; R10 := "common"
  41: MOVE	R11 R0             ; R11 := R0
  42: MOVE	R12 R6             ; R12 := R6
  43: CALL	R7 6 1             ; R7 := R7(...) -- b=6, c=1
  44: SELF	R7 R2 R265         ; R7, R8 := R2, R265
  45: LOADK	R9 K10            ; R9 := "account"
  46: LOADK	R10 K12           ; R10 := "legacy"
  47: MOVE	R11 R0             ; R11 := R0
  48: MOVE	R12 R5             ; R12 := R5
  49: CALL	R7 6 1             ; R7 := R7(...) -- b=6, c=1
  50: JMP	6                   ; goto 6
  51: SELF	R6 R2 R265         ; R6, R7 := R2, R265
  52: LOADK	R8 K10            ; R8 := "account"
  53: LOADK	R9 K11            ; R9 := "common"
  54: MOVE	R10 R0             ; R10 := R0
  55: MOVE	R11 R5             ; R11 := R5
  56: CALL	R6 6 1             ; R6 := R6(...) -- b=6, c=1
  57: SELF	R6 R2 R269         ; R6, R7 := R2, R269
  58: LOADK	R8 K10            ; R8 := "account"
  59: CALL	R6 3 1             ; R6 := R6(...) -- b=3, c=1
  60: LOADBOOL	R6 1 0         ; R6 := true
  61: RETURN	R6 2             ; return R6, R7
  62: RETURN	R0 1             ; return R0

-- SubChunk 13:
-- SubChunk: lineDefined=197, lastLineDefined=207, numParams=2, isVararg=0, maxStackSize=7

-- Register Operations:
   0: GETUPVAL	R2 0           ; R2 := UpValue[0]
   1: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   2: MOVE	R3 R0              ; R3 := R0
   3: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   4: TEST	R2 1 0             ; if not R2 then goto 0
   5: JMP	6                   ; goto 6
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   8: MOVE	R3 R1              ; R3 := R1
   9: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  10: TEST	R2 0 0             ; if  R2 then goto 0
  11: JMP	2                   ; goto 2
  12: LOADBOOL	R2 0 0         ; R2 := false
  13: RETURN	R2 2             ; return R2, R3
  14: GETGLOBAL	R2 K1         ; R2 := decCiphertext
  15: MOVE	R3 R0              ; R3 := R0
  16: MOVE	R4 R1              ; R4 := R1
  17: CALL	R2 3 2             ; R2 := R2(...) -- b=3, c=2
  18: TEST	R2 0 0             ; if  R2 then goto 0
  19: JMP	8                   ; goto 8
  20: GETUPVAL	R3 1           ; R3 := UpValue[1]
  21: GETTABLE	R3 R3 RK258    ; R3 := R3["set"]
  22: MOVE	R4 R0              ; R4 := R0
  23: MOVE	R5 R2              ; R5 := R2
  24: LOADK	R6 K3             ; R6 := "account"
  25: CALL	R3 4 1             ; R3 := R3(...) -- b=4, c=1
  26: LOADBOOL	R3 1 0         ; R3 := true
  27: RETURN	R3 2             ; return R3, R4
  28: LOADBOOL	R3 0 0         ; R3 := false
  29: RETURN	R3 2             ; return R3, R4
  30: RETURN	R0 1             ; return R0

-- SubChunk 14:
-- SubChunk: lineDefined=209, lastLineDefined=220, numParams=2, isVararg=0, maxStackSize=9

-- Register Operations:
   0: GETGLOBAL	R2 K0         ; R2 := require
   1: LOADK	R3 K1             ; R3 := "xiaoqiang.common.XQFunction"
   2: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   3: GETTABLE	R3 R2 RK258    ; R3 := R2["isStrNil"]
   4: MOVE	R4 R1              ; R4 := R1
   5: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
   6: TEST	R3 0 0             ; if  R3 then goto 0
   7: JMP	2                   ; goto 2
   8: LOADBOOL	R3 1 0         ; R3 := true
   9: RETURN	R3 2             ; return R3, R4
  10: GETGLOBAL	R3 K3         ; R3 := decCiphertext
  11: MOVE	R4 R0              ; R4 := R0
  12: MOVE	R5 R1              ; R5 := R1
  13: LOADK	R6 K4             ; R6 := "legacy"
  14: CALL	R3 4 2             ; R3 := R3(...) -- b=4, c=2
  15: TEST	R3 0 0             ; if  R3 then goto 0
  16: JMP	9                   ; goto 9
  17: GETUPVAL	R4 0           ; R4 := UpValue[0]
  18: GETTABLE	R4 R4 RK261    ; R4 := R4["set_ext"]
  19: MOVE	R5 R0              ; R5 := R0
  20: MOVE	R6 R3              ; R6 := R3
  21: LOADK	R7 K6             ; R7 := "account"
  22: LOADK	R8 K4             ; R8 := "legacy"
  23: CALL	R4 5 1             ; R4 := R4(...) -- b=5, c=1
  24: LOADBOOL	R4 1 0         ; R4 := true
  25: RETURN	R4 2             ; return R4, R5
  26: LOADBOOL	R4 0 0         ; R4 := false
  27: RETURN	R4 2             ; return R4, R5
  28: RETURN	R0 1             ; return R0

-- SubChunk 15:
-- SubChunk: lineDefined=223, lastLineDefined=243, numParams=2, isVararg=0, maxStackSize=9

-- Register Operations:
   0: GETUPVAL	R2 0           ; R2 := UpValue[0]
   1: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   2: MOVE	R3 R0              ; R3 := R0
   3: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   4: TEST	R2 1 0             ; if not R2 then goto 0
   5: JMP	6                   ; goto 6
   6: GETUPVAL	R2 0           ; R2 := UpValue[0]
   7: GETTABLE	R2 R2 RK256    ; R2 := R2["isStrNil"]
   8: MOVE	R3 R1              ; R3 := R1
   9: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  10: TEST	R2 0 0             ; if  R2 then goto 0
  11: JMP	2                   ; goto 2
  12: LOADBOOL	R2 0 0         ; R2 := false
  13: RETURN	R2 2             ; return R2, R3
  14: GETGLOBAL	R2 K1         ; R2 := require
  15: LOADK	R3 K2             ; R3 := "xiaoqiang.util.XQSysUtil"
  16: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
  17: GETTABLE	R3 R2 RK259    ; R3 := R2["getEncryptMode"]
  18: CALL	R3 1 2             ; R3 := R3(...) -- b=1, c=2
  19: GETUPVAL	R4 1           ; R4 := UpValue[1]
  20: GETTABLE	R4 R4 RK260    ; R4 := R4["get"]
  21: MOVE	R5 R0              ; R5 := R0
  22: LOADK	R6 K5             ; R6 := ""
  23: LOADK	R7 K6             ; R7 := "account"
  24: CALL	R4 4 2             ; R4 := R4(...) -- b=4, c=2
  25: LOADNIL	R5 R5           ; R5 := nil
  26: EQ	R3 R263 0            ; if R3 == 1 then goto 0
  27: JMP	8                   ; goto 8
  28: GETUPVAL	R6 2           ; R6 := UpValue[2]
  29: GETTABLE	R6 R6 RK264    ; R6 := R6["sha256"]
  30: MOVE	R7 R1              ; R7 := R1
  31: GETUPVAL	R8 3           ; R8 := UpValue[3]
  32: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  33: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  34: MOVE	R5 R6              ; R5 := R6
  35: JMP	7                   ; goto 7
  36: GETUPVAL	R6 2           ; R6 := UpValue[2]
  37: GETTABLE	R6 R6 RK265    ; R6 := R6["sha1"]
  38: MOVE	R7 R1              ; R7 := R1
  39: GETUPVAL	R8 3           ; R8 := UpValue[3]
  40: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  41: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  42: MOVE	R5 R6              ; R5 := R6
  43: EQ	R4 R5 0              ; if R4 == R5 then goto 0
  44: JMP	3                   ; goto 3
  45: LOADBOOL	R6 1 0         ; R6 := true
  46: RETURN	R6 2             ; return R6, R7
  47: JMP	2                   ; goto 2
  48: LOADBOOL	R6 0 0         ; R6 := false
  49: RETURN	R6 2             ; return R6, R7
  50: RETURN	R0 1             ; return R0

-- SubChunk 16:
-- SubChunk: lineDefined=245, lastLineDefined=266, numParams=3, isVararg=0, maxStackSize=12

-- Register Operations:
   0: GETGLOBAL	R3 K0         ; R3 := require
   1: LOADK	R4 K1             ; R4 := "xiaoqiang.util.XQSysUtil"
   2: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
   3: GETTABLE	R4 R3 RK258    ; R4 := R3["getEncryptMode"]
   4: CALL	R4 1 2             ; R4 := R4(...) -- b=1, c=2
   5: GETUPVAL	R5 0           ; R5 := UpValue[0]
   6: GETTABLE	R5 R5 RK259    ; R5 := R5["isStrNil"]
   7: MOVE	R6 R0              ; R6 := R0
   8: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
   9: TEST	R5 0 0             ; if  R5 then goto 0
  10: JMP	2                   ; goto 2
  11: LOADBOOL	R5 0 0         ; R5 := false
  12: RETURN	R5 2             ; return R5, R6
  13: GETUPVAL	R5 1           ; R5 := UpValue[1]
  14: GETTABLE	R5 R5 RK260    ; R5 := R5["get"]
  15: MOVE	R6 R0              ; R6 := R0
  16: LOADNIL	R7 R7           ; R7 := nil
  17: LOADK	R8 K5             ; R8 := "account"
  18: CALL	R5 4 2             ; R5 := R5(...) -- b=4, c=2
  19: TEST	R5 0 0             ; if  R5 then goto 0
  20: JMP	35                  ; goto 35
  21: GETUPVAL	R6 0           ; R6 := UpValue[0]
  22: GETTABLE	R6 R6 RK259    ; R6 := R6["isStrNil"]
  23: MOVE	R7 R2              ; R7 := R2
  24: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  25: TEST	R6 1 0             ; if not R6 then goto 0
  26: JMP	29                  ; goto 29
  27: GETUPVAL	R6 0           ; R6 := UpValue[0]
  28: GETTABLE	R6 R6 RK259    ; R6 := R6["isStrNil"]
  29: MOVE	R7 R1              ; R7 := R1
  30: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  31: TEST	R6 1 0             ; if not R6 then goto 0
  32: JMP	23                  ; goto 23
  33: EQ	R4 R262 0            ; if R4 == 1 then goto 0
  34: JMP	11                  ; goto 11
  35: GETUPVAL	R6 2           ; R6 := UpValue[2]
  36: GETTABLE	R6 R6 RK263    ; R6 := R6["sha256"]
  37: MOVE	R7 R1              ; R7 := R1
  38: MOVE	R8 R5              ; R8 := R5
  39: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  40: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  41: EQ	R6 R2 0              ; if R6 == R2 then goto 0
  42: JMP	13                  ; goto 13
  43: LOADBOOL	R6 1 0         ; R6 := true
  44: RETURN	R6 2             ; return R6, R7
  45: JMP	10                  ; goto 10
  46: GETUPVAL	R6 2           ; R6 := UpValue[2]
  47: GETTABLE	R6 R6 RK264    ; R6 := R6["sha1"]
  48: MOVE	R7 R1              ; R7 := R1
  49: MOVE	R8 R5              ; R8 := R5
  50: CONCAT	R7 R7 R8         ; R7 := R7 .. R8
  51: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  52: EQ	R6 R2 0              ; if R6 == R2 then goto 0
  53: JMP	2                   ; goto 2
  54: LOADBOOL	R6 1 0         ; R6 := true
  55: RETURN	R6 2             ; return R6, R7
  56: GETUPVAL	R6 3           ; R6 := UpValue[3]
  57: GETTABLE	R6 R6 RK265    ; R6 := R6["log"]
  58: LOADK	R7 K10            ; R7 := 4
  59: GETGLOBAL	R8 K11        ; R8 := luci
  60: GETTABLE	R8 R8 RK268    ; R8 := R8["http"]
  61: GETTABLE	R8 R8 RK269    ; R8 := R8["getenv"]
  62: LOADK	R9 K14            ; R9 := "REMOTE_ADDR"
  63: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  64: TEST	R8 1 0             ; if not R8 then goto 0
  65: JMP	1                   ; goto 1
  66: LOADK	R8 K15            ; R8 := ""
  67: LOADK	R9 K16            ; R9 := " Authentication failed"
  68: CONCAT	R8 R8 R9         ; R8 := R8 .. R9
  69: MOVE	R9 R1              ; R9 := R1
  70: MOVE	R10 R5             ; R10 := R5
  71: MOVE	R11 R2             ; R11 := R2
  72: CALL	R6 6 1             ; R6 := R6(...) -- b=6, c=1
  73: LOADBOOL	R6 0 0         ; R6 := false
  74: RETURN	R6 2             ; return R6, R7
  75: RETURN	R0 1             ; return R0

-- SubChunk 17:
-- SubChunk: lineDefined=272, lastLineDefined=323, numParams=2, isVararg=0, maxStackSize=19

-- Register Operations:
   0: GETGLOBAL	R2 K0         ; R2 := require
   1: LOADK	R3 K1             ; R3 := "luci.util"
   2: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   3: GETGLOBAL	R3 K0         ; R3 := require
   4: LOADK	R4 K2             ; R4 := "luci.sys"
   5: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
   6: GETGLOBAL	R4 K0         ; R4 := require
   7: LOADK	R5 K3             ; R5 := "xiaoqiang.util.XQCryptoUtil"
   8: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
   9: TEST	R0 0 0             ; if  R0 then goto 0
  10: JMP	136                 ; goto 136
  11: TEST	R1 0 0             ; if  R1 then goto 0
  12: JMP	134                 ; goto 134
  13: GETUPVAL	R5 0           ; R5 := UpValue[0]
  14: GETTABLE	R5 R5 RK260    ; R5 := R5["macFormat"]
  15: MOVE	R6 R1              ; R6 := R1
  16: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  17: MOVE	R1 R5              ; R1 := R5
  18: GETTABLE	R5 R2 RK261    ; R5 := R2["split"]
  19: MOVE	R6 R0              ; R6 := R0
  20: LOADK	R7 K6             ; R7 := "_"
  21: CALL	R5 3 2             ; R5 := R5(...) -- b=3, c=2
  22: LEN	R6 R5               ; R6 := #R5
  23: EQ	R6 R263 0            ; if R6 == 4 then goto 0
  24: JMP	11                  ; goto 11
  25: GETUPVAL	R6 1           ; R6 := UpValue[1]
  26: GETTABLE	R6 R6 RK264    ; R6 := R6["log"]
  27: LOADK	R7 K9             ; R7 := 6
  28: LOADK	R8 K10            ; R8 := "Nonce check failed!: Illegal"
  29: MOVE	R9 R0              ; R9 := R0
  30: LOADK	R10 K11           ; R10 := " remote MAC address:"
  31: MOVE	R11 R1             ; R11 := R1
  32: CONCAT	R8 R8 R11        ; R8 := R8 .. R11
  33: CALL	R6 3 1             ; R6 := R6(...) -- b=3, c=1
  34: LOADBOOL	R6 0 0         ; R6 := false
  35: RETURN	R6 2             ; return R6, R7
  36: GETGLOBAL	R6 K12        ; R6 := tonumber
  37: GETTABLE	R7 R5 RK269    ; R7 := R5[1]
  38: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  39: GETGLOBAL	R7 K14        ; R7 := tostring
  40: GETTABLE	R8 R5 RK271    ; R8 := R5[2]
  41: CALL	R7 2 2             ; R7 := R7(...) -- b=2, c=2
  42: GETGLOBAL	R8 K12        ; R8 := tonumber
  43: GETTABLE	R9 R5 RK272    ; R9 := R5[3]
  44: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  45: TEST	R6 0 0             ; if  R6 then goto 0
  46: JMP	100                 ; goto 100
  47: TEST	R7 0 0             ; if  R7 then goto 0
  48: JMP	98                  ; goto 98
  49: GETGLOBAL	R9 K0         ; R9 := require
  50: LOADK	R10 K17           ; R10 := "xiaoqiang.util.XQSysUtil"
  51: CALL	R9 2 2             ; R9 := R9(...) -- b=2, c=2
  52: GETTABLE	R10 R9 RK274   ; R10 := R9["getEncryptMode"]
  53: CALL	R10 1 2            ; R10 := R10(...) -- b=1, c=2
  54: LOADNIL	R11 R11         ; R11 := nil
  55: EQ	R10 R269 0           ; if R10 == 1 then goto 0
  56: JMP	7                   ; goto 7
  57: GETTABLE	R12 R4 RK275   ; R12 := R4["sha256"]
  58: MOVE	R13 R6             ; R13 := R6
  59: MOVE	R14 R7             ; R14 := R7
  60: CONCAT	R13 R13 R14      ; R13 := R13 .. R14
  61: CALL	R12 2 2            ; R12 := R12(...) -- b=2, c=2
  62: MOVE	R11 R12            ; R11 := R12
  63: JMP	6                   ; goto 6
  64: GETTABLE	R12 R4 RK276   ; R12 := R4["sha1"]
  65: MOVE	R13 R6             ; R13 := R6
  66: MOVE	R14 R7             ; R14 := R7
  67: CONCAT	R13 R13 R14      ; R13 := R13 .. R14
  68: CALL	R12 2 2            ; R12 := R12(...) -- b=2, c=2
  69: MOVE	R11 R12            ; R11 := R12
  70: LT	R263 R6 0            ; if 4 < R6 then goto 0
  71: JMP	11                  ; goto 11
  72: GETUPVAL	R12 1          ; R12 := UpValue[1]
  73: GETTABLE	R12 R12 RK264  ; R12 := R12["log"]
  74: LOADK	R13 K9            ; R13 := 6
  75: LOADK	R14 K21           ; R14 := "Nonce check failed! Type error:"
  76: MOVE	R15 R0             ; R15 := R0
  77: LOADK	R16 K11           ; R16 := " remote MAC address:"
  78: MOVE	R17 R1             ; R17 := R1
  79: CONCAT	R14 R14 R17      ; R14 := R14 .. R17
  80: CALL	R12 3 1            ; R12 := R12(...) -- b=3, c=1
  81: LOADBOOL	R12 0 0        ; R12 := false
  82: RETURN	R12 2            ; return R12, R13
  83: GETGLOBAL	R12 K22       ; R12 := readNonce
  84: MOVE	R13 R11            ; R13 := R11
  85: CALL	R12 2 2            ; R12 := R12(...) -- b=2, c=2
  86: TEST	R12 0 0            ; if  R12 then goto 0
  87: JMP	46                  ; goto 46
  88: GETGLOBAL	R13 K23       ; R13 := type
  89: MOVE	R14 R12            ; R14 := R12
  90: CALL	R13 2 2            ; R13 := R13(...) -- b=2, c=2
  91: EQ	R13 R280 0           ; if R13 == "table" then goto 0
  92: JMP	41                  ; goto 41
  93: GETGLOBAL	R13 K12       ; R13 := tonumber
  94: GETTABLE	R14 R12 RK281  ; R14 := R12["mark"]
  95: CALL	R13 2 2            ; R13 := R13(...) -- b=2, c=2
  96: LT	R13 R8 0             ; if R13 < R8 then goto 0
  97: JMP	25                  ; goto 25
  98: GETTABLE	R13 R12 RK282  ; R13 := R12["mac"]
  99: EQ	R1 R13 0             ; if R1 == R13 then goto 0
 100: JMP	11                  ; goto 11
 101: GETUPVAL	R13 1          ; R13 := UpValue[1]
 102: GETTABLE	R13 R13 RK264  ; R13 := R13["log"]
 103: LOADK	R14 K9            ; R14 := 6
 104: LOADK	R15 K27           ; R15 := "Mac address changed: "
 105: GETTABLE	R16 R12 RK282  ; R16 := R12["mac"]
 106: LOADK	R17 K28           ; R17 := " --> "
 107: MOVE	R18 R1             ; R18 := R1
 108: CONCAT	R15 R15 R18      ; R15 := R15 .. R18
 109: MOVE	R16 R12            ; R16 := R12
 110: MOVE	R17 R0             ; R17 := R0
 111: CALL	R13 5 1            ; R13 := R13(...) -- b=5, c=1
 112: GETGLOBAL	R13 K14       ; R13 := tostring
 113: MOVE	R14 R8             ; R14 := R8
 114: CALL	R13 2 2            ; R13 := R13(...) -- b=2, c=2
 115: SETTABLE	R12 RK281 R13  ; R12["mark"] := R13
 116: GETGLOBAL	R13 K29       ; R13 := writeNonce
 117: MOVE	R14 R11            ; R14 := R11
 118: MOVE	R15 R12            ; R15 := R12
 119: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 120: LOADBOOL	R13 1 0        ; R13 := true
 121: RETURN	R13 2            ; return R13, R14
 122: JMP	24                  ; goto 24
 123: GETUPVAL	R13 1          ; R13 := UpValue[1]
 124: GETTABLE	R13 R13 RK264  ; R13 := R13["log"]
 125: LOADK	R14 K9            ; R14 := 6
 126: LOADK	R15 K30           ; R15 := "Nonce check failed!: Not match"
 127: MOVE	R16 R0             ; R16 := R0
 128: LOADK	R17 K11           ; R17 := " remote MAC address:"
 129: MOVE	R18 R1             ; R18 := R1
 130: CONCAT	R15 R15 R18      ; R15 := R15 .. R18
 131: MOVE	R16 R12            ; R16 := R12
 132: CALL	R13 4 1            ; R13 := R13(...) -- b=4, c=1
 133: JMP	13                  ; goto 13
 134: NEWTABLE	R13            ; R13 := {}
 135: MOVE	R12 R13            ; R12 := R13
 136: GETGLOBAL	R13 K14       ; R13 := tostring
 137: MOVE	R14 R8             ; R14 := R8
 138: CALL	R13 2 2            ; R13 := R13(...) -- b=2, c=2
 139: SETTABLE	R12 RK281 R13  ; R12["mark"] := R13
 140: SETTABLE	R12 RK282 R1   ; R12["mac"] := R1
 141: GETGLOBAL	R13 K29       ; R13 := writeNonce
 142: MOVE	R14 R11            ; R14 := R11
 143: MOVE	R15 R12            ; R15 := R12
 144: CALL	R13 3 1            ; R13 := R13(...) -- b=3, c=1
 145: LOADBOOL	R13 1 0        ; R13 := true
 146: RETURN	R13 2            ; return R13, R14
 147: LOADBOOL	R5 0 0         ; R5 := false
 148: RETURN	R5 2             ; return R5, R6
 149: RETURN	R0 1             ; return R0

-- SubChunk 18:
-- SubChunk: lineDefined=327, lastLineDefined=354, numParams=0, isVararg=0, maxStackSize=17

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "luci.http.protocol"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "xiaoqiang.common.XQConfigs"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K0         ; R2 := require
   7: LOADK	R3 K3             ; R3 := "xiaoqiang.util.XQCryptoUtil"
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: LOADNIL	R3 R3           ; R3 := nil
  10: LOADK	R4 K4             ; R4 := "http://miwifi.com/cgi-bin/luci/web/xmaccount"
  11: LOADK	R5 K5             ; R5 := "followup="
  12: MOVE	R6 R4              ; R6 := R4
  13: CONCAT	R5 R5 R6         ; R5 := R5 .. R6
  14: GETGLOBAL	R6 K0         ; R6 := require
  15: LOADK	R7 K6             ; R7 := "xiaoqiang.util.XQSysUtil"
  16: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  17: GETTABLE	R7 R6 RK263    ; R7 := R6["getEncryptMode"]
  18: CALL	R7 1 2             ; R7 := R7(...) -- b=1, c=2
  19: LOADNIL	R8 R8           ; R8 := nil
  20: EQ	R7 R264 0            ; if R7 == 1 then goto 0
  21: JMP	7                   ; goto 7
  22: GETTABLE	R9 R2 RK265    ; R9 := R2["binaryBase64Enc"]
  23: GETTABLE	R10 R2 RK266   ; R10 := R2["sha256Binary"]
  24: MOVE	R11 R5             ; R11 := R5
  25: CALL	R10 2 0            ; R10 := R10(...) -- b=2, c=0
  26: CALL	R9 0 2             ; R9 := R9(...) -- b=0, c=2
  27: MOVE	R8 R9              ; R8 := R9
  28: JMP	6                   ; goto 6
  29: GETTABLE	R9 R2 RK265    ; R9 := R2["binaryBase64Enc"]
  30: GETTABLE	R10 R2 RK267   ; R10 := R2["sha1Binary"]
  31: MOVE	R11 R5             ; R11 := R5
  32: CALL	R10 2 0            ; R10 := R10(...) -- b=2, c=0
  33: CALL	R9 0 2             ; R9 := R9(...) -- b=0, c=2
  34: MOVE	R8 R9              ; R8 := R9
  35: GETTABLE	R9 R1 RK268    ; R9 := R1["SERVER_CONFIG"]
  36: EQ	R9 R269 0            ; if R9 == 0 then goto 0
  37: JMP	14                  ; goto 14
  38: GETTABLE	R9 R1 RK270    ; R9 := R1["PASSPORT_CONFIG_ONLINE_URL"]
  39: LOADK	R10 K15           ; R10 := "?callback="
  40: GETTABLE	R11 R0 RK272   ; R11 := R0["urlencode"]
  41: GETTABLE	R12 R1 RK273   ; R12 := R1["XQ_SERVER_ONLINE_STS_URL"]
  42: LOADK	R13 K18           ; R13 := "?sign="
  43: MOVE	R14 R8             ; R14 := R8
  44: LOADK	R15 K19           ; R15 := "&followup="
  45: MOVE	R16 R4             ; R16 := R4
  46: CONCAT	R12 R12 R16      ; R12 := R12 .. R16
  47: CALL	R11 2 2            ; R11 := R11(...) -- b=2, c=2
  48: LOADK	R12 K20           ; R12 := "&sid="
  49: GETUPVAL	R13 0          ; R13 := UpValue[0]
  50: CONCAT	R3 R9 R13        ; R3 := R9 .. R13
  51: JMP	16                  ; goto 16
  52: GETTABLE	R9 R1 RK268    ; R9 := R1["SERVER_CONFIG"]
  53: EQ	R9 R264 0            ; if R9 == 1 then goto 0
  54: JMP	13                  ; goto 13
  55: GETTABLE	R9 R1 RK277    ; R9 := R1["PASSPORT_CONFIG_PREVIEW_URL"]
  56: LOADK	R10 K15           ; R10 := "?callback="
  57: GETTABLE	R11 R0 RK272   ; R11 := R0["urlencode"]
  58: GETTABLE	R12 R1 RK278   ; R12 := R1["XQ_SERVER_STAGING_STS_URL"]
  59: LOADK	R13 K18           ; R13 := "?sign="
  60: MOVE	R14 R8             ; R14 := R8
  61: LOADK	R15 K19           ; R15 := "&followup="
  62: MOVE	R16 R4             ; R16 := R4
  63: CONCAT	R12 R12 R16      ; R12 := R12 .. R16
  64: CALL	R11 2 2            ; R11 := R11(...) -- b=2, c=2
  65: LOADK	R12 K20           ; R12 := "&sid="
  66: GETUPVAL	R13 0          ; R13 := UpValue[0]
  67: CONCAT	R3 R9 R13        ; R3 := R9 .. R13
  68: RETURN	R3 2             ; return R3, R4
  69: RETURN	R0 1             ; return R0

-- SubChunk 19:
-- SubChunk: lineDefined=356, lastLineDefined=376, numParams=0, isVararg=0, maxStackSize=13

-- Register Operations:
   0: GETGLOBAL	R0 K0         ; R0 := require
   1: LOADK	R1 K1             ; R1 := "xiaoqiang.util.XQSysUtil"
   2: CALL	R0 2 2             ; R0 := R0(...) -- b=2, c=2
   3: GETGLOBAL	R1 K0         ; R1 := require
   4: LOADK	R2 K2             ; R2 := "luci.http.protocol"
   5: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   6: GETGLOBAL	R2 K0         ; R2 := require
   7: LOADK	R3 K3             ; R3 := "xiaoqiang.common.XQConfigs"
   8: CALL	R2 2 2             ; R2 := R2(...) -- b=2, c=2
   9: LOADNIL	R3 R3           ; R3 := nil
  10: GETTABLE	R4 R0 RK260    ; R4 := R0["getPassportBindInfo"]
  11: CALL	R4 1 2             ; R4 := R4(...) -- b=1, c=2
  12: GETUPVAL	R5 0           ; R5 := UpValue[0]
  13: GETTABLE	R5 R5 RK261    ; R5 := R5["isStrNil"]
  14: MOVE	R6 R4              ; R6 := R4
  15: CALL	R5 2 2             ; R5 := R5(...) -- b=2, c=2
  16: TEST	R5 0 0             ; if  R5 then goto 0
  17: JMP	2                   ; goto 2
  18: LOADK	R5 K6             ; R5 := ""
  19: RETURN	R5 2             ; return R5, R6
  20: LOADK	R5 K7             ; R5 := "http://miwifi.com/cgi-bin/luci/web/home"
  21: GETTABLE	R6 R2 RK264    ; R6 := R2["SERVER_CONFIG"]
  22: EQ	R6 R265 0            ; if R6 == 0 then goto 0
  23: JMP	11                  ; goto 11
  24: GETTABLE	R6 R2 RK266    ; R6 := R2["PASSPORT_LOGOUT_ONLINE_URL"]
  25: LOADK	R7 K11            ; R7 := "?callback="
  26: GETTABLE	R8 R1 RK268    ; R8 := R1["urlencode"]
  27: MOVE	R9 R5              ; R9 := R5
  28: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  29: LOADK	R9 K13            ; R9 := "&sid="
  30: GETUPVAL	R10 1          ; R10 := UpValue[1]
  31: LOADK	R11 K14           ; R11 := "&userId="
  32: MOVE	R12 R4             ; R12 := R4
  33: CONCAT	R3 R6 R12        ; R3 := R6 .. R12
  34: JMP	13                  ; goto 13
  35: GETTABLE	R6 R2 RK264    ; R6 := R2["SERVER_CONFIG"]
  36: EQ	R6 R271 0            ; if R6 == 1 then goto 0
  37: JMP	10                  ; goto 10
  38: GETTABLE	R6 R2 RK272    ; R6 := R2["PASSPORT_LOGOUT_PREVIEW_URL"]
  39: LOADK	R7 K11            ; R7 := "?callback="
  40: GETTABLE	R8 R1 RK268    ; R8 := R1["urlencode"]
  41: MOVE	R9 R5              ; R9 := R5
  42: CALL	R8 2 2             ; R8 := R8(...) -- b=2, c=2
  43: LOADK	R9 K13            ; R9 := "&sid="
  44: GETUPVAL	R10 1          ; R10 := UpValue[1]
  45: LOADK	R11 K14           ; R11 := "&userId="
  46: MOVE	R12 R4             ; R12 := R4
  47: CONCAT	R3 R6 R12        ; R3 := R6 .. R12
  48: RETURN	R3 2             ; return R3, R4
  49: RETURN	R0 1             ; return R0

-- SubChunk 20:
-- SubChunk: lineDefined=424, lastLineDefined=460, numParams=1, isVararg=0, maxStackSize=6

-- Register Operations:
   0: LOADK	R1 K0             ; R1 := 0
   1: NEWTABLE	R2             ; R2 := {}
   2: SETTABLE	R2 RK257 R258  ; R2["l"] := 0.5
   3: GETUPVAL	R3 0           ; R3 := UpValue[0]
   4: GETTABLE	R3 R3 RK259    ; R3 := R3["isStrNil"]
   5: MOVE	R4 R0              ; R4 := R0
   6: CALL	R3 2 2             ; R3 := R3(...) -- b=2, c=2
   7: TEST	R3 0 0             ; if  R3 then goto 0
   8: JMP	2                   ; goto 2
   9: LOADK	R3 K4             ; R3 := 1
  10: RETURN	R3 2             ; return R3, R4
  11: LEN	R3 R0               ; R3 := #R0
  12: LT	R3 R261 0            ; if R3 < 6 then goto 0
  13: JMP	3                   ; goto 3
  14: LOADK	R3 K4             ; R3 := 1
  15: RETURN	R3 2             ; return R3, R4
  16: JMP	12                  ; goto 12
  17: GETTABLE	R3 R2 RK257    ; R3 := R2["l"]
  18: GETGLOBAL	R4 K6         ; R4 := math
  19: GETTABLE	R4 R4 RK263    ; R4 := R4["sqrt"]
  20: LEN	R5 R0               ; R5 := #R0
  21: SUB	R5 R5 R261          ; R5 := R5 - R261
  22: DIV	R5 R5 R264          ; R5 := R5 / R264
  23: CALL	R4 2 2             ; R4 := R4(...) -- b=2, c=2
  24: MUL	R3 R3 R4            ; R3 := R3 * R4
  25: LT	R264 R3 0            ; if 2 < R3 then goto 0
  26: JMP	1                   ; goto 1
  27: LOADK	R3 K4             ; R3 := 1
  28: ADD	R1 R1 R3            ; R1 := R1 + R3
  29: SELF	R3 R0 R265         ; R3, R4 := R0, R265
  30: LOADK	R5 K10            ; R5 := "%d"
  31: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  32: TEST	R3 0 0             ; if  R3 then goto 0
  33: JMP	1                   ; goto 1
  34: ADD	R1 R1 R260          ; R1 := R1 + R260
  35: SELF	R3 R0 R265         ; R3, R4 := R0, R265
  36: LOADK	R5 K11            ; R5 := "%l"
  37: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  38: TEST	R3 0 0             ; if  R3 then goto 0
  39: JMP	1                   ; goto 1
  40: ADD	R1 R1 R260          ; R1 := R1 + R260
  41: SELF	R3 R0 R265         ; R3, R4 := R0, R265
  42: LOADK	R5 K12            ; R5 := "%u"
  43: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  44: TEST	R3 0 0             ; if  R3 then goto 0
  45: JMP	1                   ; goto 1
  46: ADD	R1 R1 R260          ; R1 := R1 + R260
  47: SELF	R3 R0 R265         ; R3, R4 := R0, R265
  48: LOADK	R5 K13            ; R5 := "%W"
  49: CALL	R3 3 2             ; R3 := R3(...) -- b=3, c=2
  50: TEST	R3 0 0             ; if  R3 then goto 0
  51: JMP	1                   ; goto 1
  52: ADD	R1 R1 R260          ; R1 := R1 + R260
  53: LT	R1 R264 0            ; if R1 < 2 then goto 0
  54: JMP	3                   ; goto 3
  55: LOADK	R3 K4             ; R3 := 1
  56: RETURN	R3 2             ; return R3, R4
  57: JMP	7                   ; goto 7
  58: LT	R1 R270 0            ; if R1 < 3 then goto 0
  59: JMP	3                   ; goto 3
  60: LOADK	R3 K8             ; R3 := 2
  61: RETURN	R3 2             ; return R3, R4
  62: JMP	2                   ; goto 2
  63: LOADK	R3 K14            ; R3 := 3
  64: RETURN	R3 2             ; return R3, R4
  65: RETURN	R0 1             ; return R0

-- SubChunk 21:
-- SubChunk: lineDefined=471, lastLineDefined=485, numParams=1, isVararg=0, maxStackSize=11

-- Register Operations:
   0: GETUPVAL	R1 0           ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 RK256    ; R1 := R1["isStrNil"]
   2: MOVE	R2 R0              ; R2 := R0
   3: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   4: TEST	R1 0 0             ; if  R1 then goto 0
   5: JMP	3                   ; goto 3
   6: LOADBOOL	R1 1 0         ; R1 := true
   7: RETURN	R1 2             ; return R1, R2
   8: JMP	5                   ; goto 5
   9: GETGLOBAL	R1 K1         ; R1 := string
  10: GETTABLE	R1 R1 RK258    ; R1 := R1["lower"]
  11: MOVE	R2 R0              ; R2 := R0
  12: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
  13: MOVE	R0 R1              ; R0 := R1
  14: GETGLOBAL	R1 K3         ; R1 := ipairs
  15: GETGLOBAL	R2 K4         ; R2 := KEY_WORDS
  16: CALL	R1 2 4             ; R1 := R1(...) -- b=2, c=4
  17: JMP	16                  ; goto 16
  18: SELF	R6 R0 R261         ; R6, R7 := R0, R261
  19: MOVE	R8 R5              ; R8 := R5
  20: CALL	R6 3 2             ; R6 := R6(...) -- b=3, c=2
  21: TEST	R6 0 0             ; if  R6 then goto 0
  22: JMP	11                  ; goto 11
  23: GETGLOBAL	R6 K6         ; R6 := require
  24: LOADK	R7 K7             ; R7 := "xiaoqiang.XQLog"
  25: CALL	R6 2 2             ; R6 := R6(...) -- b=2, c=2
  26: GETTABLE	R7 R6 RK264    ; R7 := R6["log"]
  27: LOADK	R8 K9             ; R8 := 6
  28: LOADK	R9 K10            ; R9 := "Keyword Warning:"
  29: MOVE	R10 R0             ; R10 := R0
  30: CONCAT	R9 R9 R10        ; R9 := R9 .. R10
  31: CALL	R7 3 1             ; R7 := R7(...) -- b=3, c=1
  32: LOADBOOL	R7 0 0         ; R7 := false
  33: RETURN	R7 2             ; return R7, R8
  34: TFORLOOP	R1 0 2         ; tforloop R1, R2 -- b=0, c=2
  35: JMP	-18                 ; goto -18
  36: LOADBOOL	R1 1 0         ; R1 := true
  37: RETURN	R1 2             ; return R1, R2
  38: RETURN	R0 1             ; return R0

-- SubChunk 22:
-- SubChunk: lineDefined=487, lastLineDefined=489, numParams=1, isVararg=0, maxStackSize=3

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := _keyWordsFilter
   1: MOVE	R2 R0              ; R2 := R0
   2: TAILCALL	R1 2 0         ; tailcall R1(...) -- b=2, c=0
   3: RETURN	R1 0             ; return
   4: RETURN	R0 1             ; return R0

-- SubChunk 23:
-- SubChunk: lineDefined=533, lastLineDefined=549, numParams=2, isVararg=0, maxStackSize=8

-- Register Operations:
   0: TEST	R0 0 0             ; if  R0 then goto 0
   1: JMP	2                   ; goto 2
   2: TEST	R1 1 0             ; if not R1 then goto 0
   3: JMP	1                   ; goto 1
   4: RETURN	R1 2             ; return R1, R2
   5: GETUPVAL	R2 0           ; R2 := UpValue[0]
   6: GETTABLE	R2 R2 RK0      ; R2 := R2[R0]
   7: TEST	R2 0 0             ; if  R2 then goto 0
   8: JMP	1                   ; goto 1
   9: RETURN	R1 2             ; return R1, R2
  10: GETGLOBAL	R2 K0         ; R2 := string
  11: GETTABLE	R2 R2 RK257    ; R2 := R2["find"]
  12: MOVE	R3 R1              ; R3 := R1
  13: GETUPVAL	R4 1           ; R4 := UpValue[1]
  14: CALL	R2 3 2             ; R2 := R2(...) -- b=3, c=2
  15: TEST	R2 0 0             ; if  R2 then goto 0
  16: JMP	11                  ; goto 11
  17: GETUPVAL	R2 2           ; R2 := UpValue[2]
  18: GETTABLE	R2 R2 RK258    ; R2 := R2["log"]
  19: LOADK	R3 K3             ; R3 := 3
  20: LOADK	R4 K4             ; R4 := "hackCheck match key:"
  21: MOVE	R5 R0              ; R5 := R0
  22: LOADK	R6 K5             ; R6 := " val:"
  23: MOVE	R7 R1              ; R7 := R1
  24: CONCAT	R4 R4 R7         ; R4 := R4 .. R7
  25: CALL	R2 3 1             ; R2 := R2(...) -- b=3, c=1
  26: LOADNIL	R2 R2           ; R2 := nil
  27: RETURN	R2 2             ; return R2, R3
  28: RETURN	R1 2             ; return R1, R2
  29: RETURN	R0 1             ; return R0

-- SubChunk 24:
-- SubChunk: lineDefined=551, lastLineDefined=558, numParams=1, isVararg=0, maxStackSize=4

-- Register Operations:
   0: GETGLOBAL	R1 K0         ; R1 := string
   1: GETTABLE	R1 R1 RK257    ; R1 := R1["find"]
   2: MOVE	R2 R0              ; R2 := R0
   3: GETUPVAL	R3 0           ; R3 := UpValue[0]
   4: CALL	R1 3 2             ; R1 := R1(...) -- b=3, c=2
   5: TEST	R1 0 0             ; if  R1 then goto 0
   6: JMP	2                   ; goto 2
   7: LOADK	R1 K2             ; R1 := ""
   8: RETURN	R1 2             ; return R1, R2
   9: RETURN	R0 2             ; return R0, R1
  10: RETURN	R0 1             ; return R0

-- SubChunk 25:
-- SubChunk: lineDefined=560, lastLineDefined=566, numParams=1, isVararg=0, maxStackSize=5

-- Register Operations:
   0: GETUPVAL	R1 0           ; R1 := UpValue[0]
   1: GETTABLE	R1 R1 RK256    ; R1 := R1["isStrNil"]
   2: MOVE	R2 R0              ; R2 := R0
   3: CALL	R1 2 2             ; R1 := R1(...) -- b=2, c=2
   4: TEST	R1 0 0             ; if  R1 then goto 0
   5: JMP	3                   ; goto 3
   6: LOADK	R1 K1             ; R1 := ""
   7: RETURN	R1 2             ; return R1, R2
   8: JMP	29                  ; goto 29
   9: SELF	R1 R0 R258         ; R1, R2 := R0, R258
  10: LOADK	R3 K3             ; R3 := "\"
  11: LOADK	R4 K4             ; R4 := "\\"
  12: CALL	R1 4 2             ; R1 := R1(...) -- b=4, c=2
  13: SELF	R1 R1 R258         ; R1, R2 := R1, R258
  14: LOADK	R3 K5             ; R3 := "`"
  15: LOADK	R4 K6             ; R4 := "\`"
  16: CALL	R1 4 2             ; R1 := R1(...) -- b=4, c=2
  17: SELF	R1 R1 R258         ; R1, R2 := R1, R258
  18: LOADK	R3 K7             ; R3 := """
  19: LOADK	R4 K8             ; R4 := "\""
  20: CALL	R1 4 2             ; R1 := R1(...) -- b=4, c=2
  21: SELF	R1 R1 R258         ; R1, R2 := R1, R258
  22: LOADK	R3 K9             ; R3 := "%$"
  23: LOADK	R4 K10            ; R4 := "\$"
  24: CALL	R1 4 2             ; R1 := R1(...) -- b=4, c=2
  25: SELF	R1 R1 R258         ; R1, R2 := R1, R258
  26: LOADK	R3 K11            ; R3 := "%&"
  27: LOADK	R4 K12            ; R4 := "\&"
  28: CALL	R1 4 2             ; R1 := R1(...) -- b=4, c=2
  29: SELF	R1 R1 R258         ; R1, R2 := R1, R258
  30: LOADK	R3 K13            ; R3 := "%|"
  31: LOADK	R4 K14            ; R4 := "\|"
  32: CALL	R1 4 2             ; R1 := R1(...) -- b=4, c=2
  33: SELF	R1 R1 R258         ; R1, R2 := R1, R258
  34: LOADK	R3 K15            ; R3 := "%;"
  35: LOADK	R4 K16            ; R4 := "\;"
  36: TAILCALL	R1 4 0         ; tailcall R1(...) -- b=4, c=0
  37: RETURN	R1 0             ; return
  38: RETURN	R0 1             ; return R0

