package com.github.relua.decompiler;

import com.github.relua.model.LuacFile;
import com.github.relua.util.BytecodeFormatter;

import java.util.List;

import com.github.relua.log.Logger;
import com.github.relua.model.Chunk;
import com.github.relua.model.Instruction;

/**
 * 反编译器主类
 */
public class Decompiler {
    private LuaCodeGenerator codeGenerator;

    /**
     * 构造函数
     */
    public Decompiler() {
        // this.codeGenerator = new LuaCodeGenerator();
    }

    /**
     * 反编译Luac文件
     * @param luacFile 解析后的Luac文件对象
     * @return 反编译后的Lua代码
     */
    public String decompile(LuacFile luacFile) {
        return decompile(luacFile, false);
    }
    
    /**
     * 反编译Luac文件
     * @param luacFile 解析后的Luac文件对象
     * @param showBytecode 是否显示字节码指令
     * @return 反编译后的Lua代码
     */
    public String decompile(LuacFile luacFile, boolean showBytecode) {
        if (luacFile == null || luacFile.getMainChunk() == null) {
            throw new IllegalArgumentException("Invalid LuacFile object");
        }

        Chunk mainChunk = luacFile.getMainChunk();
        Logger.debug(mainChunk.toString());
        
        
        // 生成Lua代码
        if (showBytecode) {
            return generateBytecode(mainChunk);
        } else {
            this.codeGenerator = new LuaCodeGenerator(mainChunk);
            return codeGenerator.generate(mainChunk, null);
        }
    }
    
    /**
     * 生成字节码输出
     * @param chunk 代码块
     * @return 字节码输出
     */
    private String generateBytecode(Chunk chunk) {
        return generateBytecode(chunk, 0);
    }
    
    /**
     * 生成字节码输出（递归）
     * @param chunk 代码块
     * @param depth 嵌套深度
     * @return 字节码输出
     */
    private String generateBytecode(Chunk chunk, int depth) {
        StringBuilder sb = new StringBuilder();
        
        // 生成缩进
        String indent = "";
        
        if (depth == 0) {
            sb.append("-- Lua Bytecode Instructions\n");
            sb.append("-- Generated by Relua\n\n");
        }
        
        // 输出代码块信息
        sb.append(indent).append(String.format("-- %sChunk: lineDefined=%d, lastLineDefined=%d, numParams=%d, isVararg=%d, maxStackSize=%d\n",
                depth > 0 ? "Sub" : "",
                chunk.getLineDefined(), chunk.getLastLineDefined(), chunk.getNumParams(), 
                chunk.getIsVararg(), chunk.getMaxStackSize()));
        sb.append(indent).append("\n");
        
        // 输出指令列表（R0 = xx格式）
        sb.append(indent).append("-- Register Operations:\n");
        int index = 0;
        for (Instruction instruction : chunk.getInstructions()) {
            sb.append(indent).append(BytecodeFormatter.formatInstruction(chunk, instruction, index++));
            sb.append("\n");
        }
        
        // 输出子代码块
        List<Chunk> subChunks = chunk.getSubChunks();
        if (!subChunks.isEmpty()) {
            sb.append(indent).append("\n");
            sb.append(indent).append("-- SubChunks:\n");
            sb.append(indent).append("\n");
            
            for (int i = 0; i < subChunks.size(); i++) {
                Chunk subChunk = subChunks.get(i);
                sb.append(indent).append(String.format("-- SubChunk %d:\n", i + 1));
                sb.append(generateBytecode(subChunk, depth + 1));
                sb.append(indent).append("\n");
            }
        }
        
        return sb.toString();
    }

    /**
     * 获取代码生成器
     * @return 代码生成器
     */
    public LuaCodeGenerator getCodeGenerator() {
        return codeGenerator;
    }
}