package com.github.relua.decompiler;

import com.github.relua.model.Chunk;
import com.github.relua.model.Instruction;
import com.github.relua.model.Constant;
import com.github.relua.model.Instruction.Opcode;

import java.util.List;
import java.util.Map;

/**
 * Lua代码生成器
 */
public class LuaCodeGenerator {
    private static final String INDENT = "    "; // 4个空格缩进
    private InstructionHandler instructionHandler;
    
    /**
     * 构造函数
     * @param instructionHandler 指令处理器，用于获取控制流和变量映射信息
     */
    public LuaCodeGenerator(InstructionHandler instructionHandler) {
        this.instructionHandler = instructionHandler;
    }
    
    /**
     * 无参构造函数，创建默认的指令处理器
     */
    public LuaCodeGenerator() {
        this.instructionHandler = new InstructionHandler();
    }
    
    /**
     * 生成Lua代码
     * @param chunk 代码块
     * @return 生成的Lua代码
     */
    public String generate(Chunk chunk) {
        // 先让指令处理器处理代码块，建立控制流和变量映射
        instructionHandler.processChunk(chunk);
        
        StringBuilder sb = new StringBuilder();
        
        // 生成代码块头部信息
        generateChunkHeader(chunk, sb);
        
        // 生成指令代码（使用基本块信息）
        generateBasicBlocksCode(chunk, sb, 0);
        
        // 生成子代码块
        generateSubChunks(chunk, sb, 0);
        
        return sb.toString();
    }
    
    /**
     * 生成代码块头部信息
     * @param chunk 代码块
     * @param sb 字符串构建器
     */
    private void generateChunkHeader(Chunk chunk, StringBuilder sb) {
        // 对于主代码块，添加一些元信息注释
        sb.append("-- Decompiled Lua code\n");
        sb.append("-- Generated by Relua\n\n");
    }
    
    /**
     * 生成基本块代码
     * @param chunk 代码块
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void generateBasicBlocksCode(Chunk chunk, StringBuilder sb, int indentLevel) {
        List<InstructionHandler.BasicBlock> basicBlocks = instructionHandler.getBasicBlocks();
        if (basicBlocks.isEmpty()) {
            // 如果没有基本块信息，回退到原始的指令生成方式
            generateInstructions(chunk, sb, indentLevel);
            return;
        }
        
        // 按顺序生成每个基本块的代码
        for (int i = 0; i < basicBlocks.size(); i++) {
            InstructionHandler.BasicBlock block = basicBlocks.get(i);
            generateBasicBlockCode(chunk, block, sb, indentLevel);
        }
    }
    
    /**
     * 生成单个基本块的代码
     * @param chunk 代码块
     * @param block 基本块
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void generateBasicBlockCode(Chunk chunk, InstructionHandler.BasicBlock block, 
                                       StringBuilder sb, int indentLevel) {
        List<Instruction> instructions = chunk.getInstructions();
        
        // 检查基本块类型，生成相应的控制流语句
        if (block.isIfBlock()) {
            generateIfBlockCode(chunk, block, sb, indentLevel);
        } else if (block.isLoopBlock()) {
            generateLoopBlockCode(chunk, block, sb, indentLevel);
        } else {
            // 普通基本块，直接生成指令代码
            for (int i = block.getStartIndex(); i <= block.getEndIndex(); i++) {
                if (i < instructions.size()) {
                    generateIndentedInstruction(chunk, instructions.get(i), i, sb, indentLevel);
                }
            }
        }
    }
    
    /**
     * 生成if块代码
     * @param chunk 代码块
     * @param block 基本块
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void generateIfBlockCode(Chunk chunk, InstructionHandler.BasicBlock block, 
                                    StringBuilder sb, int indentLevel) {
        List<Instruction> instructions = chunk.getInstructions();
        List<InstructionHandler.BasicBlock> successors = block.getSuccessors();
        
        // 生成if条件
        appendIndent(sb, indentLevel);
        sb.append("if ");
        
        // 获取条件寄存器
        int condReg = block.getConditionRegister();
        if (condReg != -1) {
            sb.append(getRegisterName(condReg, block.getStartIndex()));
        } else {
            // 条件寄存器无效，使用默认条件
            sb.append("true");
        }
        sb.append(" then\n");
        
        // 生成if块内的代码
        if (!successors.isEmpty()) {
            InstructionHandler.BasicBlock trueBlock = successors.get(0);
            for (int i = trueBlock.getStartIndex(); i <= trueBlock.getEndIndex(); i++) {
                if (i < instructions.size()) {
                    generateIndentedInstruction(chunk, instructions.get(i), i, sb, indentLevel + 1);
                }
            }
        }
        
        // 生成else块
        if (successors.size() > 1) {
            InstructionHandler.BasicBlock falseBlock = successors.get(1);
            if (falseBlock.isElseBlock()) {
                appendIndent(sb, indentLevel);
                sb.append("else\n");
                
                for (int i = falseBlock.getStartIndex(); i <= falseBlock.getEndIndex(); i++) {
                    if (i < instructions.size()) {
                        generateIndentedInstruction(chunk, instructions.get(i), i, sb, indentLevel + 1);
                    }
                }
            }
        }
        
        // 生成endif
        appendIndent(sb, indentLevel);
        sb.append("end\n");
    }
    
    /**
     * 生成循环块代码
     * @param chunk 代码块
     * @param block 基本块
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void generateLoopBlockCode(Chunk chunk, InstructionHandler.BasicBlock block, 
                                      StringBuilder sb, int indentLevel) {
        List<Instruction> instructions = chunk.getInstructions();
        
        // 简单生成while循环框架
        appendIndent(sb, indentLevel);
        sb.append("while true do\n");
        
        // 生成循环体代码
        for (int i = block.getStartIndex(); i <= block.getEndIndex(); i++) {
            if (i < instructions.size()) {
                generateIndentedInstruction(chunk, instructions.get(i), i, sb, indentLevel + 1);
            }
        }
        
        // 生成end
        appendIndent(sb, indentLevel);
        sb.append("end\n");
    }
    
    /**
     * 生成缩进的指令代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param index 指令索引
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void generateIndentedInstruction(Chunk chunk, Instruction instruction, int index, 
                                            StringBuilder sb, int indentLevel) {
        appendIndent(sb, indentLevel);
        generateInstructionCode(chunk, instruction, index, sb);
        sb.append("\n");
    }
    
    /**
     * 生成指令代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param index 指令索引
     * @param sb 字符串构建器
     */
    private void generateInstructions(Chunk chunk, StringBuilder sb, int indentLevel) {
        List<Instruction> instructions = chunk.getInstructions();
        
        for (int i = 0; i < instructions.size(); i++) {
            generateIndentedInstruction(chunk, instructions.get(i), i, sb, indentLevel);
        }
    }
    
    /**
     * 生成单个指令的Lua代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param index 指令索引
     * @param sb 字符串构建器
     */
    private void generateInstructionCode(Chunk chunk, Instruction instruction, int index, StringBuilder sb) {
        Opcode opcode = instruction.getOpcode();
        
        switch (opcode) {
            case LOADK:
                // 加载常量到寄存器
                int a = instruction.getA();
                int bx = instruction.getBx();
                Constant constant = chunk.getConstant(bx);
                if (constant != null) {
                    sb.append(String.format("%s = %s", getRegisterName(a, index), constant.toString()));
                } else {
                    sb.append(String.format("%s = nil -- Unknown constant index %d", getRegisterName(a, index), bx));
                }
                break;
            case LOADBOOL:
                // 加载布尔值到寄存器
                a = instruction.getA();
                boolean boolValue = instruction.getB() != 0;
                sb.append(String.format("%s = %b", getRegisterName(a, index), boolValue));
                break;
            case LOADNIL:
                // 加载nil到寄存器
                a = instruction.getA();
                int b = instruction.getB();
                for (int i = a; i <= b; i++) {
                    if (i > a) sb.append("; ");
                    sb.append(String.format("%s = nil", getRegisterName(i, index)));
                }
                break;
            case MOVE:
                // 寄存器间数据移动
                a = instruction.getA();
                b = instruction.getB();
                sb.append(String.format("%s = %s", getRegisterName(a, index), getRegisterName(b, index)));
                break;
            case ADD:
            case SUB:
            case MUL:
            case DIV:
            case MOD:
            case POW:
                // 算术运算
                generateArithmeticCode(chunk, instruction, index, sb);
                break;
            case UNM:
            case NOT:
            case LEN:
                // 一元运算
                generateUnaryCode(chunk, instruction, index, sb);
                break;
            case GETGLOBAL:
                // 获取全局变量
                a = instruction.getA();
                bx = instruction.getBx();
                constant = chunk.getConstant(bx);
                if (constant != null) {
                    String globalVarName = constant.getValue().toString();
                    // 使用getRegisterName获取寄存器名，避免硬编码
                    sb.append(String.format("%s = %s", getRegisterName(a, index), globalVarName));
                } else {
                    sb.append(String.format("%s = nil -- Unknown global variable index %d", getRegisterName(a, index), bx));
                }
                break;
            case SETGLOBAL:
                // 设置全局变量
                a = instruction.getA();
                bx = instruction.getBx();
                constant = chunk.getConstant(bx);
                if (constant != null) {
                    sb.append(String.format("%s = %s", constant.getValue(), getRegisterName(a, index)));
                } else {
                    sb.append(String.format("-- Unknown global variable index %d = %s", bx, getRegisterName(a, index)));
                }
                break;
            case GETTABLE:
                // 获取表元素
                generateGetTableCode(chunk, instruction, index, sb);
                break;
            case SETTABLE:
                // 设置表元素
                generateSetTableCode(chunk, instruction, index, sb);
                break;
            case CALL:
                // 函数调用
                generateCallCode(chunk, instruction, index, sb);
                break;
            case RETURN:
                // 返回
                generateReturnCode(chunk, instruction, index, sb);
                break;
            case CONCAT:
                // 字符串连接
                generateConcatCode(chunk, instruction, index, sb);
                break;
            case JMP:
                // 跳转指令，根据上下文决定是否生成代码
                if (!isUnconditionalJump(instruction)) {
                    sb.append("-- Jump instruction");
                }
                break;
            case TEST:
            case TESTSET:
            case EQ:
            case LT:
            case LE:
                // 条件指令，已经在基本块处理中生成了控制流语句
                sb.append("-- Condition check (handled by control flow)");
                break;
            default:
                // 其他指令，暂时输出指令信息
                sb.append(String.format("-- %s: A=%d, B=%d, C=%d, Bx=%d, sBx=%d",
                        opcode.name(),
                        instruction.getA(),
                        instruction.getB(),
                        instruction.getC(),
                        instruction.getBx(),
                        instruction.getSBx()));
                break;
        }
    }
    
    /**
     * 生成函数调用代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateCallCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        int c = instruction.getC();
        
        // 从寄存器状态获取函数名和类型
        String funcName = getRegisterName(a, instructionIndex);
        boolean isDirectCall = false;
        
        // 检查是否是直接函数调用（函数名已知）
        if (funcName.matches("^[a-zA-Z_][a-zA-Z0-9_]*$")) {
            // 函数名看起来像变量名，可能是直接调用
            isDirectCall = true;
        }
        
        // 生成函数调用
        if (isDirectCall) {
            // 直接调用形式：func(arg1, arg2, ...)
            sb.append(funcName);
            sb.append("(");
            
            // 生成参数
            if (b > 1) {
                for (int i = a + 1; i < a + b; i++) {
                    if (i > a + 1) sb.append(", ");
                    sb.append(getArgumentValue(chunk, i, instructionIndex));
                }
            }
            
            sb.append(")");
        } else {
            // 赋值形式：result = func(arg1, arg2, ...)
            sb.append(String.format("%s = %s(", getRegisterName(a, instructionIndex), funcName));
            
            // 生成参数
            if (b > 1) {
                for (int i = a + 1; i < a + b; i++) {
                    if (i > a + 1) sb.append(", ");
                    sb.append(getArgumentValue(chunk, i, instructionIndex));
                }
            }
            
            sb.append(")");
        }
    }
    
    /**
     * 获取参数值，根据寄存器状态返回合适的表达式
     * @param chunk 代码块
     * @param register 寄存器号
     * @param instructionIndex 指令索引
     * @return 参数值表达式
     */
    private String getArgumentValue(Chunk chunk, int register, int instructionIndex) {
        Map<Integer, InstructionHandler.RegisterState> registerStates = instructionHandler.getRegisterStatesByInstructionIndex(instructionIndex);
        if (registerStates.containsKey(register)) {
            InstructionHandler.RegisterState state = registerStates.get(register);
            // 根据寄存器类型返回合适的表达式
            switch (state.getType()) {
                case STRING:
                    return "\"" + state.getValue() + "\"";
                case NUMBER:
                case BOOLEAN:
                case NIL:
                    return state.getValue();
                case GLOBAL_VAR:
                case FUNCTION:
                    return state.getValue();
                default:
                    return getRegisterName(register, instructionIndex);
            }
        }
        return getRegisterName(register, instructionIndex);
    }
    
    /**
     * 生成返回代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateReturnCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        
        sb.append("return");
        
        if (b > 0) {
            sb.append(" ");
            for (int i = a; i < a + b; i++) {
                if (i > a) sb.append(", ");
                sb.append(getRegisterName(i, instructionIndex));
            }
        }
    }
    
    /**
     * 生成表访问代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateGetTableCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        int c = instruction.getC();
        
        sb.append(String.format("%s = %s[%s]", 
                getRegisterName(a, instructionIndex), 
                getRegisterName(b, instructionIndex), 
                getRegisterName(c, instructionIndex)));
    }
    
    /**
     * 生成表赋值代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateSetTableCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        int c = instruction.getC();
        
        sb.append(String.format("%s[%s] = %s", 
                getRegisterName(a, instructionIndex), 
                getRegisterName(b, instructionIndex), 
                getRegisterName(c, instructionIndex)));
    }
    
    /**
     * 生成字符串连接代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateConcatCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        int c = instruction.getC();
        
        sb.append(String.format("%s = ", getRegisterName(a, instructionIndex)));
        for (int i = b; i <= c; i++) {
            if (i > b) sb.append(" .. ");
            sb.append(getRegisterName(i, instructionIndex));
        }
    }
    
    /**
     * 生成算术运算代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateArithmeticCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        int c = instruction.getC();
        String op = getArithmeticOperator(instruction.getOpcode());
        
        sb.append(String.format("%s = %s %s %s", 
                getRegisterName(a, instructionIndex), 
                getRegisterName(b, instructionIndex), 
                op, 
                getRegisterName(c, instructionIndex)));
    }
    
    /**
     * 生成一元运算代码
     * @param chunk 代码块
     * @param instruction 指令
     * @param instructionIndex 指令索引
     * @param sb 字符串构建器
     */
    private void generateUnaryCode(Chunk chunk, Instruction instruction, int instructionIndex, StringBuilder sb) {
        int a = instruction.getA();
        int b = instruction.getB();
        String op = getUnaryOperator(instruction.getOpcode());
        
        sb.append(String.format("%s = %s%s", 
                getRegisterName(a, instructionIndex), 
                op, 
                getRegisterName(b, instructionIndex)));
    }
    
    /**
     * 获取算术运算符
     * @param opcode 操作码
     * @return 运算符字符串
     */
    private String getArithmeticOperator(Opcode opcode) {
        switch (opcode) {
            case ADD: return "+";
            case SUB: return "-";
            case MUL: return "*";
            case DIV: return "/";
            case MOD: return "%";
            case POW: return "^";
            default: return "?";
        }
    }
    
    /**
     * 获取一元运算符
     * @param opcode 操作码
     * @return 运算符字符串
     */
    private String getUnaryOperator(Opcode opcode) {
        switch (opcode) {
            case UNM: return "-";
            case NOT: return "not ";
            case LEN: return "#";
            default: return "?";
        }
    }
    
    /**
     * 获取寄存器名，如果有已知值则使用值，否则使用R+寄存器号
     * @param register 寄存器号
     * @param instructionIndex 指令索引，用于获取正确的寄存器状态
     * @return 寄存器名或变量名
     */
    private String getRegisterName(int register, int instructionIndex) {
        // 对于寄存器0，通常是函数调用的返回值，直接使用寄存器名
        if (register == 0) {
            return "R" + register;
        }
        
        Map<Integer, InstructionHandler.RegisterState> registerStates = instructionHandler.getRegisterStatesByInstructionIndex(instructionIndex);
        if (registerStates.containsKey(register)) {
            InstructionHandler.RegisterState state = registerStates.get(register);
            // 如果是全局变量或函数，直接使用其值作为名称
            if (state.getType() == InstructionHandler.RegisterValueType.GLOBAL_VAR || 
                state.getType() == InstructionHandler.RegisterValueType.FUNCTION) {
                return state.getValue();
            }
            // 对于其他类型，只在作为表达式使用时返回值，作为左值时应返回寄存器名
            // 这里我们简单处理，只在特定情况下返回值
        }
        return "R" + register;
    }
    
    /**
     * 重载方法，使用默认指令索引
     * @param register 寄存器号
     * @return 寄存器名或变量名
     */
    private String getRegisterName(int register) {
        return getRegisterName(register, 0);
    }
    
    /**
     * 检查是否是无条件跳转
     * @param instruction 指令
     * @return 是否是无条件跳转
     */
    private boolean isUnconditionalJump(Instruction instruction) {
        return instruction.getOpcode() == Opcode.JMP && instruction.getA() == 0;
    }
    
    /**
     * 生成子代码块
     * @param chunk 代码块
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void generateSubChunks(Chunk chunk, StringBuilder sb, int indentLevel) {
        List<Chunk> subChunks = chunk.getSubChunks();
        
        if (!subChunks.isEmpty()) {
            sb.append("\n");
            appendIndent(sb, indentLevel);
            sb.append("-- Sub-chunks (functions):\n");
            
            for (int i = 0; i < subChunks.size(); i++) {
                Chunk subChunk = subChunks.get(i);
                
                appendIndent(sb, indentLevel);
                sb.append(String.format("-- Sub-chunk %d:\n", i + 1));
                
                generateInstructions(subChunk, sb, indentLevel + 1);
                generateSubChunks(subChunk, sb, indentLevel + 1);
            }
        }
    }
    
    /**
     * 添加缩进
     * @param sb 字符串构建器
     * @param indentLevel 缩进级别
     */
    private void appendIndent(StringBuilder sb, int indentLevel) {
        for (int i = 0; i < indentLevel; i++) {
            sb.append(INDENT);
        }
    }
    
    /**
     * 设置指令处理器
     * @param instructionHandler 指令处理器
     */
    public void setInstructionHandler(InstructionHandler instructionHandler) {
        this.instructionHandler = instructionHandler;
    }
    
    /**
     * 获取指令处理器
     * @return 指令处理器
     */
    public InstructionHandler getInstructionHandler() {
        return instructionHandler;
    }
}